    { "glClearIndex", "<(GLfloat) c>", TclGL_glClearIndexCmd } ,
    { "glClearColor", "<(GLclampf) red> <(GLclampf) green> <(GLclampf) blue> <(GLclampf) alpha>", TclGL_glClearColorCmd } ,
    { "glClear", "<(GLbitfield) mask>", TclGL_glClearCmd } ,
    { "glIndexMask", "<(GLuint) mask>", TclGL_glIndexMaskCmd } ,
    { "glColorMask", "<(GLboolean) red> <(GLboolean) green> <(GLboolean) blue> <(GLboolean) alpha>", TclGL_glColorMaskCmd } ,
    { "glAlphaFunc", "<(GLenum) func> <(GLclampf) ref>", TclGL_glAlphaFuncCmd } ,
    { "glBlendFunc", "<(GLenum) sfactor> <(GLenum) dfactor>", TclGL_glBlendFuncCmd } ,
    { "glLogicOp", "<(GLenum) opcode>", TclGL_glLogicOpCmd } ,
    { "glCullFace", "<(GLenum) mode>", TclGL_glCullFaceCmd } ,
    { "glFrontFace", "<(GLenum) mode>", TclGL_glFrontFaceCmd } ,
    { "glPointSize", "<(GLfloat) size>", TclGL_glPointSizeCmd } ,
    { "glLineWidth", "<(GLfloat) width>", TclGL_glLineWidthCmd } ,
    { "glLineStipple", "<(GLint) factor> <(GLushort) pattern>", TclGL_glLineStippleCmd } ,
    { "glPolygonMode", "<(GLenum) face> <(GLenum) mode>", TclGL_glPolygonModeCmd } ,
    { "glPolygonOffset", "<(GLfloat) factor> <(GLfloat) units>", TclGL_glPolygonOffsetCmd } ,
    { "glPolygonStipple", "<(GLubyte) mask>", TclGL_glPolygonStippleCmd } ,
    { "glGetPolygonStipple", "<(GLubyte) mask>", TclGL_glGetPolygonStippleCmd } ,
    { "glEdgeFlag", "<(GLboolean) flag>", TclGL_glEdgeFlagCmd } ,
    { "glEdgeFlagv", "<(GLboolean) flag>", TclGL_glEdgeFlagvCmd } ,
    { "glScissor", "<(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height>", TclGL_glScissorCmd } ,
    { "glClipPlane", "<(GLenum) plane> <(GLdouble) equation>", TclGL_glClipPlaneCmd } ,
    { "glGetClipPlane", "<(GLenum) plane> <(GLdouble) equation>", TclGL_glGetClipPlaneCmd } ,
    { "glDrawBuffer", "<(GLenum) mode>", TclGL_glDrawBufferCmd } ,
    { "glReadBuffer", "<(GLenum) mode>", TclGL_glReadBufferCmd } ,
    { "glEnable", "<(GLenum) cap>", TclGL_glEnableCmd } ,
    { "glDisable", "<(GLenum) cap>", TclGL_glDisableCmd } ,
    { "glIsEnabled", "<(GLenum) cap>", TclGL_glIsEnabledCmd } ,
    { "glEnableClientState", "<(GLenum) cap>", TclGL_glEnableClientStateCmd } ,
    { "glDisableClientState", "<(GLenum) cap>", TclGL_glDisableClientStateCmd } ,
    { "glGetBooleanv", "<(GLenum) pname> <(GLboolean) params>", TclGL_glGetBooleanvCmd } ,
    { "glGetDoublev", "<(GLenum) pname> <(GLdouble) params>", TclGL_glGetDoublevCmd } ,
    { "glGetFloatv", "<(GLenum) pname> <(GLfloat) params>", TclGL_glGetFloatvCmd } ,
    { "glGetIntegerv", "<(GLenum) pname> <(GLint) params>", TclGL_glGetIntegervCmd } ,
    { "glPushAttrib", "<(GLbitfield) mask>", TclGL_glPushAttribCmd } ,
    { "glPopAttrib", "", TclGL_glPopAttribCmd } ,
    { "glPushClientAttrib", "<(GLbitfield) mask>", TclGL_glPushClientAttribCmd } ,
    { "glPopClientAttrib", "", TclGL_glPopClientAttribCmd } ,
    { "glRenderMode", "<(GLenum) mode>", TclGL_glRenderModeCmd } ,
    { "glGetError", "", TclGL_glGetErrorCmd } ,
    { "glFinish", "", TclGL_glFinishCmd } ,
    { "glFlush", "", TclGL_glFlushCmd } ,
    { "glHint", "<(GLenum) target> <(GLenum) mode>", TclGL_glHintCmd } ,
    { "glClearDepth", "<(GLclampd) depth>", TclGL_glClearDepthCmd } ,
    { "glDepthFunc", "<(GLenum) func>", TclGL_glDepthFuncCmd } ,
    { "glDepthMask", "<(GLboolean) flag>", TclGL_glDepthMaskCmd } ,
    { "glDepthRange", "<(GLclampd) near_val> <(GLclampd) far_val>", TclGL_glDepthRangeCmd } ,
    { "glClearAccum", "<(GLfloat) red> <(GLfloat) green> <(GLfloat) blue> <(GLfloat) alpha>", TclGL_glClearAccumCmd } ,
    { "glAccum", "<(GLenum) op> <(GLfloat) value>", TclGL_glAccumCmd } ,
    { "glMatrixMode", "<(GLenum) mode>", TclGL_glMatrixModeCmd } ,
    { "glOrtho", "<(GLdouble) left> <(GLdouble) right> <(GLdouble) bottom> <(GLdouble) top> <(GLdouble) near_val> <(GLdouble) far_val>", TclGL_glOrthoCmd } ,
    { "glFrustum", "<(GLdouble) left> <(GLdouble) right> <(GLdouble) bottom> <(GLdouble) top> <(GLdouble) near_val> <(GLdouble) far_val>", TclGL_glFrustumCmd } ,
    { "glViewport", "<(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height>", TclGL_glViewportCmd } ,
    { "glPushMatrix", "", TclGL_glPushMatrixCmd } ,
    { "glPopMatrix", "", TclGL_glPopMatrixCmd } ,
    { "glLoadIdentity", "", TclGL_glLoadIdentityCmd } ,
    { "glLoadMatrixd", "<(GLdouble) m>", TclGL_glLoadMatrixdCmd } ,
    { "glLoadMatrixf", "<(GLfloat) m>", TclGL_glLoadMatrixfCmd } ,
    { "glMultMatrixd", "<(GLdouble) m>", TclGL_glMultMatrixdCmd } ,
    { "glMultMatrixf", "<(GLfloat) m>", TclGL_glMultMatrixfCmd } ,
    { "glRotated", "<(GLdouble) angle> <(GLdouble) x> <(GLdouble) y> <(GLdouble) z>", TclGL_glRotatedCmd } ,
    { "glRotatef", "<(GLfloat) angle> <(GLfloat) x> <(GLfloat) y> <(GLfloat) z>", TclGL_glRotatefCmd } ,
    { "glScaled", "<(GLdouble) x> <(GLdouble) y> <(GLdouble) z>", TclGL_glScaledCmd } ,
    { "glScalef", "<(GLfloat) x> <(GLfloat) y> <(GLfloat) z>", TclGL_glScalefCmd } ,
    { "glTranslated", "<(GLdouble) x> <(GLdouble) y> <(GLdouble) z>", TclGL_glTranslatedCmd } ,
    { "glTranslatef", "<(GLfloat) x> <(GLfloat) y> <(GLfloat) z>", TclGL_glTranslatefCmd } ,
    { "glIsList", "<(GLuint) list>", TclGL_glIsListCmd } ,
    { "glDeleteLists", "<(GLuint) list> <(GLsizei) range>", TclGL_glDeleteListsCmd } ,
    { "glGenLists", "<(GLsizei) range>", TclGL_glGenListsCmd } ,
    { "glNewList", "<(GLuint) list> <(GLenum) mode>", TclGL_glNewListCmd } ,
    { "glEndList", "", TclGL_glEndListCmd } ,
    { "glCallList", "<(GLuint) list>", TclGL_glCallListCmd } ,
    { "glCallLists", "<(GLsizei) n> <(GLenum) type> <(GLvoid) lists>", TclGL_glCallListsCmd } ,
    { "glListBase", "<(GLuint) base>", TclGL_glListBaseCmd } ,
    { "glBegin", "<(GLenum) mode>", TclGL_glBeginCmd } ,
    { "glEnd", "", TclGL_glEndCmd } ,
    { "glVertex2d", "<(GLdouble) x> <(GLdouble) y>", TclGL_glVertex2dCmd } ,
    { "glVertex2f", "<(GLfloat) x> <(GLfloat) y>", TclGL_glVertex2fCmd } ,
    { "glVertex2i", "<(GLint) x> <(GLint) y>", TclGL_glVertex2iCmd } ,
    { "glVertex2s", "<(GLshort) x> <(GLshort) y>", TclGL_glVertex2sCmd } ,
    { "glVertex3d", "<(GLdouble) x> <(GLdouble) y> <(GLdouble) z>", TclGL_glVertex3dCmd } ,
    { "glVertex3f", "<(GLfloat) x> <(GLfloat) y> <(GLfloat) z>", TclGL_glVertex3fCmd } ,
    { "glVertex3i", "<(GLint) x> <(GLint) y> <(GLint) z>", TclGL_glVertex3iCmd } ,
    { "glVertex3s", "<(GLshort) x> <(GLshort) y> <(GLshort) z>", TclGL_glVertex3sCmd } ,
    { "glVertex4d", "<(GLdouble) x> <(GLdouble) y> <(GLdouble) z> <(GLdouble) w>", TclGL_glVertex4dCmd } ,
    { "glVertex4f", "<(GLfloat) x> <(GLfloat) y> <(GLfloat) z> <(GLfloat) w>", TclGL_glVertex4fCmd } ,
    { "glVertex4i", "<(GLint) x> <(GLint) y> <(GLint) z> <(GLint) w>", TclGL_glVertex4iCmd } ,
    { "glVertex4s", "<(GLshort) x> <(GLshort) y> <(GLshort) z> <(GLshort) w>", TclGL_glVertex4sCmd } ,
    { "glVertex2dv", "<(GLdouble) v>", TclGL_glVertex2dvCmd } ,
    { "glVertex2fv", "<(GLfloat) v>", TclGL_glVertex2fvCmd } ,
    { "glVertex2iv", "<(GLint) v>", TclGL_glVertex2ivCmd } ,
    { "glVertex2sv", "<(GLshort) v>", TclGL_glVertex2svCmd } ,
    { "glVertex3dv", "<(GLdouble) v>", TclGL_glVertex3dvCmd } ,
    { "glVertex3fv", "<(GLfloat) v>", TclGL_glVertex3fvCmd } ,
    { "glVertex3iv", "<(GLint) v>", TclGL_glVertex3ivCmd } ,
    { "glVertex3sv", "<(GLshort) v>", TclGL_glVertex3svCmd } ,
    { "glVertex4dv", "<(GLdouble) v>", TclGL_glVertex4dvCmd } ,
    { "glVertex4fv", "<(GLfloat) v>", TclGL_glVertex4fvCmd } ,
    { "glVertex4iv", "<(GLint) v>", TclGL_glVertex4ivCmd } ,
    { "glVertex4sv", "<(GLshort) v>", TclGL_glVertex4svCmd } ,
    { "glNormal3b", "<(GLbyte) nx> <(GLbyte) ny> <(GLbyte) nz>", TclGL_glNormal3bCmd } ,
    { "glNormal3d", "<(GLdouble) nx> <(GLdouble) ny> <(GLdouble) nz>", TclGL_glNormal3dCmd } ,
    { "glNormal3f", "<(GLfloat) nx> <(GLfloat) ny> <(GLfloat) nz>", TclGL_glNormal3fCmd } ,
    { "glNormal3i", "<(GLint) nx> <(GLint) ny> <(GLint) nz>", TclGL_glNormal3iCmd } ,
    { "glNormal3s", "<(GLshort) nx> <(GLshort) ny> <(GLshort) nz>", TclGL_glNormal3sCmd } ,
    { "glNormal3bv", "<(GLbyte) v>", TclGL_glNormal3bvCmd } ,
    { "glNormal3dv", "<(GLdouble) v>", TclGL_glNormal3dvCmd } ,
    { "glNormal3fv", "<(GLfloat) v>", TclGL_glNormal3fvCmd } ,
    { "glNormal3iv", "<(GLint) v>", TclGL_glNormal3ivCmd } ,
    { "glNormal3sv", "<(GLshort) v>", TclGL_glNormal3svCmd } ,
    { "glIndexd", "<(GLdouble) c>", TclGL_glIndexdCmd } ,
    { "glIndexf", "<(GLfloat) c>", TclGL_glIndexfCmd } ,
    { "glIndexi", "<(GLint) c>", TclGL_glIndexiCmd } ,
    { "glIndexs", "<(GLshort) c>", TclGL_glIndexsCmd } ,
    { "glIndexub", "<(GLubyte) c>", TclGL_glIndexubCmd } ,
    { "glIndexdv", "<(GLdouble) c>", TclGL_glIndexdvCmd } ,
    { "glIndexfv", "<(GLfloat) c>", TclGL_glIndexfvCmd } ,
    { "glIndexiv", "<(GLint) c>", TclGL_glIndexivCmd } ,
    { "glIndexsv", "<(GLshort) c>", TclGL_glIndexsvCmd } ,
    { "glIndexubv", "<(GLubyte) c>", TclGL_glIndexubvCmd } ,
    { "glColor3b", "<(GLbyte) red> <(GLbyte) green> <(GLbyte) blue>", TclGL_glColor3bCmd } ,
    { "glColor3d", "<(GLdouble) red> <(GLdouble) green> <(GLdouble) blue>", TclGL_glColor3dCmd } ,
    { "glColor3f", "<(GLfloat) red> <(GLfloat) green> <(GLfloat) blue>", TclGL_glColor3fCmd } ,
    { "glColor3i", "<(GLint) red> <(GLint) green> <(GLint) blue>", TclGL_glColor3iCmd } ,
    { "glColor3s", "<(GLshort) red> <(GLshort) green> <(GLshort) blue>", TclGL_glColor3sCmd } ,
    { "glColor3ub", "<(GLubyte) red> <(GLubyte) green> <(GLubyte) blue>", TclGL_glColor3ubCmd } ,
    { "glColor3ui", "<(GLuint) red> <(GLuint) green> <(GLuint) blue>", TclGL_glColor3uiCmd } ,
    { "glColor3us", "<(GLushort) red> <(GLushort) green> <(GLushort) blue>", TclGL_glColor3usCmd } ,
    { "glColor4b", "<(GLbyte) red> <(GLbyte) green> <(GLbyte) blue> <(GLbyte) alpha>", TclGL_glColor4bCmd } ,
    { "glColor4d", "<(GLdouble) red> <(GLdouble) green> <(GLdouble) blue> <(GLdouble) alpha>", TclGL_glColor4dCmd } ,
    { "glColor4f", "<(GLfloat) red> <(GLfloat) green> <(GLfloat) blue> <(GLfloat) alpha>", TclGL_glColor4fCmd } ,
    { "glColor4i", "<(GLint) red> <(GLint) green> <(GLint) blue> <(GLint) alpha>", TclGL_glColor4iCmd } ,
    { "glColor4s", "<(GLshort) red> <(GLshort) green> <(GLshort) blue> <(GLshort) alpha>", TclGL_glColor4sCmd } ,
    { "glColor4ub", "<(GLubyte) red> <(GLubyte) green> <(GLubyte) blue> <(GLubyte) alpha>", TclGL_glColor4ubCmd } ,
    { "glColor4ui", "<(GLuint) red> <(GLuint) green> <(GLuint) blue> <(GLuint) alpha>", TclGL_glColor4uiCmd } ,
    { "glColor4us", "<(GLushort) red> <(GLushort) green> <(GLushort) blue> <(GLushort) alpha>", TclGL_glColor4usCmd } ,
    { "glColor3bv", "<(GLbyte) v>", TclGL_glColor3bvCmd } ,
    { "glColor3dv", "<(GLdouble) v>", TclGL_glColor3dvCmd } ,
    { "glColor3fv", "<(GLfloat) v>", TclGL_glColor3fvCmd } ,
    { "glColor3iv", "<(GLint) v>", TclGL_glColor3ivCmd } ,
    { "glColor3sv", "<(GLshort) v>", TclGL_glColor3svCmd } ,
    { "glColor3ubv", "<(GLubyte) v>", TclGL_glColor3ubvCmd } ,
    { "glColor3uiv", "<(GLuint) v>", TclGL_glColor3uivCmd } ,
    { "glColor3usv", "<(GLushort) v>", TclGL_glColor3usvCmd } ,
    { "glColor4bv", "<(GLbyte) v>", TclGL_glColor4bvCmd } ,
    { "glColor4dv", "<(GLdouble) v>", TclGL_glColor4dvCmd } ,
    { "glColor4fv", "<(GLfloat) v>", TclGL_glColor4fvCmd } ,
    { "glColor4iv", "<(GLint) v>", TclGL_glColor4ivCmd } ,
    { "glColor4sv", "<(GLshort) v>", TclGL_glColor4svCmd } ,
    { "glColor4ubv", "<(GLubyte) v>", TclGL_glColor4ubvCmd } ,
    { "glColor4uiv", "<(GLuint) v>", TclGL_glColor4uivCmd } ,
    { "glColor4usv", "<(GLushort) v>", TclGL_glColor4usvCmd } ,
    { "glTexCoord1d", "<(GLdouble) s>", TclGL_glTexCoord1dCmd } ,
    { "glTexCoord1f", "<(GLfloat) s>", TclGL_glTexCoord1fCmd } ,
    { "glTexCoord1i", "<(GLint) s>", TclGL_glTexCoord1iCmd } ,
    { "glTexCoord1s", "<(GLshort) s>", TclGL_glTexCoord1sCmd } ,
    { "glTexCoord2d", "<(GLdouble) s> <(GLdouble) t>", TclGL_glTexCoord2dCmd } ,
    { "glTexCoord2f", "<(GLfloat) s> <(GLfloat) t>", TclGL_glTexCoord2fCmd } ,
    { "glTexCoord2i", "<(GLint) s> <(GLint) t>", TclGL_glTexCoord2iCmd } ,
    { "glTexCoord2s", "<(GLshort) s> <(GLshort) t>", TclGL_glTexCoord2sCmd } ,
    { "glTexCoord3d", "<(GLdouble) s> <(GLdouble) t> <(GLdouble) r>", TclGL_glTexCoord3dCmd } ,
    { "glTexCoord3f", "<(GLfloat) s> <(GLfloat) t> <(GLfloat) r>", TclGL_glTexCoord3fCmd } ,
    { "glTexCoord3i", "<(GLint) s> <(GLint) t> <(GLint) r>", TclGL_glTexCoord3iCmd } ,
    { "glTexCoord3s", "<(GLshort) s> <(GLshort) t> <(GLshort) r>", TclGL_glTexCoord3sCmd } ,
    { "glTexCoord4d", "<(GLdouble) s> <(GLdouble) t> <(GLdouble) r> <(GLdouble) q>", TclGL_glTexCoord4dCmd } ,
    { "glTexCoord4f", "<(GLfloat) s> <(GLfloat) t> <(GLfloat) r> <(GLfloat) q>", TclGL_glTexCoord4fCmd } ,
    { "glTexCoord4i", "<(GLint) s> <(GLint) t> <(GLint) r> <(GLint) q>", TclGL_glTexCoord4iCmd } ,
    { "glTexCoord4s", "<(GLshort) s> <(GLshort) t> <(GLshort) r> <(GLshort) q>", TclGL_glTexCoord4sCmd } ,
    { "glTexCoord1dv", "<(GLdouble) v>", TclGL_glTexCoord1dvCmd } ,
    { "glTexCoord1fv", "<(GLfloat) v>", TclGL_glTexCoord1fvCmd } ,
    { "glTexCoord1iv", "<(GLint) v>", TclGL_glTexCoord1ivCmd } ,
    { "glTexCoord1sv", "<(GLshort) v>", TclGL_glTexCoord1svCmd } ,
    { "glTexCoord2dv", "<(GLdouble) v>", TclGL_glTexCoord2dvCmd } ,
    { "glTexCoord2fv", "<(GLfloat) v>", TclGL_glTexCoord2fvCmd } ,
    { "glTexCoord2iv", "<(GLint) v>", TclGL_glTexCoord2ivCmd } ,
    { "glTexCoord2sv", "<(GLshort) v>", TclGL_glTexCoord2svCmd } ,
    { "glTexCoord3dv", "<(GLdouble) v>", TclGL_glTexCoord3dvCmd } ,
    { "glTexCoord3fv", "<(GLfloat) v>", TclGL_glTexCoord3fvCmd } ,
    { "glTexCoord3iv", "<(GLint) v>", TclGL_glTexCoord3ivCmd } ,
    { "glTexCoord3sv", "<(GLshort) v>", TclGL_glTexCoord3svCmd } ,
    { "glTexCoord4dv", "<(GLdouble) v>", TclGL_glTexCoord4dvCmd } ,
    { "glTexCoord4fv", "<(GLfloat) v>", TclGL_glTexCoord4fvCmd } ,
    { "glTexCoord4iv", "<(GLint) v>", TclGL_glTexCoord4ivCmd } ,
    { "glTexCoord4sv", "<(GLshort) v>", TclGL_glTexCoord4svCmd } ,
    { "glRasterPos2d", "<(GLdouble) x> <(GLdouble) y>", TclGL_glRasterPos2dCmd } ,
    { "glRasterPos2f", "<(GLfloat) x> <(GLfloat) y>", TclGL_glRasterPos2fCmd } ,
    { "glRasterPos2i", "<(GLint) x> <(GLint) y>", TclGL_glRasterPos2iCmd } ,
    { "glRasterPos2s", "<(GLshort) x> <(GLshort) y>", TclGL_glRasterPos2sCmd } ,
    { "glRasterPos3d", "<(GLdouble) x> <(GLdouble) y> <(GLdouble) z>", TclGL_glRasterPos3dCmd } ,
    { "glRasterPos3f", "<(GLfloat) x> <(GLfloat) y> <(GLfloat) z>", TclGL_glRasterPos3fCmd } ,
    { "glRasterPos3i", "<(GLint) x> <(GLint) y> <(GLint) z>", TclGL_glRasterPos3iCmd } ,
    { "glRasterPos3s", "<(GLshort) x> <(GLshort) y> <(GLshort) z>", TclGL_glRasterPos3sCmd } ,
    { "glRasterPos4d", "<(GLdouble) x> <(GLdouble) y> <(GLdouble) z> <(GLdouble) w>", TclGL_glRasterPos4dCmd } ,
    { "glRasterPos4f", "<(GLfloat) x> <(GLfloat) y> <(GLfloat) z> <(GLfloat) w>", TclGL_glRasterPos4fCmd } ,
    { "glRasterPos4i", "<(GLint) x> <(GLint) y> <(GLint) z> <(GLint) w>", TclGL_glRasterPos4iCmd } ,
    { "glRasterPos4s", "<(GLshort) x> <(GLshort) y> <(GLshort) z> <(GLshort) w>", TclGL_glRasterPos4sCmd } ,
    { "glRasterPos2dv", "<(GLdouble) v>", TclGL_glRasterPos2dvCmd } ,
    { "glRasterPos2fv", "<(GLfloat) v>", TclGL_glRasterPos2fvCmd } ,
    { "glRasterPos2iv", "<(GLint) v>", TclGL_glRasterPos2ivCmd } ,
    { "glRasterPos2sv", "<(GLshort) v>", TclGL_glRasterPos2svCmd } ,
    { "glRasterPos3dv", "<(GLdouble) v>", TclGL_glRasterPos3dvCmd } ,
    { "glRasterPos3fv", "<(GLfloat) v>", TclGL_glRasterPos3fvCmd } ,
    { "glRasterPos3iv", "<(GLint) v>", TclGL_glRasterPos3ivCmd } ,
    { "glRasterPos3sv", "<(GLshort) v>", TclGL_glRasterPos3svCmd } ,
    { "glRasterPos4dv", "<(GLdouble) v>", TclGL_glRasterPos4dvCmd } ,
    { "glRasterPos4fv", "<(GLfloat) v>", TclGL_glRasterPos4fvCmd } ,
    { "glRasterPos4iv", "<(GLint) v>", TclGL_glRasterPos4ivCmd } ,
    { "glRasterPos4sv", "<(GLshort) v>", TclGL_glRasterPos4svCmd } ,
    { "glRectd", "<(GLdouble) x1> <(GLdouble) y1> <(GLdouble) x2> <(GLdouble) y2>", TclGL_glRectdCmd } ,
    { "glRectf", "<(GLfloat) x1> <(GLfloat) y1> <(GLfloat) x2> <(GLfloat) y2>", TclGL_glRectfCmd } ,
    { "glRecti", "<(GLint) x1> <(GLint) y1> <(GLint) x2> <(GLint) y2>", TclGL_glRectiCmd } ,
    { "glRects", "<(GLshort) x1> <(GLshort) y1> <(GLshort) x2> <(GLshort) y2>", TclGL_glRectsCmd } ,
    { "glRectdv", "<(GLdouble) v1> <(GLdouble) v2>", TclGL_glRectdvCmd } ,
    { "glRectfv", "<(GLfloat) v1> <(GLfloat) v2>", TclGL_glRectfvCmd } ,
    { "glRectiv", "<(GLint) v1> <(GLint) v2>", TclGL_glRectivCmd } ,
    { "glRectsv", "<(GLshort) v1> <(GLshort) v2>", TclGL_glRectsvCmd } ,
    { "glVertexPointer", "<(GLint) size> <(GLenum) type> <(GLsizei) stride> <(GLvoid) ptr>", TclGL_glVertexPointerCmd } ,
    { "glNormalPointer", "<(GLenum) type> <(GLsizei) stride> <(GLvoid) ptr>", TclGL_glNormalPointerCmd } ,
    { "glColorPointer", "<(GLint) size> <(GLenum) type> <(GLsizei) stride> <(GLvoid) ptr>", TclGL_glColorPointerCmd } ,
    { "glIndexPointer", "<(GLenum) type> <(GLsizei) stride> <(GLvoid) ptr>", TclGL_glIndexPointerCmd } ,
    { "glTexCoordPointer", "<(GLint) size> <(GLenum) type> <(GLsizei) stride> <(GLvoid) ptr>", TclGL_glTexCoordPointerCmd } ,
    { "glEdgeFlagPointer", "<(GLsizei) stride> <(GLvoid) ptr>", TclGL_glEdgeFlagPointerCmd } ,
    { "glGetPointerv", "<(GLenum) pname> <(GLvoid) params>", TclGL_glGetPointervCmd } ,
    { "glArrayElement", "<(GLint) i>", TclGL_glArrayElementCmd } ,
    { "glDrawArrays", "<(GLenum) mode> <(GLint) first> <(GLsizei) count>", TclGL_glDrawArraysCmd } ,
    { "glDrawElements", "<(GLenum) mode> <(GLsizei) count> <(GLenum) type> <(GLvoid) indices>", TclGL_glDrawElementsCmd } ,
    { "glInterleavedArrays", "<(GLenum) format> <(GLsizei) stride> <(GLvoid) pointer>", TclGL_glInterleavedArraysCmd } ,
    { "glShadeModel", "<(GLenum) mode>", TclGL_glShadeModelCmd } ,
    { "glLightf", "<(GLenum) light> <(GLenum) pname> <(GLfloat) param>", TclGL_glLightfCmd } ,
    { "glLighti", "<(GLenum) light> <(GLenum) pname> <(GLint) param>", TclGL_glLightiCmd } ,
    { "glLightfv", "<(GLenum) light> <(GLenum) pname> <(GLfloat) params>", TclGL_glLightfvCmd } ,
    { "glLightiv", "<(GLenum) light> <(GLenum) pname> <(GLint) params>", TclGL_glLightivCmd } ,
    { "glGetLightfv", "<(GLenum) light> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetLightfvCmd } ,
    { "glGetLightiv", "<(GLenum) light> <(GLenum) pname> <(GLint) params>", TclGL_glGetLightivCmd } ,
    { "glLightModelf", "<(GLenum) pname> <(GLfloat) param>", TclGL_glLightModelfCmd } ,
    { "glLightModeli", "<(GLenum) pname> <(GLint) param>", TclGL_glLightModeliCmd } ,
    { "glLightModelfv", "<(GLenum) pname> <(GLfloat) params>", TclGL_glLightModelfvCmd } ,
    { "glLightModeliv", "<(GLenum) pname> <(GLint) params>", TclGL_glLightModelivCmd } ,
    { "glMaterialf", "<(GLenum) face> <(GLenum) pname> <(GLfloat) param>", TclGL_glMaterialfCmd } ,
    { "glMateriali", "<(GLenum) face> <(GLenum) pname> <(GLint) param>", TclGL_glMaterialiCmd } ,
    { "glMaterialfv", "<(GLenum) face> <(GLenum) pname> <(GLfloat) params>", TclGL_glMaterialfvCmd } ,
    { "glMaterialiv", "<(GLenum) face> <(GLenum) pname> <(GLint) params>", TclGL_glMaterialivCmd } ,
    { "glGetMaterialfv", "<(GLenum) face> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetMaterialfvCmd } ,
    { "glGetMaterialiv", "<(GLenum) face> <(GLenum) pname> <(GLint) params>", TclGL_glGetMaterialivCmd } ,
    { "glColorMaterial", "<(GLenum) face> <(GLenum) mode>", TclGL_glColorMaterialCmd } ,
    { "glPixelZoom", "<(GLfloat) xfactor> <(GLfloat) yfactor>", TclGL_glPixelZoomCmd } ,
    { "glPixelStoref", "<(GLenum) pname> <(GLfloat) param>", TclGL_glPixelStorefCmd } ,
    { "glPixelStorei", "<(GLenum) pname> <(GLint) param>", TclGL_glPixelStoreiCmd } ,
    { "glPixelTransferf", "<(GLenum) pname> <(GLfloat) param>", TclGL_glPixelTransferfCmd } ,
    { "glPixelTransferi", "<(GLenum) pname> <(GLint) param>", TclGL_glPixelTransferiCmd } ,
    { "glPixelMapfv", "<(GLenum) map> <(GLsizei) mapsize> <(GLfloat) values>", TclGL_glPixelMapfvCmd } ,
    { "glPixelMapuiv", "<(GLenum) map> <(GLsizei) mapsize> <(GLuint) values>", TclGL_glPixelMapuivCmd } ,
    { "glPixelMapusv", "<(GLenum) map> <(GLsizei) mapsize> <(GLushort) values>", TclGL_glPixelMapusvCmd } ,
    { "glGetPixelMapfv", "<(GLenum) map> <(GLfloat) values>", TclGL_glGetPixelMapfvCmd } ,
    { "glGetPixelMapuiv", "<(GLenum) map> <(GLuint) values>", TclGL_glGetPixelMapuivCmd } ,
    { "glGetPixelMapusv", "<(GLenum) map> <(GLushort) values>", TclGL_glGetPixelMapusvCmd } ,
    { "glBitmap", "<(GLsizei) width> <(GLsizei) height> <(GLfloat) xorig> <(GLfloat) yorig> <(GLfloat) xmove> <(GLfloat) ymove> <(GLubyte) bitmap>", TclGL_glBitmapCmd } ,
    { "glReadPixels", "<(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glReadPixelsCmd } ,
    { "glDrawPixels", "<(GLsizei) width> <(GLsizei) height> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glDrawPixelsCmd } ,
    { "glCopyPixels", "<(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height> <(GLenum) type>", TclGL_glCopyPixelsCmd } ,
    { "glStencilFunc", "<(GLenum) func> <(GLint) ref> <(GLuint) mask>", TclGL_glStencilFuncCmd } ,
    { "glStencilMask", "<(GLuint) mask>", TclGL_glStencilMaskCmd } ,
    { "glStencilOp", "<(GLenum) fail> <(GLenum) zfail> <(GLenum) zpass>", TclGL_glStencilOpCmd } ,
    { "glClearStencil", "<(GLint) s>", TclGL_glClearStencilCmd } ,
    { "glTexGend", "<(GLenum) coord> <(GLenum) pname> <(GLdouble) param>", TclGL_glTexGendCmd } ,
    { "glTexGenf", "<(GLenum) coord> <(GLenum) pname> <(GLfloat) param>", TclGL_glTexGenfCmd } ,
    { "glTexGeni", "<(GLenum) coord> <(GLenum) pname> <(GLint) param>", TclGL_glTexGeniCmd } ,
    { "glTexGendv", "<(GLenum) coord> <(GLenum) pname> <(GLdouble) params>", TclGL_glTexGendvCmd } ,
    { "glTexGenfv", "<(GLenum) coord> <(GLenum) pname> <(GLfloat) params>", TclGL_glTexGenfvCmd } ,
    { "glTexGeniv", "<(GLenum) coord> <(GLenum) pname> <(GLint) params>", TclGL_glTexGenivCmd } ,
    { "glGetTexGendv", "<(GLenum) coord> <(GLenum) pname> <(GLdouble) params>", TclGL_glGetTexGendvCmd } ,
    { "glGetTexGenfv", "<(GLenum) coord> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetTexGenfvCmd } ,
    { "glGetTexGeniv", "<(GLenum) coord> <(GLenum) pname> <(GLint) params>", TclGL_glGetTexGenivCmd } ,
    { "glTexEnvf", "<(GLenum) target> <(GLenum) pname> <(GLfloat) param>", TclGL_glTexEnvfCmd } ,
    { "glTexEnvi", "<(GLenum) target> <(GLenum) pname> <(GLint) param>", TclGL_glTexEnviCmd } ,
    { "glTexEnvfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glTexEnvfvCmd } ,
    { "glTexEnviv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glTexEnvivCmd } ,
    { "glGetTexEnvfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetTexEnvfvCmd } ,
    { "glGetTexEnviv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glGetTexEnvivCmd } ,
    { "glTexParameterf", "<(GLenum) target> <(GLenum) pname> <(GLfloat) param>", TclGL_glTexParameterfCmd } ,
    { "glTexParameteri", "<(GLenum) target> <(GLenum) pname> <(GLint) param>", TclGL_glTexParameteriCmd } ,
    { "glTexParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glTexParameterfvCmd } ,
    { "glTexParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glTexParameterivCmd } ,
    { "glGetTexParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetTexParameterfvCmd } ,
    { "glGetTexParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glGetTexParameterivCmd } ,
    { "glGetTexLevelParameterfv", "<(GLenum) target> <(GLint) level> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetTexLevelParameterfvCmd } ,
    { "glGetTexLevelParameteriv", "<(GLenum) target> <(GLint) level> <(GLenum) pname> <(GLint) params>", TclGL_glGetTexLevelParameterivCmd } ,
    { "glTexImage1D", "<(GLenum) target> <(GLint) level> <(GLint) internalFormat> <(GLsizei) width> <(GLint) border> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glTexImage1DCmd } ,
    { "glTexImage2D", "<(GLenum) target> <(GLint) level> <(GLint) internalFormat> <(GLsizei) width> <(GLsizei) height> <(GLint) border> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glTexImage2DCmd } ,
    { "glGetTexImage", "<(GLenum) target> <(GLint) level> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glGetTexImageCmd } ,
    { "glGenTextures", "<(GLsizei) n> <(GLuint) textures>", TclGL_glGenTexturesCmd } ,
    { "glDeleteTextures", "<(GLsizei) n> <(GLuint) textures>", TclGL_glDeleteTexturesCmd } ,
    { "glBindTexture", "<(GLenum) target> <(GLuint) texture>", TclGL_glBindTextureCmd } ,
    { "glPrioritizeTextures", "<(GLsizei) n> <(GLuint) textures> <(GLclampf) priorities>", TclGL_glPrioritizeTexturesCmd } ,
    { "glIsTexture", "<(GLuint) texture>", TclGL_glIsTextureCmd } ,
    { "glTexSubImage1D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLsizei) width> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glTexSubImage1DCmd } ,
    { "glTexSubImage2D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLint) yoffset> <(GLsizei) width> <(GLsizei) height> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glTexSubImage2DCmd } ,
    { "glCopyTexImage1D", "<(GLenum) target> <(GLint) level> <(GLenum) internalformat> <(GLint) x> <(GLint) y> <(GLsizei) width> <(GLint) border>", TclGL_glCopyTexImage1DCmd } ,
    { "glCopyTexImage2D", "<(GLenum) target> <(GLint) level> <(GLenum) internalformat> <(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height> <(GLint) border>", TclGL_glCopyTexImage2DCmd } ,
    { "glCopyTexSubImage1D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLint) x> <(GLint) y> <(GLsizei) width>", TclGL_glCopyTexSubImage1DCmd } ,
    { "glCopyTexSubImage2D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLint) yoffset> <(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height>", TclGL_glCopyTexSubImage2DCmd } ,
    { "glMap1d", "<(GLenum) target> <(GLdouble) u1> <(GLdouble) u2> <(GLint) stride> <(GLint) order> <(GLdouble) points>", TclGL_glMap1dCmd } ,
    { "glMap1f", "<(GLenum) target> <(GLfloat) u1> <(GLfloat) u2> <(GLint) stride> <(GLint) order> <(GLfloat) points>", TclGL_glMap1fCmd } ,
    { "glMap2d", "<(GLenum) target> <(GLdouble) u1> <(GLdouble) u2> <(GLint) ustride> <(GLint) uorder> <(GLdouble) v1> <(GLdouble) v2> <(GLint) vstride> <(GLint) vorder> <(GLdouble) points>", TclGL_glMap2dCmd } ,
    { "glMap2f", "<(GLenum) target> <(GLfloat) u1> <(GLfloat) u2> <(GLint) ustride> <(GLint) uorder> <(GLfloat) v1> <(GLfloat) v2> <(GLint) vstride> <(GLint) vorder> <(GLfloat) points>", TclGL_glMap2fCmd } ,
    { "glGetMapdv", "<(GLenum) target> <(GLenum) query> <(GLdouble) v>", TclGL_glGetMapdvCmd } ,
    { "glGetMapfv", "<(GLenum) target> <(GLenum) query> <(GLfloat) v>", TclGL_glGetMapfvCmd } ,
    { "glGetMapiv", "<(GLenum) target> <(GLenum) query> <(GLint) v>", TclGL_glGetMapivCmd } ,
    { "glEvalCoord1d", "<(GLdouble) u>", TclGL_glEvalCoord1dCmd } ,
    { "glEvalCoord1f", "<(GLfloat) u>", TclGL_glEvalCoord1fCmd } ,
    { "glEvalCoord1dv", "<(GLdouble) u>", TclGL_glEvalCoord1dvCmd } ,
    { "glEvalCoord1fv", "<(GLfloat) u>", TclGL_glEvalCoord1fvCmd } ,
    { "glEvalCoord2d", "<(GLdouble) u> <(GLdouble) v>", TclGL_glEvalCoord2dCmd } ,
    { "glEvalCoord2f", "<(GLfloat) u> <(GLfloat) v>", TclGL_glEvalCoord2fCmd } ,
    { "glEvalCoord2dv", "<(GLdouble) u>", TclGL_glEvalCoord2dvCmd } ,
    { "glEvalCoord2fv", "<(GLfloat) u>", TclGL_glEvalCoord2fvCmd } ,
    { "glMapGrid1d", "<(GLint) un> <(GLdouble) u1> <(GLdouble) u2>", TclGL_glMapGrid1dCmd } ,
    { "glMapGrid1f", "<(GLint) un> <(GLfloat) u1> <(GLfloat) u2>", TclGL_glMapGrid1fCmd } ,
    { "glMapGrid2d", "<(GLint) un> <(GLdouble) u1> <(GLdouble) u2> <(GLint) vn> <(GLdouble) v1> <(GLdouble) v2>", TclGL_glMapGrid2dCmd } ,
    { "glMapGrid2f", "<(GLint) un> <(GLfloat) u1> <(GLfloat) u2> <(GLint) vn> <(GLfloat) v1> <(GLfloat) v2>", TclGL_glMapGrid2fCmd } ,
    { "glEvalPoint1", "<(GLint) i>", TclGL_glEvalPoint1Cmd } ,
    { "glEvalPoint2", "<(GLint) i> <(GLint) j>", TclGL_glEvalPoint2Cmd } ,
    { "glEvalMesh1", "<(GLenum) mode> <(GLint) i1> <(GLint) i2>", TclGL_glEvalMesh1Cmd } ,
    { "glEvalMesh2", "<(GLenum) mode> <(GLint) i1> <(GLint) i2> <(GLint) j1> <(GLint) j2>", TclGL_glEvalMesh2Cmd } ,
    { "glFogf", "<(GLenum) pname> <(GLfloat) param>", TclGL_glFogfCmd } ,
    { "glFogi", "<(GLenum) pname> <(GLint) param>", TclGL_glFogiCmd } ,
    { "glFogfv", "<(GLenum) pname> <(GLfloat) params>", TclGL_glFogfvCmd } ,
    { "glFogiv", "<(GLenum) pname> <(GLint) params>", TclGL_glFogivCmd } ,
    { "glFeedbackBuffer", "<(GLsizei) size> <(GLenum) type> <(GLfloat) buffer>", TclGL_glFeedbackBufferCmd } ,
    { "glPassThrough", "<(GLfloat) token>", TclGL_glPassThroughCmd } ,
    { "glSelectBuffer", "<(GLsizei) size> <(GLuint) buffer>", TclGL_glSelectBufferCmd } ,
    { "glInitNames", "", TclGL_glInitNamesCmd } ,
    { "glLoadName", "<(GLuint) name>", TclGL_glLoadNameCmd } ,
    { "glPushName", "<(GLuint) name>", TclGL_glPushNameCmd } ,
    { "glPopName", "", TclGL_glPopNameCmd } ,
    { "glDrawRangeElements", "<(GLenum) mode> <(GLuint) start> <(GLuint) end> <(GLsizei) count> <(GLenum) type> <(GLvoid) indices>", TclGL_glDrawRangeElementsCmd } ,
    { "glTexImage3D", "<(GLenum) target> <(GLint) level> <(GLint) internalFormat> <(GLsizei) width> <(GLsizei) height> <(GLsizei) depth> <(GLint) border> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glTexImage3DCmd } ,
    { "glTexSubImage3D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLint) yoffset> <(GLint) zoffset> <(GLsizei) width> <(GLsizei) height> <(GLsizei) depth> <(GLenum) format> <(GLenum) type> <(GLvoid) pixels>", TclGL_glTexSubImage3DCmd } ,
    { "glCopyTexSubImage3D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLint) yoffset> <(GLint) zoffset> <(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height>", TclGL_glCopyTexSubImage3DCmd } ,
    { "glColorTable", "<(GLenum) target> <(GLenum) internalformat> <(GLsizei) width> <(GLenum) format> <(GLenum) type> <(GLvoid) table>", TclGL_glColorTableCmd } ,
    { "glColorSubTable", "<(GLenum) target> <(GLsizei) start> <(GLsizei) count> <(GLenum) format> <(GLenum) type> <(GLvoid) data>", TclGL_glColorSubTableCmd } ,
    { "glColorTableParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glColorTableParameterivCmd } ,
    { "glColorTableParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glColorTableParameterfvCmd } ,
    { "glCopyColorSubTable", "<(GLenum) target> <(GLsizei) start> <(GLint) x> <(GLint) y> <(GLsizei) width>", TclGL_glCopyColorSubTableCmd } ,
    { "glCopyColorTable", "<(GLenum) target> <(GLenum) internalformat> <(GLint) x> <(GLint) y> <(GLsizei) width>", TclGL_glCopyColorTableCmd } ,
    { "glGetColorTable", "<(GLenum) target> <(GLenum) format> <(GLenum) type> <(GLvoid) table>", TclGL_glGetColorTableCmd } ,
    { "glGetColorTableParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetColorTableParameterfvCmd } ,
    { "glGetColorTableParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glGetColorTableParameterivCmd } ,
    { "glBlendEquation", "<(GLenum) mode>", TclGL_glBlendEquationCmd } ,
    { "glBlendColor", "<(GLclampf) red> <(GLclampf) green> <(GLclampf) blue> <(GLclampf) alpha>", TclGL_glBlendColorCmd } ,
    { "glHistogram", "<(GLenum) target> <(GLsizei) width> <(GLenum) internalformat> <(GLboolean) sink>", TclGL_glHistogramCmd } ,
    { "glResetHistogram", "<(GLenum) target>", TclGL_glResetHistogramCmd } ,
    { "glGetHistogram", "<(GLenum) target> <(GLboolean) reset> <(GLenum) format> <(GLenum) type> <(GLvoid) values>", TclGL_glGetHistogramCmd } ,
    { "glGetHistogramParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetHistogramParameterfvCmd } ,
    { "glGetHistogramParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glGetHistogramParameterivCmd } ,
    { "glMinmax", "<(GLenum) target> <(GLenum) internalformat> <(GLboolean) sink>", TclGL_glMinmaxCmd } ,
    { "glResetMinmax", "<(GLenum) target>", TclGL_glResetMinmaxCmd } ,
    { "glGetMinmax", "<(GLenum) target> <(GLboolean) reset> <(GLenum) format> <(GLenum) types> <(GLvoid) values>", TclGL_glGetMinmaxCmd } ,
    { "glGetMinmaxParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetMinmaxParameterfvCmd } ,
    { "glGetMinmaxParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glGetMinmaxParameterivCmd } ,
    { "glConvolutionFilter1D", "<(GLenum) target> <(GLenum) internalformat> <(GLsizei) width> <(GLenum) format> <(GLenum) type> <(GLvoid) image>", TclGL_glConvolutionFilter1DCmd } ,
    { "glConvolutionFilter2D", "<(GLenum) target> <(GLenum) internalformat> <(GLsizei) width> <(GLsizei) height> <(GLenum) format> <(GLenum) type> <(GLvoid) image>", TclGL_glConvolutionFilter2DCmd } ,
    { "glConvolutionParameterf", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glConvolutionParameterfCmd } ,
    { "glConvolutionParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glConvolutionParameterfvCmd } ,
    { "glConvolutionParameteri", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glConvolutionParameteriCmd } ,
    { "glConvolutionParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glConvolutionParameterivCmd } ,
    { "glCopyConvolutionFilter1D", "<(GLenum) target> <(GLenum) internalformat> <(GLint) x> <(GLint) y> <(GLsizei) width>", TclGL_glCopyConvolutionFilter1DCmd } ,
    { "glCopyConvolutionFilter2D", "<(GLenum) target> <(GLenum) internalformat> <(GLint) x> <(GLint) y> <(GLsizei) width> <(GLsizei) height>", TclGL_glCopyConvolutionFilter2DCmd } ,
    { "glGetConvolutionFilter", "<(GLenum) target> <(GLenum) format> <(GLenum) type> <(GLvoid) image>", TclGL_glGetConvolutionFilterCmd } ,
    { "glGetConvolutionParameterfv", "<(GLenum) target> <(GLenum) pname> <(GLfloat) params>", TclGL_glGetConvolutionParameterfvCmd } ,
    { "glGetConvolutionParameteriv", "<(GLenum) target> <(GLenum) pname> <(GLint) params>", TclGL_glGetConvolutionParameterivCmd } ,
    { "glSeparableFilter2D", "<(GLenum) target> <(GLenum) internalformat> <(GLsizei) width> <(GLsizei) height> <(GLenum) format> <(GLenum) type> <(GLvoid) row> <(GLvoid) column>", TclGL_glSeparableFilter2DCmd } ,
    { "glGetSeparableFilter", "<(GLenum) target> <(GLenum) format> <(GLenum) type> <(GLvoid) row> <(GLvoid) column> <(GLvoid) span>", TclGL_glGetSeparableFilterCmd } ,
    { "glActiveTexture", "<(GLenum) texture>", TclGL_glActiveTextureCmd } ,
    { "glClientActiveTexture", "<(GLenum) texture>", TclGL_glClientActiveTextureCmd } ,
    { "glCompressedTexImage1D", "<(GLenum) target> <(GLint) level> <(GLenum) internalformat> <(GLsizei) width> <(GLint) border> <(GLsizei) imageSize> <(GLvoid) data>", TclGL_glCompressedTexImage1DCmd } ,
    { "glCompressedTexImage2D", "<(GLenum) target> <(GLint) level> <(GLenum) internalformat> <(GLsizei) width> <(GLsizei) height> <(GLint) border> <(GLsizei) imageSize> <(GLvoid) data>", TclGL_glCompressedTexImage2DCmd } ,
    { "glCompressedTexImage3D", "<(GLenum) target> <(GLint) level> <(GLenum) internalformat> <(GLsizei) width> <(GLsizei) height> <(GLsizei) depth> <(GLint) border> <(GLsizei) imageSize> <(GLvoid) data>", TclGL_glCompressedTexImage3DCmd } ,
    { "glCompressedTexSubImage1D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLsizei) width> <(GLenum) format> <(GLsizei) imageSize> <(GLvoid) data>", TclGL_glCompressedTexSubImage1DCmd } ,
    { "glCompressedTexSubImage2D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLint) yoffset> <(GLsizei) width> <(GLsizei) height> <(GLenum) format> <(GLsizei) imageSize> <(GLvoid) data>", TclGL_glCompressedTexSubImage2DCmd } ,
    { "glCompressedTexSubImage3D", "<(GLenum) target> <(GLint) level> <(GLint) xoffset> <(GLint) yoffset> <(GLint) zoffset> <(GLsizei) width> <(GLsizei) height> <(GLsizei) depth> <(GLenum) format> <(GLsizei) imageSize> <(GLvoid) data>", TclGL_glCompressedTexSubImage3DCmd } ,
    { "glGetCompressedTexImage", "<(GLenum) target> <(GLint) lod> <(GLvoid) img>", TclGL_glGetCompressedTexImageCmd } ,
    { "glMultiTexCoord1d", "<(GLenum) target> <(GLdouble) s>", TclGL_glMultiTexCoord1dCmd } ,
    { "glMultiTexCoord1dv", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord1dvCmd } ,
    { "glMultiTexCoord1f", "<(GLenum) target> <(GLfloat) s>", TclGL_glMultiTexCoord1fCmd } ,
    { "glMultiTexCoord1fv", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord1fvCmd } ,
    { "glMultiTexCoord1i", "<(GLenum) target> <(GLint) s>", TclGL_glMultiTexCoord1iCmd } ,
    { "glMultiTexCoord1iv", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord1ivCmd } ,
    { "glMultiTexCoord1s", "<(GLenum) target> <(GLshort) s>", TclGL_glMultiTexCoord1sCmd } ,
    { "glMultiTexCoord1sv", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord1svCmd } ,
    { "glMultiTexCoord2d", "<(GLenum) target> <(GLdouble) s> <(GLdouble) t>", TclGL_glMultiTexCoord2dCmd } ,
    { "glMultiTexCoord2dv", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord2dvCmd } ,
    { "glMultiTexCoord2f", "<(GLenum) target> <(GLfloat) s> <(GLfloat) t>", TclGL_glMultiTexCoord2fCmd } ,
    { "glMultiTexCoord2fv", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord2fvCmd } ,
    { "glMultiTexCoord2i", "<(GLenum) target> <(GLint) s> <(GLint) t>", TclGL_glMultiTexCoord2iCmd } ,
    { "glMultiTexCoord2iv", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord2ivCmd } ,
    { "glMultiTexCoord2s", "<(GLenum) target> <(GLshort) s> <(GLshort) t>", TclGL_glMultiTexCoord2sCmd } ,
    { "glMultiTexCoord2sv", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord2svCmd } ,
    { "glMultiTexCoord3d", "<(GLenum) target> <(GLdouble) s> <(GLdouble) t> <(GLdouble) r>", TclGL_glMultiTexCoord3dCmd } ,
    { "glMultiTexCoord3dv", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord3dvCmd } ,
    { "glMultiTexCoord3f", "<(GLenum) target> <(GLfloat) s> <(GLfloat) t> <(GLfloat) r>", TclGL_glMultiTexCoord3fCmd } ,
    { "glMultiTexCoord3fv", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord3fvCmd } ,
    { "glMultiTexCoord3i", "<(GLenum) target> <(GLint) s> <(GLint) t> <(GLint) r>", TclGL_glMultiTexCoord3iCmd } ,
    { "glMultiTexCoord3iv", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord3ivCmd } ,
    { "glMultiTexCoord3s", "<(GLenum) target> <(GLshort) s> <(GLshort) t> <(GLshort) r>", TclGL_glMultiTexCoord3sCmd } ,
    { "glMultiTexCoord3sv", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord3svCmd } ,
    { "glMultiTexCoord4d", "<(GLenum) target> <(GLdouble) s> <(GLdouble) t> <(GLdouble) r> <(GLdouble) q>", TclGL_glMultiTexCoord4dCmd } ,
    { "glMultiTexCoord4dv", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord4dvCmd } ,
    { "glMultiTexCoord4f", "<(GLenum) target> <(GLfloat) s> <(GLfloat) t> <(GLfloat) r> <(GLfloat) q>", TclGL_glMultiTexCoord4fCmd } ,
    { "glMultiTexCoord4fv", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord4fvCmd } ,
    { "glMultiTexCoord4i", "<(GLenum) target> <(GLint) s> <(GLint) t> <(GLint) r> <(GLint) q>", TclGL_glMultiTexCoord4iCmd } ,
    { "glMultiTexCoord4iv", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord4ivCmd } ,
    { "glMultiTexCoord4s", "<(GLenum) target> <(GLshort) s> <(GLshort) t> <(GLshort) r> <(GLshort) q>", TclGL_glMultiTexCoord4sCmd } ,
    { "glMultiTexCoord4sv", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord4svCmd } ,
    { "glLoadTransposeMatrixd", "<(GLdouble) m[16]> !not yet!", TclGL_glLoadTransposeMatrixdCmd } ,
    { "glLoadTransposeMatrixf", "<(GLfloat) m[16]> !not yet!", TclGL_glLoadTransposeMatrixfCmd } ,
    { "glMultTransposeMatrixd", "<(GLdouble) m[16]> !not yet!", TclGL_glMultTransposeMatrixdCmd } ,
    { "glMultTransposeMatrixf", "<(GLfloat) m[16]> !not yet!", TclGL_glMultTransposeMatrixfCmd } ,
    { "glSampleCoverage", "<(GLclampf) value> <(GLboolean) invert>", TclGL_glSampleCoverageCmd } ,
    { "glActiveTextureARB", "<(GLenum) texture>", TclGL_glActiveTextureARBCmd } ,
    { "glClientActiveTextureARB", "<(GLenum) texture>", TclGL_glClientActiveTextureARBCmd } ,
    { "glMultiTexCoord1dARB", "<(GLenum) target> <(GLdouble) s>", TclGL_glMultiTexCoord1dARBCmd } ,
    { "glMultiTexCoord1dvARB", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord1dvARBCmd } ,
    { "glMultiTexCoord1fARB", "<(GLenum) target> <(GLfloat) s>", TclGL_glMultiTexCoord1fARBCmd } ,
    { "glMultiTexCoord1fvARB", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord1fvARBCmd } ,
    { "glMultiTexCoord1iARB", "<(GLenum) target> <(GLint) s>", TclGL_glMultiTexCoord1iARBCmd } ,
    { "glMultiTexCoord1ivARB", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord1ivARBCmd } ,
    { "glMultiTexCoord1sARB", "<(GLenum) target> <(GLshort) s>", TclGL_glMultiTexCoord1sARBCmd } ,
    { "glMultiTexCoord1svARB", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord1svARBCmd } ,
    { "glMultiTexCoord2dARB", "<(GLenum) target> <(GLdouble) s> <(GLdouble) t>", TclGL_glMultiTexCoord2dARBCmd } ,
    { "glMultiTexCoord2dvARB", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord2dvARBCmd } ,
    { "glMultiTexCoord2fARB", "<(GLenum) target> <(GLfloat) s> <(GLfloat) t>", TclGL_glMultiTexCoord2fARBCmd } ,
    { "glMultiTexCoord2fvARB", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord2fvARBCmd } ,
    { "glMultiTexCoord2iARB", "<(GLenum) target> <(GLint) s> <(GLint) t>", TclGL_glMultiTexCoord2iARBCmd } ,
    { "glMultiTexCoord2ivARB", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord2ivARBCmd } ,
    { "glMultiTexCoord2sARB", "<(GLenum) target> <(GLshort) s> <(GLshort) t>", TclGL_glMultiTexCoord2sARBCmd } ,
    { "glMultiTexCoord2svARB", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord2svARBCmd } ,
    { "glMultiTexCoord3dARB", "<(GLenum) target> <(GLdouble) s> <(GLdouble) t> <(GLdouble) r>", TclGL_glMultiTexCoord3dARBCmd } ,
    { "glMultiTexCoord3dvARB", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord3dvARBCmd } ,
    { "glMultiTexCoord3fARB", "<(GLenum) target> <(GLfloat) s> <(GLfloat) t> <(GLfloat) r>", TclGL_glMultiTexCoord3fARBCmd } ,
    { "glMultiTexCoord3fvARB", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord3fvARBCmd } ,
    { "glMultiTexCoord3iARB", "<(GLenum) target> <(GLint) s> <(GLint) t> <(GLint) r>", TclGL_glMultiTexCoord3iARBCmd } ,
    { "glMultiTexCoord3ivARB", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord3ivARBCmd } ,
    { "glMultiTexCoord3sARB", "<(GLenum) target> <(GLshort) s> <(GLshort) t> <(GLshort) r>", TclGL_glMultiTexCoord3sARBCmd } ,
    { "glMultiTexCoord3svARB", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord3svARBCmd } ,
    { "glMultiTexCoord4dARB", "<(GLenum) target> <(GLdouble) s> <(GLdouble) t> <(GLdouble) r> <(GLdouble) q>", TclGL_glMultiTexCoord4dARBCmd } ,
    { "glMultiTexCoord4dvARB", "<(GLenum) target> <(GLdouble) v>", TclGL_glMultiTexCoord4dvARBCmd } ,
    { "glMultiTexCoord4fARB", "<(GLenum) target> <(GLfloat) s> <(GLfloat) t> <(GLfloat) r> <(GLfloat) q>", TclGL_glMultiTexCoord4fARBCmd } ,
    { "glMultiTexCoord4fvARB", "<(GLenum) target> <(GLfloat) v>", TclGL_glMultiTexCoord4fvARBCmd } ,
    { "glMultiTexCoord4iARB", "<(GLenum) target> <(GLint) s> <(GLint) t> <(GLint) r> <(GLint) q>", TclGL_glMultiTexCoord4iARBCmd } ,
    { "glMultiTexCoord4ivARB", "<(GLenum) target> <(GLint) v>", TclGL_glMultiTexCoord4ivARBCmd } ,
    { "glMultiTexCoord4sARB", "<(GLenum) target> <(GLshort) s> <(GLshort) t> <(GLshort) r> <(GLshort) q>", TclGL_glMultiTexCoord4sARBCmd } ,
    { "glMultiTexCoord4svARB", "<(GLenum) target> <(GLshort) v>", TclGL_glMultiTexCoord4svARBCmd } ,
    { "glBlendEquationSeparateATI", "<(GLenum) modeRGB> <(GLenum) modeA>", TclGL_glBlendEquationSeparateATICmd } ,
