#define TCL_NUM_GL_FUNC_GROUPS 19
#define TCL_NUM_GL_FUNCS 452

typedef void (* GLfunction_void_float)(float);
typedef void (* GLfunction_void_float_float_float_float)(float, float, float, float);
typedef void (* GLfunction_void_int)(int);
typedef void (* GLfunction_void_int_int_int_int)(int, int, int, int);
typedef void (* GLfunction_void_int_float)(int, float);
typedef void (* GLfunction_void_int_int)(int, int);
typedef void (* GLfunction_void_float_float)(float, float);
typedef void (* GLfunction_void_voidPtr)(void*);
typedef void (* GLfunction_void_int_voidPtr)(int, void*);
typedef GLboolean (* GLfunction_GLboolean_int)(int);
typedef void (* GLfunction_void_)();
typedef GLint (* GLfunction_GLint_int)(int);
typedef GLenum (* GLfunction_GLenum_)();
typedef void (* GLfunction_void_double)(double);
typedef void (* GLfunction_void_double_double)(double, double);
typedef void (* GLfunction_void_double_double_double_double_double_double)(double, double, double, double, double, double);
typedef void (* GLfunction_void_double_double_double_double)(double, double, double, double);
typedef void (* GLfunction_void_double_double_double)(double, double, double);
typedef void (* GLfunction_void_float_float_float)(float, float, float);
typedef GLuint (* GLfunction_GLuint_int)(int);
typedef void (* GLfunction_void_int_int_voidPtr)(int, int, void*);
typedef void (* GLfunction_void_int_int_int)(int, int, int);
typedef void (* GLfunction_void_voidPtr_voidPtr)(void*, void*);
typedef void (* GLfunction_void_int_int_int_voidPtr)(int, int, int, void*);
typedef void (* GLfunction_void_int_voidPtrPtr)(int, void**);
typedef void (* GLfunction_void_int_int_float)(int, int, float);
typedef void (* GLfunction_void_int_int_float_float_float_float_voidPtr)(int, int, float, float, float, float, void*);
typedef void (* GLfunction_void_int_int_int_int_int_int_voidPtr)(int, int, int, int, int, int, void*);
typedef void (* GLfunction_void_int_int_int_int_voidPtr)(int, int, int, int, void*);
typedef void (* GLfunction_void_int_int_int_int_int)(int, int, int, int, int);
typedef void (* GLfunction_void_int_int_double)(int, int, double);
typedef void (* GLfunction_void_int_int_int_int_int_int_int_voidPtr)(int, int, int, int, int, int, int, void*);
typedef void (* GLfunction_void_int_int_int_int_int_int_int_int_voidPtr)(int, int, int, int, int, int, int, int, void*);
typedef void (* GLfunction_void_int_voidPtr_voidPtr)(int, void*, void*);
typedef void (* GLfunction_void_int_int_int_int_int_int_int)(int, int, int, int, int, int, int);
typedef void (* GLfunction_void_int_int_int_int_int_int_int_int)(int, int, int, int, int, int, int, int);
typedef void (* GLfunction_void_int_int_int_int_int_int)(int, int, int, int, int, int);
typedef void (* GLfunction_void_int_double_double_int_int_voidPtr)(int, double, double, int, int, void*);
typedef void (* GLfunction_void_int_float_float_int_int_voidPtr)(int, float, float, int, int, void*);
typedef void (* GLfunction_void_int_double_double_int_int_double_double_int_int_voidPtr)(int, double, double, int, int, double, double, int, int, void*);
typedef void (* GLfunction_void_int_float_float_int_int_float_float_int_int_voidPtr)(int, float, float, int, int, float, float, int, int, void*);
typedef void (* GLfunction_void_int_double_double)(int, double, double);
typedef void (* GLfunction_void_int_float_float)(int, float, float);
typedef void (* GLfunction_void_int_double_double_int_double_double)(int, double, double, int, double, double);
typedef void (* GLfunction_void_int_float_float_int_float_float)(int, float, float, int, float, float);
typedef void (* GLfunction_void_int_int_int_int_int_voidPtr)(int, int, int, int, int, void*);
typedef void (* GLfunction_void_int_int_int_int_int_int_int_int_int_voidPtr)(int, int, int, int, int, int, int, int, int, void*);
typedef void (* GLfunction_void_int_int_int_int_int_int_int_int_int_int_voidPtr)(int, int, int, int, int, int, int, int, int, int, void*);
typedef void (* GLfunction_void_int_int_int_int_int_int_int_int_int)(int, int, int, int, int, int, int, int, int);
typedef void (* GLfunction_void_int_int_int_int_int_int_voidPtr_voidPtr)(int, int, int, int, int, int, void*, void*);
typedef void (* GLfunction_void_int_int_int_voidPtr_voidPtr_voidPtr)(int, int, int, void*, void*, void*);
typedef void (* GLfunction_void_int_double)(int, double);
typedef void (* GLfunction_void_int_double_double_double)(int, double, double, double);
typedef void (* GLfunction_void_int_float_float_float)(int, float, float, float);
typedef void (* GLfunction_void_int_double_double_double_double)(int, double, double, double, double);
typedef void (* GLfunction_void_int_float_float_float_float)(int, float, float, float, float);
typedef void (* GLfunction_void_float_int)(float, int);
