    { "::ntk::gl::GL::glClearIndex",
            NULL, TclGL_glClearIndexCmd },
    { "::ntk::gl::GL::glClearColor",
            NULL, TclGL_glClearColorCmd },
    { "::ntk::gl::GL::glClear",
            NULL, TclGL_glClearCmd },
    { "::ntk::gl::GL::glIndexMask",
            NULL, TclGL_glIndexMaskCmd },
    { "::ntk::gl::GL::glColorMask",
            NULL, TclGL_glColorMaskCmd },
    { "::ntk::gl::GL::glAlphaFunc",
            NULL, TclGL_glAlphaFuncCmd },
    { "::ntk::gl::GL::glBlendFunc",
            NULL, TclGL_glBlendFuncCmd },
    { "::ntk::gl::GL::glLogicOp",
            NULL, TclGL_glLogicOpCmd },
    { "::ntk::gl::GL::glCullFace",
            NULL, TclGL_glCullFaceCmd },
    { "::ntk::gl::GL::glFrontFace",
            NULL, TclGL_glFrontFaceCmd },
    { "::ntk::gl::GL::glPointSize",
            NULL, TclGL_glPointSizeCmd },
    { "::ntk::gl::GL::glLineWidth",
            NULL, TclGL_glLineWidthCmd },
    { "::ntk::gl::GL::glLineStipple",
            NULL, TclGL_glLineStippleCmd },
    { "::ntk::gl::GL::glPolygonMode",
            NULL, TclGL_glPolygonModeCmd },
    { "::ntk::gl::GL::glPolygonOffset",
            NULL, TclGL_glPolygonOffsetCmd },
    { "::ntk::gl::GL::glPolygonStipple",
            NULL, TclGL_glPolygonStippleCmd },
    { "::ntk::gl::GL::glGetPolygonStipple",
            NULL, TclGL_glGetPolygonStippleCmd },
    { "::ntk::gl::GL::glEdgeFlag",
            NULL, TclGL_glEdgeFlagCmd },
    { "::ntk::gl::GL::glEdgeFlagv",
            NULL, TclGL_glEdgeFlagvCmd },
    { "::ntk::gl::GL::glScissor",
            NULL, TclGL_glScissorCmd },
    { "::ntk::gl::GL::glClipPlane",
            NULL, TclGL_glClipPlaneCmd },
    { "::ntk::gl::GL::glGetClipPlane",
            NULL, TclGL_glGetClipPlaneCmd },
    { "::ntk::gl::GL::glDrawBuffer",
            NULL, TclGL_glDrawBufferCmd },
    { "::ntk::gl::GL::glReadBuffer",
            NULL, TclGL_glReadBufferCmd },
    { "::ntk::gl::GL::glEnable",
            NULL, TclGL_glEnableCmd },
    { "::ntk::gl::GL::glDisable",
            NULL, TclGL_glDisableCmd },
    { "::ntk::gl::GL::glIsEnabled",
            NULL, TclGL_glIsEnabledCmd },
    { "::ntk::gl::GL::glEnableClientState",
            NULL, TclGL_glEnableClientStateCmd },
    { "::ntk::gl::GL::glDisableClientState",
            NULL, TclGL_glDisableClientStateCmd },
    { "::ntk::gl::GL::glGetBooleanv",
            NULL, TclGL_glGetBooleanvCmd },
    { "::ntk::gl::GL::glGetDoublev",
            NULL, TclGL_glGetDoublevCmd },
    { "::ntk::gl::GL::glGetFloatv",
            NULL, TclGL_glGetFloatvCmd },
    { "::ntk::gl::GL::glGetIntegerv",
            NULL, TclGL_glGetIntegervCmd },
    { "::ntk::gl::GL::glPushAttrib",
            NULL, TclGL_glPushAttribCmd },
    { "::ntk::gl::GL::glPopAttrib",
            NULL, TclGL_glPopAttribCmd },
    { "::ntk::gl::GL::glPushClientAttrib",
            NULL, TclGL_glPushClientAttribCmd },
    { "::ntk::gl::GL::glPopClientAttrib",
            NULL, TclGL_glPopClientAttribCmd },
    { "::ntk::gl::GL::glRenderMode",
            NULL, TclGL_glRenderModeCmd },
    { "::ntk::gl::GL::glGetError",
            NULL, TclGL_glGetErrorCmd },
    { "::ntk::gl::GL::glGetString",
            NULL, TclGL_glGetStringCmd },
    { "::ntk::gl::GL::glFinish",
            NULL, TclGL_glFinishCmd },
    { "::ntk::gl::GL::glFlush",
            NULL, TclGL_glFlushCmd },
    { "::ntk::gl::GL::glHint",
            NULL, TclGL_glHintCmd },
    { "::ntk::gl::GL::glClearDepth",
            NULL, TclGL_glClearDepthCmd },
    { "::ntk::gl::GL::glDepthFunc",
            NULL, TclGL_glDepthFuncCmd },
    { "::ntk::gl::GL::glDepthMask",
            NULL, TclGL_glDepthMaskCmd },
    { "::ntk::gl::GL::glDepthRange",
            NULL, TclGL_glDepthRangeCmd },
    { "::ntk::gl::GL::glClearAccum",
            NULL, TclGL_glClearAccumCmd },
    { "::ntk::gl::GL::glAccum",
            NULL, TclGL_glAccumCmd },
    { "::ntk::gl::GL::glMatrixMode",
            NULL, TclGL_glMatrixModeCmd },
    { "::ntk::gl::GL::glOrtho",
            NULL, TclGL_glOrthoCmd },
    { "::ntk::gl::GL::glFrustum",
            NULL, TclGL_glFrustumCmd },
    { "::ntk::gl::GL::glViewport",
            NULL, TclGL_glViewportCmd },
    { "::ntk::gl::GL::glPushMatrix",
            NULL, TclGL_glPushMatrixCmd },
    { "::ntk::gl::GL::glPopMatrix",
            NULL, TclGL_glPopMatrixCmd },
    { "::ntk::gl::GL::glLoadIdentity",
            NULL, TclGL_glLoadIdentityCmd },
    { "::ntk::gl::GL::glLoadMatrixd",
            NULL, TclGL_glLoadMatrixdCmd },
    { "::ntk::gl::GL::glLoadMatrixf",
            NULL, TclGL_glLoadMatrixfCmd },
    { "::ntk::gl::GL::glMultMatrixd",
            NULL, TclGL_glMultMatrixdCmd },
    { "::ntk::gl::GL::glMultMatrixf",
            NULL, TclGL_glMultMatrixfCmd },
    { "::ntk::gl::GL::glRotated",
            NULL, TclGL_glRotatedCmd },
    { "::ntk::gl::GL::glRotatef",
            NULL, TclGL_glRotatefCmd },
    { "::ntk::gl::GL::glScaled",
            NULL, TclGL_glScaledCmd },
    { "::ntk::gl::GL::glScalef",
            NULL, TclGL_glScalefCmd },
    { "::ntk::gl::GL::glTranslated",
            NULL, TclGL_glTranslatedCmd },
    { "::ntk::gl::GL::glTranslatef",
            NULL, TclGL_glTranslatefCmd },
    { "::ntk::gl::GL::glIsList",
            NULL, TclGL_glIsListCmd },
    { "::ntk::gl::GL::glDeleteLists",
            NULL, TclGL_glDeleteListsCmd },
    { "::ntk::gl::GL::glGenLists",
            NULL, TclGL_glGenListsCmd },
    { "::ntk::gl::GL::glNewList",
            NULL, TclGL_glNewListCmd },
    { "::ntk::gl::GL::glEndList",
            NULL, TclGL_glEndListCmd },
    { "::ntk::gl::GL::glCallList",
            NULL, TclGL_glCallListCmd },
    { "::ntk::gl::GL::glCallLists",
            NULL, TclGL_glCallListsCmd },
    { "::ntk::gl::GL::glListBase",
            NULL, TclGL_glListBaseCmd },
    { "::ntk::gl::GL::glBegin",
            NULL, TclGL_glBeginCmd },
    { "::ntk::gl::GL::glEnd",
            NULL, TclGL_glEndCmd },
    { "::ntk::gl::GL::glVertex2d",
            NULL, TclGL_glVertex2dCmd },
    { "::ntk::gl::GL::glVertex2f",
            NULL, TclGL_glVertex2fCmd },
    { "::ntk::gl::GL::glVertex2i",
            NULL, TclGL_glVertex2iCmd },
    { "::ntk::gl::GL::glVertex2s",
            NULL, TclGL_glVertex2sCmd },
    { "::ntk::gl::GL::glVertex3d",
            NULL, TclGL_glVertex3dCmd },
    { "::ntk::gl::GL::glVertex3f",
            NULL, TclGL_glVertex3fCmd },
    { "::ntk::gl::GL::glVertex3i",
            NULL, TclGL_glVertex3iCmd },
    { "::ntk::gl::GL::glVertex3s",
            NULL, TclGL_glVertex3sCmd },
    { "::ntk::gl::GL::glVertex4d",
            NULL, TclGL_glVertex4dCmd },
    { "::ntk::gl::GL::glVertex4f",
            NULL, TclGL_glVertex4fCmd },
    { "::ntk::gl::GL::glVertex4i",
            NULL, TclGL_glVertex4iCmd },
    { "::ntk::gl::GL::glVertex4s",
            NULL, TclGL_glVertex4sCmd },
    { "::ntk::gl::GL::glVertex2dv",
            NULL, TclGL_glVertex2dvCmd },
    { "::ntk::gl::GL::glVertex2fv",
            NULL, TclGL_glVertex2fvCmd },
    { "::ntk::gl::GL::glVertex2iv",
            NULL, TclGL_glVertex2ivCmd },
    { "::ntk::gl::GL::glVertex2sv",
            NULL, TclGL_glVertex2svCmd },
    { "::ntk::gl::GL::glVertex3dv",
            NULL, TclGL_glVertex3dvCmd },
    { "::ntk::gl::GL::glVertex3fv",
            NULL, TclGL_glVertex3fvCmd },
    { "::ntk::gl::GL::glVertex3iv",
            NULL, TclGL_glVertex3ivCmd },
    { "::ntk::gl::GL::glVertex3sv",
            NULL, TclGL_glVertex3svCmd },
    { "::ntk::gl::GL::glVertex4dv",
            NULL, TclGL_glVertex4dvCmd },
    { "::ntk::gl::GL::glVertex4fv",
            NULL, TclGL_glVertex4fvCmd },
    { "::ntk::gl::GL::glVertex4iv",
            NULL, TclGL_glVertex4ivCmd },
    { "::ntk::gl::GL::glVertex4sv",
            NULL, TclGL_glVertex4svCmd },
    { "::ntk::gl::GL::glNormal3b",
            NULL, TclGL_glNormal3bCmd },
    { "::ntk::gl::GL::glNormal3d",
            NULL, TclGL_glNormal3dCmd },
    { "::ntk::gl::GL::glNormal3f",
            NULL, TclGL_glNormal3fCmd },
    { "::ntk::gl::GL::glNormal3i",
            NULL, TclGL_glNormal3iCmd },
    { "::ntk::gl::GL::glNormal3s",
            NULL, TclGL_glNormal3sCmd },
    { "::ntk::gl::GL::glNormal3bv",
            NULL, TclGL_glNormal3bvCmd },
    { "::ntk::gl::GL::glNormal3dv",
            NULL, TclGL_glNormal3dvCmd },
    { "::ntk::gl::GL::glNormal3fv",
            NULL, TclGL_glNormal3fvCmd },
    { "::ntk::gl::GL::glNormal3iv",
            NULL, TclGL_glNormal3ivCmd },
    { "::ntk::gl::GL::glNormal3sv",
            NULL, TclGL_glNormal3svCmd },
    { "::ntk::gl::GL::glIndexd",
            NULL, TclGL_glIndexdCmd },
    { "::ntk::gl::GL::glIndexf",
            NULL, TclGL_glIndexfCmd },
    { "::ntk::gl::GL::glIndexi",
            NULL, TclGL_glIndexiCmd },
    { "::ntk::gl::GL::glIndexs",
            NULL, TclGL_glIndexsCmd },
    { "::ntk::gl::GL::glIndexub",
            NULL, TclGL_glIndexubCmd },
    { "::ntk::gl::GL::glIndexdv",
            NULL, TclGL_glIndexdvCmd },
    { "::ntk::gl::GL::glIndexfv",
            NULL, TclGL_glIndexfvCmd },
    { "::ntk::gl::GL::glIndexiv",
            NULL, TclGL_glIndexivCmd },
    { "::ntk::gl::GL::glIndexsv",
            NULL, TclGL_glIndexsvCmd },
    { "::ntk::gl::GL::glIndexubv",
            NULL, TclGL_glIndexubvCmd },
    { "::ntk::gl::GL::glColor3b",
            NULL, TclGL_glColor3bCmd },
    { "::ntk::gl::GL::glColor3d",
            NULL, TclGL_glColor3dCmd },
    { "::ntk::gl::GL::glColor3f",
            NULL, TclGL_glColor3fCmd },
    { "::ntk::gl::GL::glColor3i",
            NULL, TclGL_glColor3iCmd },
    { "::ntk::gl::GL::glColor3s",
            NULL, TclGL_glColor3sCmd },
    { "::ntk::gl::GL::glColor3ub",
            NULL, TclGL_glColor3ubCmd },
    { "::ntk::gl::GL::glColor3ui",
            NULL, TclGL_glColor3uiCmd },
    { "::ntk::gl::GL::glColor3us",
            NULL, TclGL_glColor3usCmd },
    { "::ntk::gl::GL::glColor4b",
            NULL, TclGL_glColor4bCmd },
    { "::ntk::gl::GL::glColor4d",
            NULL, TclGL_glColor4dCmd },
    { "::ntk::gl::GL::glColor4f",
            NULL, TclGL_glColor4fCmd },
    { "::ntk::gl::GL::glColor4i",
            NULL, TclGL_glColor4iCmd },
    { "::ntk::gl::GL::glColor4s",
            NULL, TclGL_glColor4sCmd },
    { "::ntk::gl::GL::glColor4ub",
            NULL, TclGL_glColor4ubCmd },
    { "::ntk::gl::GL::glColor4ui",
            NULL, TclGL_glColor4uiCmd },
    { "::ntk::gl::GL::glColor4us",
            NULL, TclGL_glColor4usCmd },
    { "::ntk::gl::GL::glColor3bv",
            NULL, TclGL_glColor3bvCmd },
    { "::ntk::gl::GL::glColor3dv",
            NULL, TclGL_glColor3dvCmd },
    { "::ntk::gl::GL::glColor3fv",
            NULL, TclGL_glColor3fvCmd },
    { "::ntk::gl::GL::glColor3iv",
            NULL, TclGL_glColor3ivCmd },
    { "::ntk::gl::GL::glColor3sv",
            NULL, TclGL_glColor3svCmd },
    { "::ntk::gl::GL::glColor3ubv",
            NULL, TclGL_glColor3ubvCmd },
    { "::ntk::gl::GL::glColor3uiv",
            NULL, TclGL_glColor3uivCmd },
    { "::ntk::gl::GL::glColor3usv",
            NULL, TclGL_glColor3usvCmd },
    { "::ntk::gl::GL::glColor4bv",
            NULL, TclGL_glColor4bvCmd },
    { "::ntk::gl::GL::glColor4dv",
            NULL, TclGL_glColor4dvCmd },
    { "::ntk::gl::GL::glColor4fv",
            NULL, TclGL_glColor4fvCmd },
    { "::ntk::gl::GL::glColor4iv",
            NULL, TclGL_glColor4ivCmd },
    { "::ntk::gl::GL::glColor4sv",
            NULL, TclGL_glColor4svCmd },
    { "::ntk::gl::GL::glColor4ubv",
            NULL, TclGL_glColor4ubvCmd },
    { "::ntk::gl::GL::glColor4uiv",
            NULL, TclGL_glColor4uivCmd },
    { "::ntk::gl::GL::glColor4usv",
            NULL, TclGL_glColor4usvCmd },
    { "::ntk::gl::GL::glTexCoord1d",
            NULL, TclGL_glTexCoord1dCmd },
    { "::ntk::gl::GL::glTexCoord1f",
            NULL, TclGL_glTexCoord1fCmd },
    { "::ntk::gl::GL::glTexCoord1i",
            NULL, TclGL_glTexCoord1iCmd },
    { "::ntk::gl::GL::glTexCoord1s",
            NULL, TclGL_glTexCoord1sCmd },
    { "::ntk::gl::GL::glTexCoord2d",
            NULL, TclGL_glTexCoord2dCmd },
    { "::ntk::gl::GL::glTexCoord2f",
            NULL, TclGL_glTexCoord2fCmd },
    { "::ntk::gl::GL::glTexCoord2i",
            NULL, TclGL_glTexCoord2iCmd },
    { "::ntk::gl::GL::glTexCoord2s",
            NULL, TclGL_glTexCoord2sCmd },
    { "::ntk::gl::GL::glTexCoord3d",
            NULL, TclGL_glTexCoord3dCmd },
    { "::ntk::gl::GL::glTexCoord3f",
            NULL, TclGL_glTexCoord3fCmd },
    { "::ntk::gl::GL::glTexCoord3i",
            NULL, TclGL_glTexCoord3iCmd },
    { "::ntk::gl::GL::glTexCoord3s",
            NULL, TclGL_glTexCoord3sCmd },
    { "::ntk::gl::GL::glTexCoord4d",
            NULL, TclGL_glTexCoord4dCmd },
    { "::ntk::gl::GL::glTexCoord4f",
            NULL, TclGL_glTexCoord4fCmd },
    { "::ntk::gl::GL::glTexCoord4i",
            NULL, TclGL_glTexCoord4iCmd },
    { "::ntk::gl::GL::glTexCoord4s",
            NULL, TclGL_glTexCoord4sCmd },
    { "::ntk::gl::GL::glTexCoord1dv",
            NULL, TclGL_glTexCoord1dvCmd },
    { "::ntk::gl::GL::glTexCoord1fv",
            NULL, TclGL_glTexCoord1fvCmd },
    { "::ntk::gl::GL::glTexCoord1iv",
            NULL, TclGL_glTexCoord1ivCmd },
    { "::ntk::gl::GL::glTexCoord1sv",
            NULL, TclGL_glTexCoord1svCmd },
    { "::ntk::gl::GL::glTexCoord2dv",
            NULL, TclGL_glTexCoord2dvCmd },
    { "::ntk::gl::GL::glTexCoord2fv",
            NULL, TclGL_glTexCoord2fvCmd },
    { "::ntk::gl::GL::glTexCoord2iv",
            NULL, TclGL_glTexCoord2ivCmd },
    { "::ntk::gl::GL::glTexCoord2sv",
            NULL, TclGL_glTexCoord2svCmd },
    { "::ntk::gl::GL::glTexCoord3dv",
            NULL, TclGL_glTexCoord3dvCmd },
    { "::ntk::gl::GL::glTexCoord3fv",
            NULL, TclGL_glTexCoord3fvCmd },
    { "::ntk::gl::GL::glTexCoord3iv",
            NULL, TclGL_glTexCoord3ivCmd },
    { "::ntk::gl::GL::glTexCoord3sv",
            NULL, TclGL_glTexCoord3svCmd },
    { "::ntk::gl::GL::glTexCoord4dv",
            NULL, TclGL_glTexCoord4dvCmd },
    { "::ntk::gl::GL::glTexCoord4fv",
            NULL, TclGL_glTexCoord4fvCmd },
    { "::ntk::gl::GL::glTexCoord4iv",
            NULL, TclGL_glTexCoord4ivCmd },
    { "::ntk::gl::GL::glTexCoord4sv",
            NULL, TclGL_glTexCoord4svCmd },
    { "::ntk::gl::GL::glRasterPos2d",
            NULL, TclGL_glRasterPos2dCmd },
    { "::ntk::gl::GL::glRasterPos2f",
            NULL, TclGL_glRasterPos2fCmd },
    { "::ntk::gl::GL::glRasterPos2i",
            NULL, TclGL_glRasterPos2iCmd },
    { "::ntk::gl::GL::glRasterPos2s",
            NULL, TclGL_glRasterPos2sCmd },
    { "::ntk::gl::GL::glRasterPos3d",
            NULL, TclGL_glRasterPos3dCmd },
    { "::ntk::gl::GL::glRasterPos3f",
            NULL, TclGL_glRasterPos3fCmd },
    { "::ntk::gl::GL::glRasterPos3i",
            NULL, TclGL_glRasterPos3iCmd },
    { "::ntk::gl::GL::glRasterPos3s",
            NULL, TclGL_glRasterPos3sCmd },
    { "::ntk::gl::GL::glRasterPos4d",
            NULL, TclGL_glRasterPos4dCmd },
    { "::ntk::gl::GL::glRasterPos4f",
            NULL, TclGL_glRasterPos4fCmd },
    { "::ntk::gl::GL::glRasterPos4i",
            NULL, TclGL_glRasterPos4iCmd },
    { "::ntk::gl::GL::glRasterPos4s",
            NULL, TclGL_glRasterPos4sCmd },
    { "::ntk::gl::GL::glRasterPos2dv",
            NULL, TclGL_glRasterPos2dvCmd },
    { "::ntk::gl::GL::glRasterPos2fv",
            NULL, TclGL_glRasterPos2fvCmd },
    { "::ntk::gl::GL::glRasterPos2iv",
            NULL, TclGL_glRasterPos2ivCmd },
    { "::ntk::gl::GL::glRasterPos2sv",
            NULL, TclGL_glRasterPos2svCmd },
    { "::ntk::gl::GL::glRasterPos3dv",
            NULL, TclGL_glRasterPos3dvCmd },
    { "::ntk::gl::GL::glRasterPos3fv",
            NULL, TclGL_glRasterPos3fvCmd },
    { "::ntk::gl::GL::glRasterPos3iv",
            NULL, TclGL_glRasterPos3ivCmd },
    { "::ntk::gl::GL::glRasterPos3sv",
            NULL, TclGL_glRasterPos3svCmd },
    { "::ntk::gl::GL::glRasterPos4dv",
            NULL, TclGL_glRasterPos4dvCmd },
    { "::ntk::gl::GL::glRasterPos4fv",
            NULL, TclGL_glRasterPos4fvCmd },
    { "::ntk::gl::GL::glRasterPos4iv",
            NULL, TclGL_glRasterPos4ivCmd },
    { "::ntk::gl::GL::glRasterPos4sv",
            NULL, TclGL_glRasterPos4svCmd },
    { "::ntk::gl::GL::glRectd",
            NULL, TclGL_glRectdCmd },
    { "::ntk::gl::GL::glRectf",
            NULL, TclGL_glRectfCmd },
    { "::ntk::gl::GL::glRecti",
            NULL, TclGL_glRectiCmd },
    { "::ntk::gl::GL::glRects",
            NULL, TclGL_glRectsCmd },
    { "::ntk::gl::GL::glRectdv",
            NULL, TclGL_glRectdvCmd },
    { "::ntk::gl::GL::glRectfv",
            NULL, TclGL_glRectfvCmd },
    { "::ntk::gl::GL::glRectiv",
            NULL, TclGL_glRectivCmd },
    { "::ntk::gl::GL::glRectsv",
            NULL, TclGL_glRectsvCmd },
    { "::ntk::gl::GL::glVertexPointer",
            NULL, TclGL_glVertexPointerCmd },
    { "::ntk::gl::GL::glNormalPointer",
            NULL, TclGL_glNormalPointerCmd },
    { "::ntk::gl::GL::glColorPointer",
            NULL, TclGL_glColorPointerCmd },
    { "::ntk::gl::GL::glIndexPointer",
            NULL, TclGL_glIndexPointerCmd },
    { "::ntk::gl::GL::glTexCoordPointer",
            NULL, TclGL_glTexCoordPointerCmd },
    { "::ntk::gl::GL::glEdgeFlagPointer",
            NULL, TclGL_glEdgeFlagPointerCmd },
    { "::ntk::gl::GL::glGetPointerv",
            NULL, TclGL_glGetPointervCmd },
    { "::ntk::gl::GL::glArrayElement",
            NULL, TclGL_glArrayElementCmd },
    { "::ntk::gl::GL::glDrawArrays",
            NULL, TclGL_glDrawArraysCmd },
    { "::ntk::gl::GL::glDrawElements",
            NULL, TclGL_glDrawElementsCmd },
    { "::ntk::gl::GL::glInterleavedArrays",
            NULL, TclGL_glInterleavedArraysCmd },
    { "::ntk::gl::GL::glShadeModel",
            NULL, TclGL_glShadeModelCmd },
    { "::ntk::gl::GL::glLightf",
            NULL, TclGL_glLightfCmd },
    { "::ntk::gl::GL::glLighti",
            NULL, TclGL_glLightiCmd },
    { "::ntk::gl::GL::glLightfv",
            NULL, TclGL_glLightfvCmd },
    { "::ntk::gl::GL::glLightiv",
            NULL, TclGL_glLightivCmd },
    { "::ntk::gl::GL::glGetLightfv",
            NULL, TclGL_glGetLightfvCmd },
    { "::ntk::gl::GL::glGetLightiv",
            NULL, TclGL_glGetLightivCmd },
    { "::ntk::gl::GL::glLightModelf",
            NULL, TclGL_glLightModelfCmd },
    { "::ntk::gl::GL::glLightModeli",
            NULL, TclGL_glLightModeliCmd },
    { "::ntk::gl::GL::glLightModelfv",
            NULL, TclGL_glLightModelfvCmd },
    { "::ntk::gl::GL::glLightModeliv",
            NULL, TclGL_glLightModelivCmd },
    { "::ntk::gl::GL::glMaterialf",
            NULL, TclGL_glMaterialfCmd },
    { "::ntk::gl::GL::glMateriali",
            NULL, TclGL_glMaterialiCmd },
    { "::ntk::gl::GL::glMaterialfv",
            NULL, TclGL_glMaterialfvCmd },
    { "::ntk::gl::GL::glMaterialiv",
            NULL, TclGL_glMaterialivCmd },
    { "::ntk::gl::GL::glGetMaterialfv",
            NULL, TclGL_glGetMaterialfvCmd },
    { "::ntk::gl::GL::glGetMaterialiv",
            NULL, TclGL_glGetMaterialivCmd },
    { "::ntk::gl::GL::glColorMaterial",
            NULL, TclGL_glColorMaterialCmd },
    { "::ntk::gl::GL::glPixelZoom",
            NULL, TclGL_glPixelZoomCmd },
    { "::ntk::gl::GL::glPixelStoref",
            NULL, TclGL_glPixelStorefCmd },
    { "::ntk::gl::GL::glPixelStorei",
            NULL, TclGL_glPixelStoreiCmd },
    { "::ntk::gl::GL::glPixelTransferf",
            NULL, TclGL_glPixelTransferfCmd },
    { "::ntk::gl::GL::glPixelTransferi",
            NULL, TclGL_glPixelTransferiCmd },
    { "::ntk::gl::GL::glPixelMapfv",
            NULL, TclGL_glPixelMapfvCmd },
    { "::ntk::gl::GL::glPixelMapuiv",
            NULL, TclGL_glPixelMapuivCmd },
    { "::ntk::gl::GL::glPixelMapusv",
            NULL, TclGL_glPixelMapusvCmd },
    { "::ntk::gl::GL::glGetPixelMapfv",
            NULL, TclGL_glGetPixelMapfvCmd },
    { "::ntk::gl::GL::glGetPixelMapuiv",
            NULL, TclGL_glGetPixelMapuivCmd },
    { "::ntk::gl::GL::glGetPixelMapusv",
            NULL, TclGL_glGetPixelMapusvCmd },
    { "::ntk::gl::GL::glBitmap",
            NULL, TclGL_glBitmapCmd },
    { "::ntk::gl::GL::glReadPixels",
            NULL, TclGL_glReadPixelsCmd },
    { "::ntk::gl::GL::glDrawPixels",
            NULL, TclGL_glDrawPixelsCmd },
    { "::ntk::gl::GL::glCopyPixels",
            NULL, TclGL_glCopyPixelsCmd },
    { "::ntk::gl::GL::glStencilFunc",
            NULL, TclGL_glStencilFuncCmd },
    { "::ntk::gl::GL::glStencilMask",
            NULL, TclGL_glStencilMaskCmd },
    { "::ntk::gl::GL::glStencilOp",
            NULL, TclGL_glStencilOpCmd },
    { "::ntk::gl::GL::glClearStencil",
            NULL, TclGL_glClearStencilCmd },
    { "::ntk::gl::GL::glTexGend",
            NULL, TclGL_glTexGendCmd },
    { "::ntk::gl::GL::glTexGenf",
            NULL, TclGL_glTexGenfCmd },
    { "::ntk::gl::GL::glTexGeni",
            NULL, TclGL_glTexGeniCmd },
    { "::ntk::gl::GL::glTexGendv",
            NULL, TclGL_glTexGendvCmd },
    { "::ntk::gl::GL::glTexGenfv",
            NULL, TclGL_glTexGenfvCmd },
    { "::ntk::gl::GL::glTexGeniv",
            NULL, TclGL_glTexGenivCmd },
    { "::ntk::gl::GL::glGetTexGendv",
            NULL, TclGL_glGetTexGendvCmd },
    { "::ntk::gl::GL::glGetTexGenfv",
            NULL, TclGL_glGetTexGenfvCmd },
    { "::ntk::gl::GL::glGetTexGeniv",
            NULL, TclGL_glGetTexGenivCmd },
    { "::ntk::gl::GL::glTexEnvf",
            NULL, TclGL_glTexEnvfCmd },
    { "::ntk::gl::GL::glTexEnvi",
            NULL, TclGL_glTexEnviCmd },
    { "::ntk::gl::GL::glTexEnvfv",
            NULL, TclGL_glTexEnvfvCmd },
    { "::ntk::gl::GL::glTexEnviv",
            NULL, TclGL_glTexEnvivCmd },
    { "::ntk::gl::GL::glGetTexEnvfv",
            NULL, TclGL_glGetTexEnvfvCmd },
    { "::ntk::gl::GL::glGetTexEnviv",
            NULL, TclGL_glGetTexEnvivCmd },
    { "::ntk::gl::GL::glTexParameterf",
            NULL, TclGL_glTexParameterfCmd },
    { "::ntk::gl::GL::glTexParameteri",
            NULL, TclGL_glTexParameteriCmd },
    { "::ntk::gl::GL::glTexParameterfv",
            NULL, TclGL_glTexParameterfvCmd },
    { "::ntk::gl::GL::glTexParameteriv",
            NULL, TclGL_glTexParameterivCmd },
    { "::ntk::gl::GL::glGetTexParameterfv",
            NULL, TclGL_glGetTexParameterfvCmd },
    { "::ntk::gl::GL::glGetTexParameteriv",
            NULL, TclGL_glGetTexParameterivCmd },
    { "::ntk::gl::GL::glGetTexLevelParameterfv",
            NULL, TclGL_glGetTexLevelParameterfvCmd },
    { "::ntk::gl::GL::glGetTexLevelParameteriv",
            NULL, TclGL_glGetTexLevelParameterivCmd },
    { "::ntk::gl::GL::glTexImage1D",
            NULL, TclGL_glTexImage1DCmd },
    { "::ntk::gl::GL::glTexImage2D",
            NULL, TclGL_glTexImage2DCmd },
    { "::ntk::gl::GL::glGetTexImage",
            NULL, TclGL_glGetTexImageCmd },
    { "::ntk::gl::GL::glGenTextures",
            NULL, TclGL_glGenTexturesCmd },
    { "::ntk::gl::GL::glDeleteTextures",
            NULL, TclGL_glDeleteTexturesCmd },
    { "::ntk::gl::GL::glBindTexture",
            NULL, TclGL_glBindTextureCmd },
    { "::ntk::gl::GL::glPrioritizeTextures",
            NULL, TclGL_glPrioritizeTexturesCmd },
    { "::ntk::gl::GL::glAreTexturesResident",
            NULL, TclGL_glAreTexturesResidentCmd },
    { "::ntk::gl::GL::glIsTexture",
            NULL, TclGL_glIsTextureCmd },
    { "::ntk::gl::GL::glTexSubImage1D",
            NULL, TclGL_glTexSubImage1DCmd },
    { "::ntk::gl::GL::glTexSubImage2D",
            NULL, TclGL_glTexSubImage2DCmd },
    { "::ntk::gl::GL::glCopyTexImage1D",
            NULL, TclGL_glCopyTexImage1DCmd },
    { "::ntk::gl::GL::glCopyTexImage2D",
            NULL, TclGL_glCopyTexImage2DCmd },
    { "::ntk::gl::GL::glCopyTexSubImage1D",
            NULL, TclGL_glCopyTexSubImage1DCmd },
    { "::ntk::gl::GL::glCopyTexSubImage2D",
            NULL, TclGL_glCopyTexSubImage2DCmd },
    { "::ntk::gl::GL::glMap1d",
            NULL, TclGL_glMap1dCmd },
    { "::ntk::gl::GL::glMap1f",
            NULL, TclGL_glMap1fCmd },
    { "::ntk::gl::GL::glMap2d",
            NULL, TclGL_glMap2dCmd },
    { "::ntk::gl::GL::glMap2f",
            NULL, TclGL_glMap2fCmd },
    { "::ntk::gl::GL::glGetMapdv",
            NULL, TclGL_glGetMapdvCmd },
    { "::ntk::gl::GL::glGetMapfv",
            NULL, TclGL_glGetMapfvCmd },
    { "::ntk::gl::GL::glGetMapiv",
            NULL, TclGL_glGetMapivCmd },
    { "::ntk::gl::GL::glEvalCoord1d",
            NULL, TclGL_glEvalCoord1dCmd },
    { "::ntk::gl::GL::glEvalCoord1f",
            NULL, TclGL_glEvalCoord1fCmd },
    { "::ntk::gl::GL::glEvalCoord1dv",
            NULL, TclGL_glEvalCoord1dvCmd },
    { "::ntk::gl::GL::glEvalCoord1fv",
            NULL, TclGL_glEvalCoord1fvCmd },
    { "::ntk::gl::GL::glEvalCoord2d",
            NULL, TclGL_glEvalCoord2dCmd },
    { "::ntk::gl::GL::glEvalCoord2f",
            NULL, TclGL_glEvalCoord2fCmd },
    { "::ntk::gl::GL::glEvalCoord2dv",
            NULL, TclGL_glEvalCoord2dvCmd },
    { "::ntk::gl::GL::glEvalCoord2fv",
            NULL, TclGL_glEvalCoord2fvCmd },
    { "::ntk::gl::GL::glMapGrid1d",
            NULL, TclGL_glMapGrid1dCmd },
    { "::ntk::gl::GL::glMapGrid1f",
            NULL, TclGL_glMapGrid1fCmd },
    { "::ntk::gl::GL::glMapGrid2d",
            NULL, TclGL_glMapGrid2dCmd },
    { "::ntk::gl::GL::glMapGrid2f",
            NULL, TclGL_glMapGrid2fCmd },
    { "::ntk::gl::GL::glEvalPoint1",
            NULL, TclGL_glEvalPoint1Cmd },
    { "::ntk::gl::GL::glEvalPoint2",
            NULL, TclGL_glEvalPoint2Cmd },
    { "::ntk::gl::GL::glEvalMesh1",
            NULL, TclGL_glEvalMesh1Cmd },
    { "::ntk::gl::GL::glEvalMesh2",
            NULL, TclGL_glEvalMesh2Cmd },
    { "::ntk::gl::GL::glFogf",
            NULL, TclGL_glFogfCmd },
    { "::ntk::gl::GL::glFogi",
            NULL, TclGL_glFogiCmd },
    { "::ntk::gl::GL::glFogfv",
            NULL, TclGL_glFogfvCmd },
    { "::ntk::gl::GL::glFogiv",
            NULL, TclGL_glFogivCmd },
    { "::ntk::gl::GL::glFeedbackBuffer",
            NULL, TclGL_glFeedbackBufferCmd },
    { "::ntk::gl::GL::glPassThrough",
            NULL, TclGL_glPassThroughCmd },
    { "::ntk::gl::GL::glSelectBuffer",
            NULL, TclGL_glSelectBufferCmd },
    { "::ntk::gl::GL::glInitNames",
            NULL, TclGL_glInitNamesCmd },
    { "::ntk::gl::GL::glLoadName",
            NULL, TclGL_glLoadNameCmd },
    { "::ntk::gl::GL::glPushName",
            NULL, TclGL_glPushNameCmd },
    { "::ntk::gl::GL::glPopName",
            NULL, TclGL_glPopNameCmd },
    { "::ntk::gl::GL::glDrawRangeElements",
            NULL, TclGL_glDrawRangeElementsCmd },
    { "::ntk::gl::GL::glTexImage3D",
            NULL, TclGL_glTexImage3DCmd },
    { "::ntk::gl::GL::glTexSubImage3D",
            NULL, TclGL_glTexSubImage3DCmd },
    { "::ntk::gl::GL::glCopyTexSubImage3D",
            NULL, TclGL_glCopyTexSubImage3DCmd },
    { "::ntk::gl::GL::glColorTable",
            NULL, TclGL_glColorTableCmd },
    { "::ntk::gl::GL::glColorSubTable",
            NULL, TclGL_glColorSubTableCmd },
    { "::ntk::gl::GL::glColorTableParameteriv",
            NULL, TclGL_glColorTableParameterivCmd },
    { "::ntk::gl::GL::glColorTableParameterfv",
            NULL, TclGL_glColorTableParameterfvCmd },
    { "::ntk::gl::GL::glCopyColorSubTable",
            NULL, TclGL_glCopyColorSubTableCmd },
    { "::ntk::gl::GL::glCopyColorTable",
            NULL, TclGL_glCopyColorTableCmd },
    { "::ntk::gl::GL::glGetColorTable",
            NULL, TclGL_glGetColorTableCmd },
    { "::ntk::gl::GL::glGetColorTableParameterfv",
            NULL, TclGL_glGetColorTableParameterfvCmd },
    { "::ntk::gl::GL::glGetColorTableParameteriv",
            NULL, TclGL_glGetColorTableParameterivCmd },
    { "::ntk::gl::GL::glBlendEquation",
            NULL, TclGL_glBlendEquationCmd },
    { "::ntk::gl::GL::glBlendColor",
            NULL, TclGL_glBlendColorCmd },
    { "::ntk::gl::GL::glHistogram",
            NULL, TclGL_glHistogramCmd },
    { "::ntk::gl::GL::glResetHistogram",
            NULL, TclGL_glResetHistogramCmd },
    { "::ntk::gl::GL::glGetHistogram",
            NULL, TclGL_glGetHistogramCmd },
    { "::ntk::gl::GL::glGetHistogramParameterfv",
            NULL, TclGL_glGetHistogramParameterfvCmd },
    { "::ntk::gl::GL::glGetHistogramParameteriv",
            NULL, TclGL_glGetHistogramParameterivCmd },
    { "::ntk::gl::GL::glMinmax",
            NULL, TclGL_glMinmaxCmd },
    { "::ntk::gl::GL::glResetMinmax",
            NULL, TclGL_glResetMinmaxCmd },
    { "::ntk::gl::GL::glGetMinmax",
            NULL, TclGL_glGetMinmaxCmd },
    { "::ntk::gl::GL::glGetMinmaxParameterfv",
            NULL, TclGL_glGetMinmaxParameterfvCmd },
    { "::ntk::gl::GL::glGetMinmaxParameteriv",
            NULL, TclGL_glGetMinmaxParameterivCmd },
    { "::ntk::gl::GL::glConvolutionFilter1D",
            NULL, TclGL_glConvolutionFilter1DCmd },
    { "::ntk::gl::GL::glConvolutionFilter2D",
            NULL, TclGL_glConvolutionFilter2DCmd },
    { "::ntk::gl::GL::glConvolutionParameterf",
            NULL, TclGL_glConvolutionParameterfCmd },
    { "::ntk::gl::GL::glConvolutionParameterfv",
            NULL, TclGL_glConvolutionParameterfvCmd },
    { "::ntk::gl::GL::glConvolutionParameteri",
            NULL, TclGL_glConvolutionParameteriCmd },
    { "::ntk::gl::GL::glConvolutionParameteriv",
            NULL, TclGL_glConvolutionParameterivCmd },
    { "::ntk::gl::GL::glCopyConvolutionFilter1D",
            NULL, TclGL_glCopyConvolutionFilter1DCmd },
    { "::ntk::gl::GL::glCopyConvolutionFilter2D",
            NULL, TclGL_glCopyConvolutionFilter2DCmd },
    { "::ntk::gl::GL::glGetConvolutionFilter",
            NULL, TclGL_glGetConvolutionFilterCmd },
    { "::ntk::gl::GL::glGetConvolutionParameterfv",
            NULL, TclGL_glGetConvolutionParameterfvCmd },
    { "::ntk::gl::GL::glGetConvolutionParameteriv",
            NULL, TclGL_glGetConvolutionParameterivCmd },
    { "::ntk::gl::GL::glSeparableFilter2D",
            NULL, TclGL_glSeparableFilter2DCmd },
    { "::ntk::gl::GL::glGetSeparableFilter",
            NULL, TclGL_glGetSeparableFilterCmd },
    { "::ntk::gl::GL::glActiveTexture",
            NULL, TclGL_glActiveTextureCmd },
    { "::ntk::gl::GL::glClientActiveTexture",
            NULL, TclGL_glClientActiveTextureCmd },
    { "::ntk::gl::GL::glCompressedTexImage1D",
            NULL, TclGL_glCompressedTexImage1DCmd },
    { "::ntk::gl::GL::glCompressedTexImage2D",
            NULL, TclGL_glCompressedTexImage2DCmd },
    { "::ntk::gl::GL::glCompressedTexImage3D",
            NULL, TclGL_glCompressedTexImage3DCmd },
    { "::ntk::gl::GL::glCompressedTexSubImage1D",
            NULL, TclGL_glCompressedTexSubImage1DCmd },
    { "::ntk::gl::GL::glCompressedTexSubImage2D",
            NULL, TclGL_glCompressedTexSubImage2DCmd },
    { "::ntk::gl::GL::glCompressedTexSubImage3D",
            NULL, TclGL_glCompressedTexSubImage3DCmd },
    { "::ntk::gl::GL::glGetCompressedTexImage",
            NULL, TclGL_glGetCompressedTexImageCmd },
    { "::ntk::gl::GL::glMultiTexCoord1d",
            NULL, TclGL_glMultiTexCoord1dCmd },
    { "::ntk::gl::GL::glMultiTexCoord1dv",
            NULL, TclGL_glMultiTexCoord1dvCmd },
    { "::ntk::gl::GL::glMultiTexCoord1f",
            NULL, TclGL_glMultiTexCoord1fCmd },
    { "::ntk::gl::GL::glMultiTexCoord1fv",
            NULL, TclGL_glMultiTexCoord1fvCmd },
    { "::ntk::gl::GL::glMultiTexCoord1i",
            NULL, TclGL_glMultiTexCoord1iCmd },
    { "::ntk::gl::GL::glMultiTexCoord1iv",
            NULL, TclGL_glMultiTexCoord1ivCmd },
    { "::ntk::gl::GL::glMultiTexCoord1s",
            NULL, TclGL_glMultiTexCoord1sCmd },
    { "::ntk::gl::GL::glMultiTexCoord1sv",
            NULL, TclGL_glMultiTexCoord1svCmd },
    { "::ntk::gl::GL::glMultiTexCoord2d",
            NULL, TclGL_glMultiTexCoord2dCmd },
    { "::ntk::gl::GL::glMultiTexCoord2dv",
            NULL, TclGL_glMultiTexCoord2dvCmd },
    { "::ntk::gl::GL::glMultiTexCoord2f",
            NULL, TclGL_glMultiTexCoord2fCmd },
    { "::ntk::gl::GL::glMultiTexCoord2fv",
            NULL, TclGL_glMultiTexCoord2fvCmd },
    { "::ntk::gl::GL::glMultiTexCoord2i",
            NULL, TclGL_glMultiTexCoord2iCmd },
    { "::ntk::gl::GL::glMultiTexCoord2iv",
            NULL, TclGL_glMultiTexCoord2ivCmd },
    { "::ntk::gl::GL::glMultiTexCoord2s",
            NULL, TclGL_glMultiTexCoord2sCmd },
    { "::ntk::gl::GL::glMultiTexCoord2sv",
            NULL, TclGL_glMultiTexCoord2svCmd },
    { "::ntk::gl::GL::glMultiTexCoord3d",
            NULL, TclGL_glMultiTexCoord3dCmd },
    { "::ntk::gl::GL::glMultiTexCoord3dv",
            NULL, TclGL_glMultiTexCoord3dvCmd },
    { "::ntk::gl::GL::glMultiTexCoord3f",
            NULL, TclGL_glMultiTexCoord3fCmd },
    { "::ntk::gl::GL::glMultiTexCoord3fv",
            NULL, TclGL_glMultiTexCoord3fvCmd },
    { "::ntk::gl::GL::glMultiTexCoord3i",
            NULL, TclGL_glMultiTexCoord3iCmd },
    { "::ntk::gl::GL::glMultiTexCoord3iv",
            NULL, TclGL_glMultiTexCoord3ivCmd },
    { "::ntk::gl::GL::glMultiTexCoord3s",
            NULL, TclGL_glMultiTexCoord3sCmd },
    { "::ntk::gl::GL::glMultiTexCoord3sv",
            NULL, TclGL_glMultiTexCoord3svCmd },
    { "::ntk::gl::GL::glMultiTexCoord4d",
            NULL, TclGL_glMultiTexCoord4dCmd },
    { "::ntk::gl::GL::glMultiTexCoord4dv",
            NULL, TclGL_glMultiTexCoord4dvCmd },
    { "::ntk::gl::GL::glMultiTexCoord4f",
            NULL, TclGL_glMultiTexCoord4fCmd },
    { "::ntk::gl::GL::glMultiTexCoord4fv",
            NULL, TclGL_glMultiTexCoord4fvCmd },
    { "::ntk::gl::GL::glMultiTexCoord4i",
            NULL, TclGL_glMultiTexCoord4iCmd },
    { "::ntk::gl::GL::glMultiTexCoord4iv",
            NULL, TclGL_glMultiTexCoord4ivCmd },
    { "::ntk::gl::GL::glMultiTexCoord4s",
            NULL, TclGL_glMultiTexCoord4sCmd },
    { "::ntk::gl::GL::glMultiTexCoord4sv",
            NULL, TclGL_glMultiTexCoord4svCmd },
    { "::ntk::gl::GL::glLoadTransposeMatrixd",
            NULL, TclGL_glLoadTransposeMatrixdCmd },
    { "::ntk::gl::GL::glLoadTransposeMatrixf",
            NULL, TclGL_glLoadTransposeMatrixfCmd },
    { "::ntk::gl::GL::glMultTransposeMatrixd",
            NULL, TclGL_glMultTransposeMatrixdCmd },
    { "::ntk::gl::GL::glMultTransposeMatrixf",
            NULL, TclGL_glMultTransposeMatrixfCmd },
    { "::ntk::gl::GL::glSampleCoverage",
            NULL, TclGL_glSampleCoverageCmd },
    { "::ntk::gl::GL::glActiveTextureARB",
            NULL, TclGL_glActiveTextureARBCmd },
    { "::ntk::gl::GL::glClientActiveTextureARB",
            NULL, TclGL_glClientActiveTextureARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1dARB",
            NULL, TclGL_glMultiTexCoord1dARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1dvARB",
            NULL, TclGL_glMultiTexCoord1dvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1fARB",
            NULL, TclGL_glMultiTexCoord1fARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1fvARB",
            NULL, TclGL_glMultiTexCoord1fvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1iARB",
            NULL, TclGL_glMultiTexCoord1iARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1ivARB",
            NULL, TclGL_glMultiTexCoord1ivARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1sARB",
            NULL, TclGL_glMultiTexCoord1sARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord1svARB",
            NULL, TclGL_glMultiTexCoord1svARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2dARB",
            NULL, TclGL_glMultiTexCoord2dARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2dvARB",
            NULL, TclGL_glMultiTexCoord2dvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2fARB",
            NULL, TclGL_glMultiTexCoord2fARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2fvARB",
            NULL, TclGL_glMultiTexCoord2fvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2iARB",
            NULL, TclGL_glMultiTexCoord2iARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2ivARB",
            NULL, TclGL_glMultiTexCoord2ivARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2sARB",
            NULL, TclGL_glMultiTexCoord2sARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord2svARB",
            NULL, TclGL_glMultiTexCoord2svARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3dARB",
            NULL, TclGL_glMultiTexCoord3dARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3dvARB",
            NULL, TclGL_glMultiTexCoord3dvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3fARB",
            NULL, TclGL_glMultiTexCoord3fARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3fvARB",
            NULL, TclGL_glMultiTexCoord3fvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3iARB",
            NULL, TclGL_glMultiTexCoord3iARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3ivARB",
            NULL, TclGL_glMultiTexCoord3ivARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3sARB",
            NULL, TclGL_glMultiTexCoord3sARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord3svARB",
            NULL, TclGL_glMultiTexCoord3svARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4dARB",
            NULL, TclGL_glMultiTexCoord4dARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4dvARB",
            NULL, TclGL_glMultiTexCoord4dvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4fARB",
            NULL, TclGL_glMultiTexCoord4fARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4fvARB",
            NULL, TclGL_glMultiTexCoord4fvARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4iARB",
            NULL, TclGL_glMultiTexCoord4iARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4ivARB",
            NULL, TclGL_glMultiTexCoord4ivARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4sARB",
            NULL, TclGL_glMultiTexCoord4sARBCmd },
    { "::ntk::gl::GL::glMultiTexCoord4svARB",
            NULL, TclGL_glMultiTexCoord4svARBCmd },
    { "::ntk::gl::GL::glBlendEquationSeparateATI",
            NULL, TclGL_glBlendEquationSeparateATICmd },
