    objPtr = InitFuncGroup(interp, infoPtr, 0, "Miscellaneous");
    InitFunc(interp, infoPtr, objPtr, 0, 0, "glClearIndex", TCL_GLvoid, 0, "<(GLfloat) c");
    InitFunc(interp, infoPtr, objPtr, 0, 1, "glClearColor", TCL_GLvoid, 3, "<(GLclampf) red <(GLclampf) green <(GLclampf) blue <(GLclampf) alpha");
    InitFunc(interp, infoPtr, objPtr, 0, 2, "glClear", TCL_GLvoid, 0, "<(GLbitfield) mask");
    InitFunc(interp, infoPtr, objPtr, 0, 3, "glIndexMask", TCL_GLvoid, 0, "<(GLuint) mask");
    InitFunc(interp, infoPtr, objPtr, 0, 4, "glColorMask", TCL_GLvoid, 3, "<(GLboolean) red <(GLboolean) green <(GLboolean) blue <(GLboolean) alpha");
    InitFunc(interp, infoPtr, objPtr, 0, 5, "glAlphaFunc", TCL_GLvoid, 1, "<(GLenum) func <(GLclampf) ref");
    InitFunc(interp, infoPtr, objPtr, 0, 6, "glBlendFunc", TCL_GLvoid, 1, "<(GLenum) sfactor <(GLenum) dfactor");
    InitFunc(interp, infoPtr, objPtr, 0, 7, "glLogicOp", TCL_GLvoid, 0, "<(GLenum) opcode");
    InitFunc(interp, infoPtr, objPtr, 0, 8, "glCullFace", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 0, 9, "glFrontFace", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 0, 10, "glPointSize", TCL_GLvoid, 0, "<(GLfloat) size");
    InitFunc(interp, infoPtr, objPtr, 0, 11, "glLineWidth", TCL_GLvoid, 0, "<(GLfloat) width");
    InitFunc(interp, infoPtr, objPtr, 0, 12, "glLineStipple", TCL_GLvoid, 1, "<(GLint) factor <(GLushort) pattern");
    InitFunc(interp, infoPtr, objPtr, 0, 13, "glPolygonMode", TCL_GLvoid, 1, "<(GLenum) face <(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 0, 14, "glPolygonOffset", TCL_GLvoid, 1, "<(GLfloat) factor <(GLfloat) units");
    InitFunc(interp, infoPtr, objPtr, 0, 15, "glPolygonStipple", TCL_GLvoid, 0, "<(const GLubyte*) mask");
    InitFunc(interp, infoPtr, objPtr, 0, 16, "glGetPolygonStipple", TCL_GLvoid, 0, "<(GLubyte*) mask");
    InitFunc(interp, infoPtr, objPtr, 0, 17, "glEdgeFlag", TCL_GLvoid, 0, "<(GLboolean) flag");
    InitFunc(interp, infoPtr, objPtr, 0, 18, "glEdgeFlagv", TCL_GLvoid, 0, "<(const GLboolean*) flag");
    InitFunc(interp, infoPtr, objPtr, 0, 19, "glScissor", TCL_GLvoid, 3, "<(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height");
    InitFunc(interp, infoPtr, objPtr, 0, 20, "glClipPlane", TCL_GLvoid, 1, "<(GLenum) plane <(const GLdouble*) equation");
    InitFunc(interp, infoPtr, objPtr, 0, 21, "glGetClipPlane", TCL_GLvoid, 1, "<(GLenum) plane <(GLdouble*) equation");
    InitFunc(interp, infoPtr, objPtr, 0, 22, "glDrawBuffer", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 0, 23, "glReadBuffer", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 0, 24, "glEnable", TCL_GLvoid, 0, "<(GLenum) cap");
    InitFunc(interp, infoPtr, objPtr, 0, 25, "glDisable", TCL_GLvoid, 0, "<(GLenum) cap");
    InitFunc(interp, infoPtr, objPtr, 0, 26, "glIsEnabled", TCL_GLboolean, 0, "<(GLenum) cap");
    InitFunc(interp, infoPtr, objPtr, 0, 27, "glEnableClientState", TCL_GLvoid, 0, "<(GLenum) cap");
    InitFunc(interp, infoPtr, objPtr, 0, 28, "glDisableClientState", TCL_GLvoid, 0, "<(GLenum) cap");
    InitFunc(interp, infoPtr, objPtr, 0, 29, "glGetBooleanv", TCL_GLvoid, 1, "<(GLenum) pname <(GLboolean*) params");
    InitFunc(interp, infoPtr, objPtr, 0, 30, "glGetDoublev", TCL_GLvoid, 1, "<(GLenum) pname <(GLdouble*) params");
    InitFunc(interp, infoPtr, objPtr, 0, 31, "glGetFloatv", TCL_GLvoid, 1, "<(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 0, 32, "glGetIntegerv", TCL_GLvoid, 1, "<(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 0, 33, "glPushAttrib", TCL_GLvoid, 0, "<(GLbitfield) mask");
    InitFunc(interp, infoPtr, objPtr, 0, 34, "glPopAttrib", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 0, 35, "glPushClientAttrib", TCL_GLvoid, 0, "<(GLbitfield) mask");
    InitFunc(interp, infoPtr, objPtr, 0, 36, "glPopClientAttrib", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 0, 37, "glRenderMode", TCL_GLint, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 0, 38, "glGetError", TCL_GLenum, -1, "");
    InitFunc(interp, infoPtr, objPtr, 0, 39, "glFinish", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 0, 40, "glFlush", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 0, 41, "glHint", TCL_GLvoid, 1, "<(GLenum) target <(GLenum) mode");
    objPtr = InitFuncGroup(interp, infoPtr, 1, "Depth Buffer");
    InitFunc(interp, infoPtr, objPtr, 1, 42, "glClearDepth", TCL_GLvoid, 0, "<(GLclampd) depth");
    InitFunc(interp, infoPtr, objPtr, 1, 43, "glDepthFunc", TCL_GLvoid, 0, "<(GLenum) func");
    InitFunc(interp, infoPtr, objPtr, 1, 44, "glDepthMask", TCL_GLvoid, 0, "<(GLboolean) flag");
    InitFunc(interp, infoPtr, objPtr, 1, 45, "glDepthRange", TCL_GLvoid, 1, "<(GLclampd) near_val <(GLclampd) far_val");
    objPtr = InitFuncGroup(interp, infoPtr, 2, "Accumulation Buffer");
    InitFunc(interp, infoPtr, objPtr, 2, 46, "glClearAccum", TCL_GLvoid, 3, "<(GLfloat) red <(GLfloat) green <(GLfloat) blue <(GLfloat) alpha");
    InitFunc(interp, infoPtr, objPtr, 2, 47, "glAccum", TCL_GLvoid, 1, "<(GLenum) op <(GLfloat) value");
    objPtr = InitFuncGroup(interp, infoPtr, 3, "Transformation");
    InitFunc(interp, infoPtr, objPtr, 3, 48, "glMatrixMode", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 3, 49, "glOrtho", TCL_GLvoid, 5, "<(GLdouble) left <(GLdouble) right <(GLdouble) bottom <(GLdouble) top <(GLdouble) near_val <(GLdouble) far_val");
    InitFunc(interp, infoPtr, objPtr, 3, 50, "glFrustum", TCL_GLvoid, 5, "<(GLdouble) left <(GLdouble) right <(GLdouble) bottom <(GLdouble) top <(GLdouble) near_val <(GLdouble) far_val");
    InitFunc(interp, infoPtr, objPtr, 3, 51, "glViewport", TCL_GLvoid, 3, "<(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height");
    InitFunc(interp, infoPtr, objPtr, 3, 52, "glPushMatrix", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 3, 53, "glPopMatrix", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 3, 54, "glLoadIdentity", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 3, 55, "glLoadMatrixd", TCL_GLvoid, 0, "<(const GLdouble*) m");
    InitFunc(interp, infoPtr, objPtr, 3, 56, "glLoadMatrixf", TCL_GLvoid, 0, "<(const GLfloat*) m");
    InitFunc(interp, infoPtr, objPtr, 3, 57, "glMultMatrixd", TCL_GLvoid, 0, "<(const GLdouble*) m");
    InitFunc(interp, infoPtr, objPtr, 3, 58, "glMultMatrixf", TCL_GLvoid, 0, "<(const GLfloat*) m");
    InitFunc(interp, infoPtr, objPtr, 3, 59, "glRotated", TCL_GLvoid, 3, "<(GLdouble) angle <(GLdouble) x <(GLdouble) y <(GLdouble) z");
    InitFunc(interp, infoPtr, objPtr, 3, 60, "glRotatef", TCL_GLvoid, 3, "<(GLfloat) angle <(GLfloat) x <(GLfloat) y <(GLfloat) z");
    InitFunc(interp, infoPtr, objPtr, 3, 61, "glScaled", TCL_GLvoid, 2, "<(GLdouble) x <(GLdouble) y <(GLdouble) z");
    InitFunc(interp, infoPtr, objPtr, 3, 62, "glScalef", TCL_GLvoid, 2, "<(GLfloat) x <(GLfloat) y <(GLfloat) z");
    InitFunc(interp, infoPtr, objPtr, 3, 63, "glTranslated", TCL_GLvoid, 2, "<(GLdouble) x <(GLdouble) y <(GLdouble) z");
    InitFunc(interp, infoPtr, objPtr, 3, 64, "glTranslatef", TCL_GLvoid, 2, "<(GLfloat) x <(GLfloat) y <(GLfloat) z");
    objPtr = InitFuncGroup(interp, infoPtr, 4, "Display Lists");
    InitFunc(interp, infoPtr, objPtr, 4, 65, "glIsList", TCL_GLboolean, 0, "<(GLuint) list");
    InitFunc(interp, infoPtr, objPtr, 4, 66, "glDeleteLists", TCL_GLvoid, 1, "<(GLuint) list <(GLsizei) range");
    InitFunc(interp, infoPtr, objPtr, 4, 67, "glGenLists", TCL_GLuint, 0, "<(GLsizei) range");
    InitFunc(interp, infoPtr, objPtr, 4, 68, "glNewList", TCL_GLvoid, 1, "<(GLuint) list <(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 4, 69, "glEndList", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 4, 70, "glCallList", TCL_GLvoid, 0, "<(GLuint) list");
    InitFunc(interp, infoPtr, objPtr, 4, 71, "glCallLists", TCL_GLvoid, 2, "<(GLsizei) n <(GLenum) type <(const GLvoid*) lists");
    InitFunc(interp, infoPtr, objPtr, 4, 72, "glListBase", TCL_GLvoid, 0, "<(GLuint) base");
    objPtr = InitFuncGroup(interp, infoPtr, 5, "Drawing Functions");
    InitFunc(interp, infoPtr, objPtr, 5, 73, "glBegin", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 5, 74, "glEnd", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 5, 75, "glVertex2d", TCL_GLvoid, 1, "<(GLdouble) x <(GLdouble) y");
    InitFunc(interp, infoPtr, objPtr, 5, 76, "glVertex2f", TCL_GLvoid, 1, "<(GLfloat) x <(GLfloat) y");
    InitFunc(interp, infoPtr, objPtr, 5, 77, "glVertex2i", TCL_GLvoid, 1, "<(GLint) x <(GLint) y");
    InitFunc(interp, infoPtr, objPtr, 5, 78, "glVertex2s", TCL_GLvoid, 1, "<(GLshort) x <(GLshort) y");
    InitFunc(interp, infoPtr, objPtr, 5, 79, "glVertex3d", TCL_GLvoid, 2, "<(GLdouble) x <(GLdouble) y <(GLdouble) z");
    InitFunc(interp, infoPtr, objPtr, 5, 80, "glVertex3f", TCL_GLvoid, 2, "<(GLfloat) x <(GLfloat) y <(GLfloat) z");
    InitFunc(interp, infoPtr, objPtr, 5, 81, "glVertex3i", TCL_GLvoid, 2, "<(GLint) x <(GLint) y <(GLint) z");
    InitFunc(interp, infoPtr, objPtr, 5, 82, "glVertex3s", TCL_GLvoid, 2, "<(GLshort) x <(GLshort) y <(GLshort) z");
    InitFunc(interp, infoPtr, objPtr, 5, 83, "glVertex4d", TCL_GLvoid, 3, "<(GLdouble) x <(GLdouble) y <(GLdouble) z <(GLdouble) w");
    InitFunc(interp, infoPtr, objPtr, 5, 84, "glVertex4f", TCL_GLvoid, 3, "<(GLfloat) x <(GLfloat) y <(GLfloat) z <(GLfloat) w");
    InitFunc(interp, infoPtr, objPtr, 5, 85, "glVertex4i", TCL_GLvoid, 3, "<(GLint) x <(GLint) y <(GLint) z <(GLint) w");
    InitFunc(interp, infoPtr, objPtr, 5, 86, "glVertex4s", TCL_GLvoid, 3, "<(GLshort) x <(GLshort) y <(GLshort) z <(GLshort) w");
    InitFunc(interp, infoPtr, objPtr, 5, 87, "glVertex2dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 88, "glVertex2fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 89, "glVertex2iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 90, "glVertex2sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 91, "glVertex3dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 92, "glVertex3fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 93, "glVertex3iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 94, "glVertex3sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 95, "glVertex4dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 96, "glVertex4fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 97, "glVertex4iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 98, "glVertex4sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 99, "glNormal3b", TCL_GLvoid, 2, "<(GLbyte) nx <(GLbyte) ny <(GLbyte) nz");
    InitFunc(interp, infoPtr, objPtr, 5, 100, "glNormal3d", TCL_GLvoid, 2, "<(GLdouble) nx <(GLdouble) ny <(GLdouble) nz");
    InitFunc(interp, infoPtr, objPtr, 5, 101, "glNormal3f", TCL_GLvoid, 2, "<(GLfloat) nx <(GLfloat) ny <(GLfloat) nz");
    InitFunc(interp, infoPtr, objPtr, 5, 102, "glNormal3i", TCL_GLvoid, 2, "<(GLint) nx <(GLint) ny <(GLint) nz");
    InitFunc(interp, infoPtr, objPtr, 5, 103, "glNormal3s", TCL_GLvoid, 2, "<(GLshort) nx <(GLshort) ny <(GLshort) nz");
    InitFunc(interp, infoPtr, objPtr, 5, 104, "glNormal3bv", TCL_GLvoid, 0, "<(const GLbyte*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 105, "glNormal3dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 106, "glNormal3fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 107, "glNormal3iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 108, "glNormal3sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 109, "glIndexd", TCL_GLvoid, 0, "<(GLdouble) c");
    InitFunc(interp, infoPtr, objPtr, 5, 110, "glIndexf", TCL_GLvoid, 0, "<(GLfloat) c");
    InitFunc(interp, infoPtr, objPtr, 5, 111, "glIndexi", TCL_GLvoid, 0, "<(GLint) c");
    InitFunc(interp, infoPtr, objPtr, 5, 112, "glIndexs", TCL_GLvoid, 0, "<(GLshort) c");
    InitFunc(interp, infoPtr, objPtr, 5, 113, "glIndexub", TCL_GLvoid, 0, "<(GLubyte) c");
    InitFunc(interp, infoPtr, objPtr, 5, 114, "glIndexdv", TCL_GLvoid, 0, "<(const GLdouble*) c");
    InitFunc(interp, infoPtr, objPtr, 5, 115, "glIndexfv", TCL_GLvoid, 0, "<(const GLfloat*) c");
    InitFunc(interp, infoPtr, objPtr, 5, 116, "glIndexiv", TCL_GLvoid, 0, "<(const GLint*) c");
    InitFunc(interp, infoPtr, objPtr, 5, 117, "glIndexsv", TCL_GLvoid, 0, "<(const GLshort*) c");
    InitFunc(interp, infoPtr, objPtr, 5, 118, "glIndexubv", TCL_GLvoid, 0, "<(const GLubyte*) c");
    InitFunc(interp, infoPtr, objPtr, 5, 119, "glColor3b", TCL_GLvoid, 2, "<(GLbyte) red <(GLbyte) green <(GLbyte) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 120, "glColor3d", TCL_GLvoid, 2, "<(GLdouble) red <(GLdouble) green <(GLdouble) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 121, "glColor3f", TCL_GLvoid, 2, "<(GLfloat) red <(GLfloat) green <(GLfloat) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 122, "glColor3i", TCL_GLvoid, 2, "<(GLint) red <(GLint) green <(GLint) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 123, "glColor3s", TCL_GLvoid, 2, "<(GLshort) red <(GLshort) green <(GLshort) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 124, "glColor3ub", TCL_GLvoid, 2, "<(GLubyte) red <(GLubyte) green <(GLubyte) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 125, "glColor3ui", TCL_GLvoid, 2, "<(GLuint) red <(GLuint) green <(GLuint) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 126, "glColor3us", TCL_GLvoid, 2, "<(GLushort) red <(GLushort) green <(GLushort) blue");
    InitFunc(interp, infoPtr, objPtr, 5, 127, "glColor4b", TCL_GLvoid, 3, "<(GLbyte) red <(GLbyte) green <(GLbyte) blue <(GLbyte) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 128, "glColor4d", TCL_GLvoid, 3, "<(GLdouble) red <(GLdouble) green <(GLdouble) blue <(GLdouble) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 129, "glColor4f", TCL_GLvoid, 3, "<(GLfloat) red <(GLfloat) green <(GLfloat) blue <(GLfloat) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 130, "glColor4i", TCL_GLvoid, 3, "<(GLint) red <(GLint) green <(GLint) blue <(GLint) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 131, "glColor4s", TCL_GLvoid, 3, "<(GLshort) red <(GLshort) green <(GLshort) blue <(GLshort) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 132, "glColor4ub", TCL_GLvoid, 3, "<(GLubyte) red <(GLubyte) green <(GLubyte) blue <(GLubyte) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 133, "glColor4ui", TCL_GLvoid, 3, "<(GLuint) red <(GLuint) green <(GLuint) blue <(GLuint) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 134, "glColor4us", TCL_GLvoid, 3, "<(GLushort) red <(GLushort) green <(GLushort) blue <(GLushort) alpha");
    InitFunc(interp, infoPtr, objPtr, 5, 135, "glColor3bv", TCL_GLvoid, 0, "<(const GLbyte*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 136, "glColor3dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 137, "glColor3fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 138, "glColor3iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 139, "glColor3sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 140, "glColor3ubv", TCL_GLvoid, 0, "<(const GLubyte*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 141, "glColor3uiv", TCL_GLvoid, 0, "<(const GLuint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 142, "glColor3usv", TCL_GLvoid, 0, "<(const GLushort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 143, "glColor4bv", TCL_GLvoid, 0, "<(const GLbyte*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 144, "glColor4dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 145, "glColor4fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 146, "glColor4iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 147, "glColor4sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 148, "glColor4ubv", TCL_GLvoid, 0, "<(const GLubyte*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 149, "glColor4uiv", TCL_GLvoid, 0, "<(const GLuint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 150, "glColor4usv", TCL_GLvoid, 0, "<(const GLushort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 151, "glTexCoord1d", TCL_GLvoid, 0, "<(GLdouble) s");
    InitFunc(interp, infoPtr, objPtr, 5, 152, "glTexCoord1f", TCL_GLvoid, 0, "<(GLfloat) s");
    InitFunc(interp, infoPtr, objPtr, 5, 153, "glTexCoord1i", TCL_GLvoid, 0, "<(GLint) s");
    InitFunc(interp, infoPtr, objPtr, 5, 154, "glTexCoord1s", TCL_GLvoid, 0, "<(GLshort) s");
    InitFunc(interp, infoPtr, objPtr, 5, 155, "glTexCoord2d", TCL_GLvoid, 1, "<(GLdouble) s <(GLdouble) t");
    InitFunc(interp, infoPtr, objPtr, 5, 156, "glTexCoord2f", TCL_GLvoid, 1, "<(GLfloat) s <(GLfloat) t");
    InitFunc(interp, infoPtr, objPtr, 5, 157, "glTexCoord2i", TCL_GLvoid, 1, "<(GLint) s <(GLint) t");
    InitFunc(interp, infoPtr, objPtr, 5, 158, "glTexCoord2s", TCL_GLvoid, 1, "<(GLshort) s <(GLshort) t");
    InitFunc(interp, infoPtr, objPtr, 5, 159, "glTexCoord3d", TCL_GLvoid, 2, "<(GLdouble) s <(GLdouble) t <(GLdouble) r");
    InitFunc(interp, infoPtr, objPtr, 5, 160, "glTexCoord3f", TCL_GLvoid, 2, "<(GLfloat) s <(GLfloat) t <(GLfloat) r");
    InitFunc(interp, infoPtr, objPtr, 5, 161, "glTexCoord3i", TCL_GLvoid, 2, "<(GLint) s <(GLint) t <(GLint) r");
    InitFunc(interp, infoPtr, objPtr, 5, 162, "glTexCoord3s", TCL_GLvoid, 2, "<(GLshort) s <(GLshort) t <(GLshort) r");
    InitFunc(interp, infoPtr, objPtr, 5, 163, "glTexCoord4d", TCL_GLvoid, 3, "<(GLdouble) s <(GLdouble) t <(GLdouble) r <(GLdouble) q");
    InitFunc(interp, infoPtr, objPtr, 5, 164, "glTexCoord4f", TCL_GLvoid, 3, "<(GLfloat) s <(GLfloat) t <(GLfloat) r <(GLfloat) q");
    InitFunc(interp, infoPtr, objPtr, 5, 165, "glTexCoord4i", TCL_GLvoid, 3, "<(GLint) s <(GLint) t <(GLint) r <(GLint) q");
    InitFunc(interp, infoPtr, objPtr, 5, 166, "glTexCoord4s", TCL_GLvoid, 3, "<(GLshort) s <(GLshort) t <(GLshort) r <(GLshort) q");
    InitFunc(interp, infoPtr, objPtr, 5, 167, "glTexCoord1dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 168, "glTexCoord1fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 169, "glTexCoord1iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 170, "glTexCoord1sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 171, "glTexCoord2dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 172, "glTexCoord2fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 173, "glTexCoord2iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 174, "glTexCoord2sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 175, "glTexCoord3dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 176, "glTexCoord3fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 177, "glTexCoord3iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 178, "glTexCoord3sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 179, "glTexCoord4dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 180, "glTexCoord4fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 181, "glTexCoord4iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 182, "glTexCoord4sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 183, "glRasterPos2d", TCL_GLvoid, 1, "<(GLdouble) x <(GLdouble) y");
    InitFunc(interp, infoPtr, objPtr, 5, 184, "glRasterPos2f", TCL_GLvoid, 1, "<(GLfloat) x <(GLfloat) y");
    InitFunc(interp, infoPtr, objPtr, 5, 185, "glRasterPos2i", TCL_GLvoid, 1, "<(GLint) x <(GLint) y");
    InitFunc(interp, infoPtr, objPtr, 5, 186, "glRasterPos2s", TCL_GLvoid, 1, "<(GLshort) x <(GLshort) y");
    InitFunc(interp, infoPtr, objPtr, 5, 187, "glRasterPos3d", TCL_GLvoid, 2, "<(GLdouble) x <(GLdouble) y <(GLdouble) z");
    InitFunc(interp, infoPtr, objPtr, 5, 188, "glRasterPos3f", TCL_GLvoid, 2, "<(GLfloat) x <(GLfloat) y <(GLfloat) z");
    InitFunc(interp, infoPtr, objPtr, 5, 189, "glRasterPos3i", TCL_GLvoid, 2, "<(GLint) x <(GLint) y <(GLint) z");
    InitFunc(interp, infoPtr, objPtr, 5, 190, "glRasterPos3s", TCL_GLvoid, 2, "<(GLshort) x <(GLshort) y <(GLshort) z");
    InitFunc(interp, infoPtr, objPtr, 5, 191, "glRasterPos4d", TCL_GLvoid, 3, "<(GLdouble) x <(GLdouble) y <(GLdouble) z <(GLdouble) w");
    InitFunc(interp, infoPtr, objPtr, 5, 192, "glRasterPos4f", TCL_GLvoid, 3, "<(GLfloat) x <(GLfloat) y <(GLfloat) z <(GLfloat) w");
    InitFunc(interp, infoPtr, objPtr, 5, 193, "glRasterPos4i", TCL_GLvoid, 3, "<(GLint) x <(GLint) y <(GLint) z <(GLint) w");
    InitFunc(interp, infoPtr, objPtr, 5, 194, "glRasterPos4s", TCL_GLvoid, 3, "<(GLshort) x <(GLshort) y <(GLshort) z <(GLshort) w");
    InitFunc(interp, infoPtr, objPtr, 5, 195, "glRasterPos2dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 196, "glRasterPos2fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 197, "glRasterPos2iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 198, "glRasterPos2sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 199, "glRasterPos3dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 200, "glRasterPos3fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 201, "glRasterPos3iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 202, "glRasterPos3sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 203, "glRasterPos4dv", TCL_GLvoid, 0, "<(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 204, "glRasterPos4fv", TCL_GLvoid, 0, "<(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 205, "glRasterPos4iv", TCL_GLvoid, 0, "<(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 206, "glRasterPos4sv", TCL_GLvoid, 0, "<(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 5, 207, "glRectd", TCL_GLvoid, 3, "<(GLdouble) x1 <(GLdouble) y1 <(GLdouble) x2 <(GLdouble) y2");
    InitFunc(interp, infoPtr, objPtr, 5, 208, "glRectf", TCL_GLvoid, 3, "<(GLfloat) x1 <(GLfloat) y1 <(GLfloat) x2 <(GLfloat) y2");
    InitFunc(interp, infoPtr, objPtr, 5, 209, "glRecti", TCL_GLvoid, 3, "<(GLint) x1 <(GLint) y1 <(GLint) x2 <(GLint) y2");
    InitFunc(interp, infoPtr, objPtr, 5, 210, "glRects", TCL_GLvoid, 3, "<(GLshort) x1 <(GLshort) y1 <(GLshort) x2 <(GLshort) y2");
    InitFunc(interp, infoPtr, objPtr, 5, 211, "glRectdv", TCL_GLvoid, 1, "<(const GLdouble*) v1 <(const GLdouble*) v2");
    InitFunc(interp, infoPtr, objPtr, 5, 212, "glRectfv", TCL_GLvoid, 1, "<(const GLfloat*) v1 <(const GLfloat*) v2");
    InitFunc(interp, infoPtr, objPtr, 5, 213, "glRectiv", TCL_GLvoid, 1, "<(const GLint*) v1 <(const GLint*) v2");
    InitFunc(interp, infoPtr, objPtr, 5, 214, "glRectsv", TCL_GLvoid, 1, "<(const GLshort*) v1 <(const GLshort*) v2");
    objPtr = InitFuncGroup(interp, infoPtr, 6, "Vertex Arrays  (1.1)");
    InitFunc(interp, infoPtr, objPtr, 6, 215, "glVertexPointer", TCL_GLvoid, 3, "<(GLint) size <(GLenum) type <(GLsizei) stride <(const GLvoid*) ptr");
    InitFunc(interp, infoPtr, objPtr, 6, 216, "glNormalPointer", TCL_GLvoid, 2, "<(GLenum) type <(GLsizei) stride <(const GLvoid*) ptr");
    InitFunc(interp, infoPtr, objPtr, 6, 217, "glColorPointer", TCL_GLvoid, 3, "<(GLint) size <(GLenum) type <(GLsizei) stride <(const GLvoid*) ptr");
    InitFunc(interp, infoPtr, objPtr, 6, 218, "glIndexPointer", TCL_GLvoid, 2, "<(GLenum) type <(GLsizei) stride <(const GLvoid*) ptr");
    InitFunc(interp, infoPtr, objPtr, 6, 219, "glTexCoordPointer", TCL_GLvoid, 3, "<(GLint) size <(GLenum) type <(GLsizei) stride <(const GLvoid*) ptr");
    InitFunc(interp, infoPtr, objPtr, 6, 220, "glEdgeFlagPointer", TCL_GLvoid, 1, "<(GLsizei) stride <(const GLvoid*) ptr");
    InitFunc(interp, infoPtr, objPtr, 6, 221, "glGetPointerv", TCL_GLvoid, 1, "<(GLenum) pname <(GLvoid**) params");
    InitFunc(interp, infoPtr, objPtr, 6, 222, "glArrayElement", TCL_GLvoid, 0, "<(GLint) i");
    InitFunc(interp, infoPtr, objPtr, 6, 223, "glDrawArrays", TCL_GLvoid, 2, "<(GLenum) mode <(GLint) first <(GLsizei) count");
    InitFunc(interp, infoPtr, objPtr, 6, 224, "glDrawElements", TCL_GLvoid, 3, "<(GLenum) mode <(GLsizei) count <(GLenum) type <(const GLvoid*) indices");
    InitFunc(interp, infoPtr, objPtr, 6, 225, "glInterleavedArrays", TCL_GLvoid, 2, "<(GLenum) format <(GLsizei) stride <(const GLvoid*) pointer");
    objPtr = InitFuncGroup(interp, infoPtr, 7, "Lighting");
    InitFunc(interp, infoPtr, objPtr, 7, 226, "glShadeModel", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 7, 227, "glLightf", TCL_GLvoid, 2, "<(GLenum) light <(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 7, 228, "glLighti", TCL_GLvoid, 2, "<(GLenum) light <(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 7, 229, "glLightfv", TCL_GLvoid, 2, "<(GLenum) light <(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 230, "glLightiv", TCL_GLvoid, 2, "<(GLenum) light <(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 231, "glGetLightfv", TCL_GLvoid, 2, "<(GLenum) light <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 232, "glGetLightiv", TCL_GLvoid, 2, "<(GLenum) light <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 233, "glLightModelf", TCL_GLvoid, 1, "<(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 7, 234, "glLightModeli", TCL_GLvoid, 1, "<(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 7, 235, "glLightModelfv", TCL_GLvoid, 1, "<(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 236, "glLightModeliv", TCL_GLvoid, 1, "<(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 237, "glMaterialf", TCL_GLvoid, 2, "<(GLenum) face <(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 7, 238, "glMateriali", TCL_GLvoid, 2, "<(GLenum) face <(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 7, 239, "glMaterialfv", TCL_GLvoid, 2, "<(GLenum) face <(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 240, "glMaterialiv", TCL_GLvoid, 2, "<(GLenum) face <(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 241, "glGetMaterialfv", TCL_GLvoid, 2, "<(GLenum) face <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 242, "glGetMaterialiv", TCL_GLvoid, 2, "<(GLenum) face <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 7, 243, "glColorMaterial", TCL_GLvoid, 1, "<(GLenum) face <(GLenum) mode");
    objPtr = InitFuncGroup(interp, infoPtr, 8, "Raster functions");
    InitFunc(interp, infoPtr, objPtr, 8, 244, "glPixelZoom", TCL_GLvoid, 1, "<(GLfloat) xfactor <(GLfloat) yfactor");
    InitFunc(interp, infoPtr, objPtr, 8, 245, "glPixelStoref", TCL_GLvoid, 1, "<(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 8, 246, "glPixelStorei", TCL_GLvoid, 1, "<(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 8, 247, "glPixelTransferf", TCL_GLvoid, 1, "<(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 8, 248, "glPixelTransferi", TCL_GLvoid, 1, "<(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 8, 249, "glPixelMapfv", TCL_GLvoid, 2, "<(GLenum) map <(GLsizei) mapsize <(const GLfloat*) values");
    InitFunc(interp, infoPtr, objPtr, 8, 250, "glPixelMapuiv", TCL_GLvoid, 2, "<(GLenum) map <(GLsizei) mapsize <(const GLuint*) values");
    InitFunc(interp, infoPtr, objPtr, 8, 251, "glPixelMapusv", TCL_GLvoid, 2, "<(GLenum) map <(GLsizei) mapsize <(const GLushort*) values");
    InitFunc(interp, infoPtr, objPtr, 8, 252, "glGetPixelMapfv", TCL_GLvoid, 1, "<(GLenum) map <(GLfloat*) values");
    InitFunc(interp, infoPtr, objPtr, 8, 253, "glGetPixelMapuiv", TCL_GLvoid, 1, "<(GLenum) map <(GLuint*) values");
    InitFunc(interp, infoPtr, objPtr, 8, 254, "glGetPixelMapusv", TCL_GLvoid, 1, "<(GLenum) map <(GLushort*) values");
    InitFunc(interp, infoPtr, objPtr, 8, 255, "glBitmap", TCL_GLvoid, 6, "<(GLsizei) width <(GLsizei) height <(GLfloat) xorig <(GLfloat) yorig <(GLfloat) xmove <(GLfloat) ymove <(const GLubyte*) bitmap");
    InitFunc(interp, infoPtr, objPtr, 8, 256, "glReadPixels", TCL_GLvoid, 6, "<(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height <(GLenum) format <(GLenum) type <(GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 8, 257, "glDrawPixels", TCL_GLvoid, 4, "<(GLsizei) width <(GLsizei) height <(GLenum) format <(GLenum) type <(const GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 8, 258, "glCopyPixels", TCL_GLvoid, 4, "<(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height <(GLenum) type");
    objPtr = InitFuncGroup(interp, infoPtr, 9, "Stenciling");
    InitFunc(interp, infoPtr, objPtr, 9, 259, "glStencilFunc", TCL_GLvoid, 2, "<(GLenum) func <(GLint) ref <(GLuint) mask");
    InitFunc(interp, infoPtr, objPtr, 9, 260, "glStencilMask", TCL_GLvoid, 0, "<(GLuint) mask");
    InitFunc(interp, infoPtr, objPtr, 9, 261, "glStencilOp", TCL_GLvoid, 2, "<(GLenum) fail <(GLenum) zfail <(GLenum) zpass");
    InitFunc(interp, infoPtr, objPtr, 9, 262, "glClearStencil", TCL_GLvoid, 0, "<(GLint) s");
    objPtr = InitFuncGroup(interp, infoPtr, 10, "Texture mapping");
    InitFunc(interp, infoPtr, objPtr, 10, 263, "glTexGend", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(GLdouble) param");
    InitFunc(interp, infoPtr, objPtr, 10, 264, "glTexGenf", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 10, 265, "glTexGeni", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 10, 266, "glTexGendv", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(const GLdouble*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 267, "glTexGenfv", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 268, "glTexGeniv", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 269, "glGetTexGendv", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(GLdouble*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 270, "glGetTexGenfv", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 271, "glGetTexGeniv", TCL_GLvoid, 2, "<(GLenum) coord <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 272, "glTexEnvf", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 10, 273, "glTexEnvi", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 10, 274, "glTexEnvfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 275, "glTexEnviv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 276, "glGetTexEnvfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 277, "glGetTexEnviv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 278, "glTexParameterf", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 10, 279, "glTexParameteri", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 10, 280, "glTexParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 281, "glTexParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 282, "glGetTexParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 283, "glGetTexParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 284, "glGetTexLevelParameterfv", TCL_GLvoid, 3, "<(GLenum) target <(GLint) level <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 285, "glGetTexLevelParameteriv", TCL_GLvoid, 3, "<(GLenum) target <(GLint) level <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 10, 286, "glTexImage1D", TCL_GLvoid, 7, "<(GLenum) target <(GLint) level <(GLint) internalFormat <(GLsizei) width <(GLint) border <(GLenum) format <(GLenum) type <(const GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 10, 287, "glTexImage2D", TCL_GLvoid, 8, "<(GLenum) target <(GLint) level <(GLint) internalFormat <(GLsizei) width <(GLsizei) height <(GLint) border <(GLenum) format <(GLenum) type <(const GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 10, 288, "glGetTexImage", TCL_GLvoid, 4, "<(GLenum) target <(GLint) level <(GLenum) format <(GLenum) type <(GLvoid*) pixels");
    objPtr = InitFuncGroup(interp, infoPtr, 11, "1.1 functions");
    InitFunc(interp, infoPtr, objPtr, 11, 289, "glGenTextures", TCL_GLvoid, 1, "<(GLsizei) n <(GLuint*) textures");
    InitFunc(interp, infoPtr, objPtr, 11, 290, "glDeleteTextures", TCL_GLvoid, 1, "<(GLsizei) n <(const GLuint*) textures");
    InitFunc(interp, infoPtr, objPtr, 11, 291, "glBindTexture", TCL_GLvoid, 1, "<(GLenum) target <(GLuint) texture");
    InitFunc(interp, infoPtr, objPtr, 11, 292, "glPrioritizeTextures", TCL_GLvoid, 2, "<(GLsizei) n <(const GLuint*) textures <(const GLclampf*) priorities");
    InitFunc(interp, infoPtr, objPtr, 11, 293, "glIsTexture", TCL_GLboolean, 0, "<(GLuint) texture");
    InitFunc(interp, infoPtr, objPtr, 11, 294, "glTexSubImage1D", TCL_GLvoid, 6, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLsizei) width <(GLenum) format <(GLenum) type <(const GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 11, 295, "glTexSubImage2D", TCL_GLvoid, 8, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLint) yoffset <(GLsizei) width <(GLsizei) height <(GLenum) format <(GLenum) type <(const GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 11, 296, "glCopyTexImage1D", TCL_GLvoid, 6, "<(GLenum) target <(GLint) level <(GLenum) internalformat <(GLint) x <(GLint) y <(GLsizei) width <(GLint) border");
    InitFunc(interp, infoPtr, objPtr, 11, 297, "glCopyTexImage2D", TCL_GLvoid, 7, "<(GLenum) target <(GLint) level <(GLenum) internalformat <(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height <(GLint) border");
    InitFunc(interp, infoPtr, objPtr, 11, 298, "glCopyTexSubImage1D", TCL_GLvoid, 5, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLint) x <(GLint) y <(GLsizei) width");
    InitFunc(interp, infoPtr, objPtr, 11, 299, "glCopyTexSubImage2D", TCL_GLvoid, 7, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLint) yoffset <(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height");
    objPtr = InitFuncGroup(interp, infoPtr, 12, "Evaluators");
    InitFunc(interp, infoPtr, objPtr, 12, 300, "glMap1d", TCL_GLvoid, 5, "<(GLenum) target <(GLdouble) u1 <(GLdouble) u2 <(GLint) stride <(GLint) order <(const GLdouble*) points");
    InitFunc(interp, infoPtr, objPtr, 12, 301, "glMap1f", TCL_GLvoid, 5, "<(GLenum) target <(GLfloat) u1 <(GLfloat) u2 <(GLint) stride <(GLint) order <(const GLfloat*) points");
    InitFunc(interp, infoPtr, objPtr, 12, 302, "glMap2d", TCL_GLvoid, 9, "<(GLenum) target <(GLdouble) u1 <(GLdouble) u2 <(GLint) ustride <(GLint) uorder <(GLdouble) v1 <(GLdouble) v2 <(GLint) vstride <(GLint) vorder <(const GLdouble*) points");
    InitFunc(interp, infoPtr, objPtr, 12, 303, "glMap2f", TCL_GLvoid, 9, "<(GLenum) target <(GLfloat) u1 <(GLfloat) u2 <(GLint) ustride <(GLint) uorder <(GLfloat) v1 <(GLfloat) v2 <(GLint) vstride <(GLint) vorder <(const GLfloat*) points");
    InitFunc(interp, infoPtr, objPtr, 12, 304, "glGetMapdv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) query <(GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 12, 305, "glGetMapfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) query <(GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 12, 306, "glGetMapiv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) query <(GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 12, 307, "glEvalCoord1d", TCL_GLvoid, 0, "<(GLdouble) u");
    InitFunc(interp, infoPtr, objPtr, 12, 308, "glEvalCoord1f", TCL_GLvoid, 0, "<(GLfloat) u");
    InitFunc(interp, infoPtr, objPtr, 12, 309, "glEvalCoord1dv", TCL_GLvoid, 0, "<(const GLdouble*) u");
    InitFunc(interp, infoPtr, objPtr, 12, 310, "glEvalCoord1fv", TCL_GLvoid, 0, "<(const GLfloat*) u");
    InitFunc(interp, infoPtr, objPtr, 12, 311, "glEvalCoord2d", TCL_GLvoid, 1, "<(GLdouble) u <(GLdouble) v");
    InitFunc(interp, infoPtr, objPtr, 12, 312, "glEvalCoord2f", TCL_GLvoid, 1, "<(GLfloat) u <(GLfloat) v");
    InitFunc(interp, infoPtr, objPtr, 12, 313, "glEvalCoord2dv", TCL_GLvoid, 0, "<(const GLdouble*) u");
    InitFunc(interp, infoPtr, objPtr, 12, 314, "glEvalCoord2fv", TCL_GLvoid, 0, "<(const GLfloat*) u");
    InitFunc(interp, infoPtr, objPtr, 12, 315, "glMapGrid1d", TCL_GLvoid, 2, "<(GLint) un <(GLdouble) u1 <(GLdouble) u2");
    InitFunc(interp, infoPtr, objPtr, 12, 316, "glMapGrid1f", TCL_GLvoid, 2, "<(GLint) un <(GLfloat) u1 <(GLfloat) u2");
    InitFunc(interp, infoPtr, objPtr, 12, 317, "glMapGrid2d", TCL_GLvoid, 5, "<(GLint) un <(GLdouble) u1 <(GLdouble) u2 <(GLint) vn <(GLdouble) v1 <(GLdouble) v2");
    InitFunc(interp, infoPtr, objPtr, 12, 318, "glMapGrid2f", TCL_GLvoid, 5, "<(GLint) un <(GLfloat) u1 <(GLfloat) u2 <(GLint) vn <(GLfloat) v1 <(GLfloat) v2");
    InitFunc(interp, infoPtr, objPtr, 12, 319, "glEvalPoint1", TCL_GLvoid, 0, "<(GLint) i");
    InitFunc(interp, infoPtr, objPtr, 12, 320, "glEvalPoint2", TCL_GLvoid, 1, "<(GLint) i <(GLint) j");
    InitFunc(interp, infoPtr, objPtr, 12, 321, "glEvalMesh1", TCL_GLvoid, 2, "<(GLenum) mode <(GLint) i1 <(GLint) i2");
    InitFunc(interp, infoPtr, objPtr, 12, 322, "glEvalMesh2", TCL_GLvoid, 4, "<(GLenum) mode <(GLint) i1 <(GLint) i2 <(GLint) j1 <(GLint) j2");
    objPtr = InitFuncGroup(interp, infoPtr, 13, "Fog");
    InitFunc(interp, infoPtr, objPtr, 13, 323, "glFogf", TCL_GLvoid, 1, "<(GLenum) pname <(GLfloat) param");
    InitFunc(interp, infoPtr, objPtr, 13, 324, "glFogi", TCL_GLvoid, 1, "<(GLenum) pname <(GLint) param");
    InitFunc(interp, infoPtr, objPtr, 13, 325, "glFogfv", TCL_GLvoid, 1, "<(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 13, 326, "glFogiv", TCL_GLvoid, 1, "<(GLenum) pname <(const GLint*) params");
    objPtr = InitFuncGroup(interp, infoPtr, 14, "Selection and Feedback");
    InitFunc(interp, infoPtr, objPtr, 14, 327, "glFeedbackBuffer", TCL_GLvoid, 2, "<(GLsizei) size <(GLenum) type <(GLfloat*) buffer");
    InitFunc(interp, infoPtr, objPtr, 14, 328, "glPassThrough", TCL_GLvoid, 0, "<(GLfloat) token");
    InitFunc(interp, infoPtr, objPtr, 14, 329, "glSelectBuffer", TCL_GLvoid, 1, "<(GLsizei) size <(GLuint*) buffer");
    InitFunc(interp, infoPtr, objPtr, 14, 330, "glInitNames", TCL_GLvoid, -1, "");
    InitFunc(interp, infoPtr, objPtr, 14, 331, "glLoadName", TCL_GLvoid, 0, "<(GLuint) name");
    InitFunc(interp, infoPtr, objPtr, 14, 332, "glPushName", TCL_GLvoid, 0, "<(GLuint) name");
    InitFunc(interp, infoPtr, objPtr, 14, 333, "glPopName", TCL_GLvoid, -1, "");
    objPtr = InitFuncGroup(interp, infoPtr, 15, "OpenGL 1.2");
    InitFunc(interp, infoPtr, objPtr, 15, 334, "glDrawRangeElements", TCL_GLvoid, 5, "<(GLenum) mode <(GLuint) start <(GLuint) end <(GLsizei) count <(GLenum) type <(const GLvoid*) indices");
    InitFunc(interp, infoPtr, objPtr, 15, 335, "glTexImage3D", TCL_GLvoid, 9, "<(GLenum) target <(GLint) level <(GLint) internalFormat <(GLsizei) width <(GLsizei) height <(GLsizei) depth <(GLint) border <(GLenum) format <(GLenum) type <(const GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 15, 336, "glTexSubImage3D", TCL_GLvoid, 10, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLint) yoffset <(GLint) zoffset <(GLsizei) width <(GLsizei) height <(GLsizei) depth <(GLenum) format <(GLenum) type <(const GLvoid*) pixels");
    InitFunc(interp, infoPtr, objPtr, 15, 337, "glCopyTexSubImage3D", TCL_GLvoid, 8, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLint) yoffset <(GLint) zoffset <(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height");
    objPtr = InitFuncGroup(interp, infoPtr, 16, "GL_ARB_imaging");
    InitFunc(interp, infoPtr, objPtr, 16, 338, "glColorTable", TCL_GLvoid, 5, "<(GLenum) target <(GLenum) internalformat <(GLsizei) width <(GLenum) format <(GLenum) type <(const GLvoid*) table");
    InitFunc(interp, infoPtr, objPtr, 16, 339, "glColorSubTable", TCL_GLvoid, 5, "<(GLenum) target <(GLsizei) start <(GLsizei) count <(GLenum) format <(GLenum) type <(const GLvoid*) data");
    InitFunc(interp, infoPtr, objPtr, 16, 340, "glColorTableParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 341, "glColorTableParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 342, "glCopyColorSubTable", TCL_GLvoid, 4, "<(GLenum) target <(GLsizei) start <(GLint) x <(GLint) y <(GLsizei) width");
    InitFunc(interp, infoPtr, objPtr, 16, 343, "glCopyColorTable", TCL_GLvoid, 4, "<(GLenum) target <(GLenum) internalformat <(GLint) x <(GLint) y <(GLsizei) width");
    InitFunc(interp, infoPtr, objPtr, 16, 344, "glGetColorTable", TCL_GLvoid, 3, "<(GLenum) target <(GLenum) format <(GLenum) type <(GLvoid*) table");
    InitFunc(interp, infoPtr, objPtr, 16, 345, "glGetColorTableParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 346, "glGetColorTableParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 347, "glBlendEquation", TCL_GLvoid, 0, "<(GLenum) mode");
    InitFunc(interp, infoPtr, objPtr, 16, 348, "glBlendColor", TCL_GLvoid, 3, "<(GLclampf) red <(GLclampf) green <(GLclampf) blue <(GLclampf) alpha");
    InitFunc(interp, infoPtr, objPtr, 16, 349, "glHistogram", TCL_GLvoid, 3, "<(GLenum) target <(GLsizei) width <(GLenum) internalformat <(GLboolean) sink");
    InitFunc(interp, infoPtr, objPtr, 16, 350, "glResetHistogram", TCL_GLvoid, 0, "<(GLenum) target");
    InitFunc(interp, infoPtr, objPtr, 16, 351, "glGetHistogram", TCL_GLvoid, 4, "<(GLenum) target <(GLboolean) reset <(GLenum) format <(GLenum) type <(GLvoid*) values");
    InitFunc(interp, infoPtr, objPtr, 16, 352, "glGetHistogramParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 353, "glGetHistogramParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 354, "glMinmax", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) internalformat <(GLboolean) sink");
    InitFunc(interp, infoPtr, objPtr, 16, 355, "glResetMinmax", TCL_GLvoid, 0, "<(GLenum) target");
    InitFunc(interp, infoPtr, objPtr, 16, 356, "glGetMinmax", TCL_GLvoid, 4, "<(GLenum) target <(GLboolean) reset <(GLenum) format <(GLenum) types <(GLvoid*) values");
    InitFunc(interp, infoPtr, objPtr, 16, 357, "glGetMinmaxParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 358, "glGetMinmaxParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 359, "glConvolutionFilter1D", TCL_GLvoid, 5, "<(GLenum) target <(GLenum) internalformat <(GLsizei) width <(GLenum) format <(GLenum) type <(const GLvoid*) image");
    InitFunc(interp, infoPtr, objPtr, 16, 360, "glConvolutionFilter2D", TCL_GLvoid, 6, "<(GLenum) target <(GLenum) internalformat <(GLsizei) width <(GLsizei) height <(GLenum) format <(GLenum) type <(const GLvoid*) image");
    InitFunc(interp, infoPtr, objPtr, 16, 361, "glConvolutionParameterf", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat) params");
    InitFunc(interp, infoPtr, objPtr, 16, 362, "glConvolutionParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 363, "glConvolutionParameteri", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint) params");
    InitFunc(interp, infoPtr, objPtr, 16, 364, "glConvolutionParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(const GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 365, "glCopyConvolutionFilter1D", TCL_GLvoid, 4, "<(GLenum) target <(GLenum) internalformat <(GLint) x <(GLint) y <(GLsizei) width");
    InitFunc(interp, infoPtr, objPtr, 16, 366, "glCopyConvolutionFilter2D", TCL_GLvoid, 5, "<(GLenum) target <(GLenum) internalformat <(GLint) x <(GLint) y <(GLsizei) width <(GLsizei) height");
    InitFunc(interp, infoPtr, objPtr, 16, 367, "glGetConvolutionFilter", TCL_GLvoid, 3, "<(GLenum) target <(GLenum) format <(GLenum) type <(GLvoid*) image");
    InitFunc(interp, infoPtr, objPtr, 16, 368, "glGetConvolutionParameterfv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLfloat*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 369, "glGetConvolutionParameteriv", TCL_GLvoid, 2, "<(GLenum) target <(GLenum) pname <(GLint*) params");
    InitFunc(interp, infoPtr, objPtr, 16, 370, "glSeparableFilter2D", TCL_GLvoid, 7, "<(GLenum) target <(GLenum) internalformat <(GLsizei) width <(GLsizei) height <(GLenum) format <(GLenum) type <(const GLvoid*) row <(const GLvoid*) column");
    InitFunc(interp, infoPtr, objPtr, 16, 371, "glGetSeparableFilter", TCL_GLvoid, 5, "<(GLenum) target <(GLenum) format <(GLenum) type <(GLvoid*) row <(GLvoid*) column <(GLvoid*) span");
    objPtr = InitFuncGroup(interp, infoPtr, 17, "texture_border_clamp");
    InitFunc(interp, infoPtr, objPtr, 17, 372, "glActiveTexture", TCL_GLvoid, 0, "<(GLenum) texture");
    InitFunc(interp, infoPtr, objPtr, 17, 373, "glClientActiveTexture", TCL_GLvoid, 0, "<(GLenum) texture");
    InitFunc(interp, infoPtr, objPtr, 17, 374, "glCompressedTexImage1D", TCL_GLvoid, 6, "<(GLenum) target <(GLint) level <(GLenum) internalformat <(GLsizei) width <(GLint) border <(GLsizei) imageSize <(const GLvoid*) data");
    InitFunc(interp, infoPtr, objPtr, 17, 375, "glCompressedTexImage2D", TCL_GLvoid, 7, "<(GLenum) target <(GLint) level <(GLenum) internalformat <(GLsizei) width <(GLsizei) height <(GLint) border <(GLsizei) imageSize <(const GLvoid*) data");
    InitFunc(interp, infoPtr, objPtr, 17, 376, "glCompressedTexImage3D", TCL_GLvoid, 8, "<(GLenum) target <(GLint) level <(GLenum) internalformat <(GLsizei) width <(GLsizei) height <(GLsizei) depth <(GLint) border <(GLsizei) imageSize <(const GLvoid*) data");
    InitFunc(interp, infoPtr, objPtr, 17, 377, "glCompressedTexSubImage1D", TCL_GLvoid, 6, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLsizei) width <(GLenum) format <(GLsizei) imageSize <(const GLvoid*) data");
    InitFunc(interp, infoPtr, objPtr, 17, 378, "glCompressedTexSubImage2D", TCL_GLvoid, 8, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLint) yoffset <(GLsizei) width <(GLsizei) height <(GLenum) format <(GLsizei) imageSize <(const GLvoid*) data");
    InitFunc(interp, infoPtr, objPtr, 17, 379, "glCompressedTexSubImage3D", TCL_GLvoid, 10, "<(GLenum) target <(GLint) level <(GLint) xoffset <(GLint) yoffset <(GLint) zoffset <(GLsizei) width <(GLsizei) height <(GLsizei) depth <(GLenum) format <(GLsizei) imageSize <(const GLvoid*) data");
    InitFunc(interp, infoPtr, objPtr, 17, 380, "glGetCompressedTexImage", TCL_GLvoid, 2, "<(GLenum) target <(GLint) lod <(GLvoid*) img");
    InitFunc(interp, infoPtr, objPtr, 17, 381, "glMultiTexCoord1d", TCL_GLvoid, 1, "<(GLenum) target <(GLdouble) s");
    InitFunc(interp, infoPtr, objPtr, 17, 382, "glMultiTexCoord1dv", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 383, "glMultiTexCoord1f", TCL_GLvoid, 1, "<(GLenum) target <(GLfloat) s");
    InitFunc(interp, infoPtr, objPtr, 17, 384, "glMultiTexCoord1fv", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 385, "glMultiTexCoord1i", TCL_GLvoid, 1, "<(GLenum) target <(GLint) s");
    InitFunc(interp, infoPtr, objPtr, 17, 386, "glMultiTexCoord1iv", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 387, "glMultiTexCoord1s", TCL_GLvoid, 1, "<(GLenum) target <(GLshort) s");
    InitFunc(interp, infoPtr, objPtr, 17, 388, "glMultiTexCoord1sv", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 389, "glMultiTexCoord2d", TCL_GLvoid, 2, "<(GLenum) target <(GLdouble) s <(GLdouble) t");
    InitFunc(interp, infoPtr, objPtr, 17, 390, "glMultiTexCoord2dv", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 391, "glMultiTexCoord2f", TCL_GLvoid, 2, "<(GLenum) target <(GLfloat) s <(GLfloat) t");
    InitFunc(interp, infoPtr, objPtr, 17, 392, "glMultiTexCoord2fv", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 393, "glMultiTexCoord2i", TCL_GLvoid, 2, "<(GLenum) target <(GLint) s <(GLint) t");
    InitFunc(interp, infoPtr, objPtr, 17, 394, "glMultiTexCoord2iv", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 395, "glMultiTexCoord2s", TCL_GLvoid, 2, "<(GLenum) target <(GLshort) s <(GLshort) t");
    InitFunc(interp, infoPtr, objPtr, 17, 396, "glMultiTexCoord2sv", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 397, "glMultiTexCoord3d", TCL_GLvoid, 3, "<(GLenum) target <(GLdouble) s <(GLdouble) t <(GLdouble) r");
    InitFunc(interp, infoPtr, objPtr, 17, 398, "glMultiTexCoord3dv", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 399, "glMultiTexCoord3f", TCL_GLvoid, 3, "<(GLenum) target <(GLfloat) s <(GLfloat) t <(GLfloat) r");
    InitFunc(interp, infoPtr, objPtr, 17, 400, "glMultiTexCoord3fv", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 401, "glMultiTexCoord3i", TCL_GLvoid, 3, "<(GLenum) target <(GLint) s <(GLint) t <(GLint) r");
    InitFunc(interp, infoPtr, objPtr, 17, 402, "glMultiTexCoord3iv", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 403, "glMultiTexCoord3s", TCL_GLvoid, 3, "<(GLenum) target <(GLshort) s <(GLshort) t <(GLshort) r");
    InitFunc(interp, infoPtr, objPtr, 17, 404, "glMultiTexCoord3sv", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 405, "glMultiTexCoord4d", TCL_GLvoid, 4, "<(GLenum) target <(GLdouble) s <(GLdouble) t <(GLdouble) r <(GLdouble) q");
    InitFunc(interp, infoPtr, objPtr, 17, 406, "glMultiTexCoord4dv", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 407, "glMultiTexCoord4f", TCL_GLvoid, 4, "<(GLenum) target <(GLfloat) s <(GLfloat) t <(GLfloat) r <(GLfloat) q");
    InitFunc(interp, infoPtr, objPtr, 17, 408, "glMultiTexCoord4fv", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 409, "glMultiTexCoord4i", TCL_GLvoid, 4, "<(GLenum) target <(GLint) s <(GLint) t <(GLint) r <(GLint) q");
    InitFunc(interp, infoPtr, objPtr, 17, 410, "glMultiTexCoord4iv", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 411, "glMultiTexCoord4s", TCL_GLvoid, 4, "<(GLenum) target <(GLshort) s <(GLshort) t <(GLshort) r <(GLshort) q");
    InitFunc(interp, infoPtr, objPtr, 17, 412, "glMultiTexCoord4sv", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 17, 413, "glLoadTransposeMatrixd", TCL_GLvoid, 0, "<(const GLdouble) m[16]");
    InitFunc(interp, infoPtr, objPtr, 17, 414, "glLoadTransposeMatrixf", TCL_GLvoid, 0, "<(const GLfloat) m[16]");
    InitFunc(interp, infoPtr, objPtr, 17, 415, "glMultTransposeMatrixd", TCL_GLvoid, 0, "<(const GLdouble) m[16]");
    InitFunc(interp, infoPtr, objPtr, 17, 416, "glMultTransposeMatrixf", TCL_GLvoid, 0, "<(const GLfloat) m[16]");
    InitFunc(interp, infoPtr, objPtr, 17, 417, "glSampleCoverage", TCL_GLvoid, 1, "<(GLclampf) value <(GLboolean) invert");
    objPtr = InitFuncGroup(interp, infoPtr, 18, "GL_ARB_multitexture (ARB extension 1 and OpenGL 1.2.1)");
    InitFunc(interp, infoPtr, objPtr, 18, 418, "glActiveTextureARB", TCL_GLvoid, 0, "<(GLenum) texture");
    InitFunc(interp, infoPtr, objPtr, 18, 419, "glClientActiveTextureARB", TCL_GLvoid, 0, "<(GLenum) texture");
    InitFunc(interp, infoPtr, objPtr, 18, 420, "glMultiTexCoord1dARB", TCL_GLvoid, 1, "<(GLenum) target <(GLdouble) s");
    InitFunc(interp, infoPtr, objPtr, 18, 421, "glMultiTexCoord1dvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 422, "glMultiTexCoord1fARB", TCL_GLvoid, 1, "<(GLenum) target <(GLfloat) s");
    InitFunc(interp, infoPtr, objPtr, 18, 423, "glMultiTexCoord1fvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 424, "glMultiTexCoord1iARB", TCL_GLvoid, 1, "<(GLenum) target <(GLint) s");
    InitFunc(interp, infoPtr, objPtr, 18, 425, "glMultiTexCoord1ivARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 426, "glMultiTexCoord1sARB", TCL_GLvoid, 1, "<(GLenum) target <(GLshort) s");
    InitFunc(interp, infoPtr, objPtr, 18, 427, "glMultiTexCoord1svARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 428, "glMultiTexCoord2dARB", TCL_GLvoid, 2, "<(GLenum) target <(GLdouble) s <(GLdouble) t");
    InitFunc(interp, infoPtr, objPtr, 18, 429, "glMultiTexCoord2dvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 430, "glMultiTexCoord2fARB", TCL_GLvoid, 2, "<(GLenum) target <(GLfloat) s <(GLfloat) t");
    InitFunc(interp, infoPtr, objPtr, 18, 431, "glMultiTexCoord2fvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 432, "glMultiTexCoord2iARB", TCL_GLvoid, 2, "<(GLenum) target <(GLint) s <(GLint) t");
    InitFunc(interp, infoPtr, objPtr, 18, 433, "glMultiTexCoord2ivARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 434, "glMultiTexCoord2sARB", TCL_GLvoid, 2, "<(GLenum) target <(GLshort) s <(GLshort) t");
    InitFunc(interp, infoPtr, objPtr, 18, 435, "glMultiTexCoord2svARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 436, "glMultiTexCoord3dARB", TCL_GLvoid, 3, "<(GLenum) target <(GLdouble) s <(GLdouble) t <(GLdouble) r");
    InitFunc(interp, infoPtr, objPtr, 18, 437, "glMultiTexCoord3dvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 438, "glMultiTexCoord3fARB", TCL_GLvoid, 3, "<(GLenum) target <(GLfloat) s <(GLfloat) t <(GLfloat) r");
    InitFunc(interp, infoPtr, objPtr, 18, 439, "glMultiTexCoord3fvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 440, "glMultiTexCoord3iARB", TCL_GLvoid, 3, "<(GLenum) target <(GLint) s <(GLint) t <(GLint) r");
    InitFunc(interp, infoPtr, objPtr, 18, 441, "glMultiTexCoord3ivARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 442, "glMultiTexCoord3sARB", TCL_GLvoid, 3, "<(GLenum) target <(GLshort) s <(GLshort) t <(GLshort) r");
    InitFunc(interp, infoPtr, objPtr, 18, 443, "glMultiTexCoord3svARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 444, "glMultiTexCoord4dARB", TCL_GLvoid, 4, "<(GLenum) target <(GLdouble) s <(GLdouble) t <(GLdouble) r <(GLdouble) q");
    InitFunc(interp, infoPtr, objPtr, 18, 445, "glMultiTexCoord4dvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLdouble*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 446, "glMultiTexCoord4fARB", TCL_GLvoid, 4, "<(GLenum) target <(GLfloat) s <(GLfloat) t <(GLfloat) r <(GLfloat) q");
    InitFunc(interp, infoPtr, objPtr, 18, 447, "glMultiTexCoord4fvARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLfloat*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 448, "glMultiTexCoord4iARB", TCL_GLvoid, 4, "<(GLenum) target <(GLint) s <(GLint) t <(GLint) r <(GLint) q");
    InitFunc(interp, infoPtr, objPtr, 18, 449, "glMultiTexCoord4ivARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLint*) v");
    InitFunc(interp, infoPtr, objPtr, 18, 450, "glMultiTexCoord4sARB", TCL_GLvoid, 4, "<(GLenum) target <(GLshort) s <(GLshort) t <(GLshort) r <(GLshort) q");
    InitFunc(interp, infoPtr, objPtr, 18, 451, "glMultiTexCoord4svARB", TCL_GLvoid, 1, "<(GLenum) target <(const GLshort*) v");
    objPtr = InitFuncGroup(interp, infoPtr, 19, "???. GL_MESA_packed_depth_stencil * XXX obsolete");
    InitFunc(interp, infoPtr, objPtr, 19, 452, "glBlendEquationSeparateATI", TCL_GLvoid, 1, "<(GLenum) modeRGB <(GLenum) modeA");
