    { "::ntk::gl::GLext::glBlendColor",
            NULL, TclGLext_glBlendColorCmd },
    { "::ntk::gl::GLext::glBlendEquation",
            NULL, TclGLext_glBlendEquationCmd },
    { "::ntk::gl::GLext::glDrawRangeElements",
            NULL, TclGLext_glDrawRangeElementsCmd },
    { "::ntk::gl::GLext::glColorTable",
            NULL, TclGLext_glColorTableCmd },
    { "::ntk::gl::GLext::glColorTableParameterfv",
            NULL, TclGLext_glColorTableParameterfvCmd },
    { "::ntk::gl::GLext::glColorTableParameteriv",
            NULL, TclGLext_glColorTableParameterivCmd },
    { "::ntk::gl::GLext::glCopyColorTable",
            NULL, TclGLext_glCopyColorTableCmd },
    { "::ntk::gl::GLext::glGetColorTable",
            NULL, TclGLext_glGetColorTableCmd },
    { "::ntk::gl::GLext::glGetColorTableParameterfv",
            NULL, TclGLext_glGetColorTableParameterfvCmd },
    { "::ntk::gl::GLext::glGetColorTableParameteriv",
            NULL, TclGLext_glGetColorTableParameterivCmd },
    { "::ntk::gl::GLext::glColorSubTable",
            NULL, TclGLext_glColorSubTableCmd },
    { "::ntk::gl::GLext::glCopyColorSubTable",
            NULL, TclGLext_glCopyColorSubTableCmd },
    { "::ntk::gl::GLext::glConvolutionFilter1D",
            NULL, TclGLext_glConvolutionFilter1DCmd },
    { "::ntk::gl::GLext::glConvolutionFilter2D",
            NULL, TclGLext_glConvolutionFilter2DCmd },
    { "::ntk::gl::GLext::glConvolutionParameterf",
            NULL, TclGLext_glConvolutionParameterfCmd },
    { "::ntk::gl::GLext::glConvolutionParameterfv",
            NULL, TclGLext_glConvolutionParameterfvCmd },
    { "::ntk::gl::GLext::glConvolutionParameteri",
            NULL, TclGLext_glConvolutionParameteriCmd },
    { "::ntk::gl::GLext::glConvolutionParameteriv",
            NULL, TclGLext_glConvolutionParameterivCmd },
    { "::ntk::gl::GLext::glCopyConvolutionFilter1D",
            NULL, TclGLext_glCopyConvolutionFilter1DCmd },
    { "::ntk::gl::GLext::glCopyConvolutionFilter2D",
            NULL, TclGLext_glCopyConvolutionFilter2DCmd },
    { "::ntk::gl::GLext::glGetConvolutionFilter",
            NULL, TclGLext_glGetConvolutionFilterCmd },
    { "::ntk::gl::GLext::glGetConvolutionParameterfv",
            NULL, TclGLext_glGetConvolutionParameterfvCmd },
    { "::ntk::gl::GLext::glGetConvolutionParameteriv",
            NULL, TclGLext_glGetConvolutionParameterivCmd },
    { "::ntk::gl::GLext::glGetSeparableFilter",
            NULL, TclGLext_glGetSeparableFilterCmd },
    { "::ntk::gl::GLext::glSeparableFilter2D",
            NULL, TclGLext_glSeparableFilter2DCmd },
    { "::ntk::gl::GLext::glGetHistogram",
            NULL, TclGLext_glGetHistogramCmd },
    { "::ntk::gl::GLext::glGetHistogramParameterfv",
            NULL, TclGLext_glGetHistogramParameterfvCmd },
    { "::ntk::gl::GLext::glGetHistogramParameteriv",
            NULL, TclGLext_glGetHistogramParameterivCmd },
    { "::ntk::gl::GLext::glGetMinmax",
            NULL, TclGLext_glGetMinmaxCmd },
    { "::ntk::gl::GLext::glGetMinmaxParameterfv",
            NULL, TclGLext_glGetMinmaxParameterfvCmd },
    { "::ntk::gl::GLext::glGetMinmaxParameteriv",
            NULL, TclGLext_glGetMinmaxParameterivCmd },
    { "::ntk::gl::GLext::glHistogram",
            NULL, TclGLext_glHistogramCmd },
    { "::ntk::gl::GLext::glMinmax",
            NULL, TclGLext_glMinmaxCmd },
    { "::ntk::gl::GLext::glResetHistogram",
            NULL, TclGLext_glResetHistogramCmd },
    { "::ntk::gl::GLext::glResetMinmax",
            NULL, TclGLext_glResetMinmaxCmd },
    { "::ntk::gl::GLext::glTexImage3D",
            NULL, TclGLext_glTexImage3DCmd },
    { "::ntk::gl::GLext::glTexSubImage3D",
            NULL, TclGLext_glTexSubImage3DCmd },
    { "::ntk::gl::GLext::glCopyTexSubImage3D",
            NULL, TclGLext_glCopyTexSubImage3DCmd },
    { "::ntk::gl::GLext::glActiveTexture",
            NULL, TclGLext_glActiveTextureCmd },
    { "::ntk::gl::GLext::glClientActiveTexture",
            NULL, TclGLext_glClientActiveTextureCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1d",
            NULL, TclGLext_glMultiTexCoord1dCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1dv",
            NULL, TclGLext_glMultiTexCoord1dvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1f",
            NULL, TclGLext_glMultiTexCoord1fCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1fv",
            NULL, TclGLext_glMultiTexCoord1fvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1i",
            NULL, TclGLext_glMultiTexCoord1iCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1iv",
            NULL, TclGLext_glMultiTexCoord1ivCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1s",
            NULL, TclGLext_glMultiTexCoord1sCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1sv",
            NULL, TclGLext_glMultiTexCoord1svCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2d",
            NULL, TclGLext_glMultiTexCoord2dCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2dv",
            NULL, TclGLext_glMultiTexCoord2dvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2f",
            NULL, TclGLext_glMultiTexCoord2fCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2fv",
            NULL, TclGLext_glMultiTexCoord2fvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2i",
            NULL, TclGLext_glMultiTexCoord2iCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2iv",
            NULL, TclGLext_glMultiTexCoord2ivCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2s",
            NULL, TclGLext_glMultiTexCoord2sCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2sv",
            NULL, TclGLext_glMultiTexCoord2svCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3d",
            NULL, TclGLext_glMultiTexCoord3dCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3dv",
            NULL, TclGLext_glMultiTexCoord3dvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3f",
            NULL, TclGLext_glMultiTexCoord3fCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3fv",
            NULL, TclGLext_glMultiTexCoord3fvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3i",
            NULL, TclGLext_glMultiTexCoord3iCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3iv",
            NULL, TclGLext_glMultiTexCoord3ivCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3s",
            NULL, TclGLext_glMultiTexCoord3sCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3sv",
            NULL, TclGLext_glMultiTexCoord3svCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4d",
            NULL, TclGLext_glMultiTexCoord4dCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4dv",
            NULL, TclGLext_glMultiTexCoord4dvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4f",
            NULL, TclGLext_glMultiTexCoord4fCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4fv",
            NULL, TclGLext_glMultiTexCoord4fvCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4i",
            NULL, TclGLext_glMultiTexCoord4iCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4iv",
            NULL, TclGLext_glMultiTexCoord4ivCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4s",
            NULL, TclGLext_glMultiTexCoord4sCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4sv",
            NULL, TclGLext_glMultiTexCoord4svCmd },
    { "::ntk::gl::GLext::glLoadTransposeMatrixf",
            NULL, TclGLext_glLoadTransposeMatrixfCmd },
    { "::ntk::gl::GLext::glLoadTransposeMatrixd",
            NULL, TclGLext_glLoadTransposeMatrixdCmd },
    { "::ntk::gl::GLext::glMultTransposeMatrixf",
            NULL, TclGLext_glMultTransposeMatrixfCmd },
    { "::ntk::gl::GLext::glMultTransposeMatrixd",
            NULL, TclGLext_glMultTransposeMatrixdCmd },
    { "::ntk::gl::GLext::glSampleCoverage",
            NULL, TclGLext_glSampleCoverageCmd },
    { "::ntk::gl::GLext::glCompressedTexImage3D",
            NULL, TclGLext_glCompressedTexImage3DCmd },
    { "::ntk::gl::GLext::glCompressedTexImage2D",
            NULL, TclGLext_glCompressedTexImage2DCmd },
    { "::ntk::gl::GLext::glCompressedTexImage1D",
            NULL, TclGLext_glCompressedTexImage1DCmd },
    { "::ntk::gl::GLext::glCompressedTexSubImage3D",
            NULL, TclGLext_glCompressedTexSubImage3DCmd },
    { "::ntk::gl::GLext::glCompressedTexSubImage2D",
            NULL, TclGLext_glCompressedTexSubImage2DCmd },
    { "::ntk::gl::GLext::glCompressedTexSubImage1D",
            NULL, TclGLext_glCompressedTexSubImage1DCmd },
    { "::ntk::gl::GLext::glGetCompressedTexImage",
            NULL, TclGLext_glGetCompressedTexImageCmd },
    { "::ntk::gl::GLext::glBlendFuncSeparate",
            NULL, TclGLext_glBlendFuncSeparateCmd },
    { "::ntk::gl::GLext::glFogCoordf",
            NULL, TclGLext_glFogCoordfCmd },
    { "::ntk::gl::GLext::glFogCoordfv",
            NULL, TclGLext_glFogCoordfvCmd },
    { "::ntk::gl::GLext::glFogCoordd",
            NULL, TclGLext_glFogCoorddCmd },
    { "::ntk::gl::GLext::glFogCoorddv",
            NULL, TclGLext_glFogCoorddvCmd },
    { "::ntk::gl::GLext::glFogCoordPointer",
            NULL, TclGLext_glFogCoordPointerCmd },
    { "::ntk::gl::GLext::glMultiDrawArrays",
            NULL, TclGLext_glMultiDrawArraysCmd },
    { "::ntk::gl::GLext::glMultiDrawElements",
            NULL, TclGLext_glMultiDrawElementsCmd },
    { "::ntk::gl::GLext::glPointParameterf",
            NULL, TclGLext_glPointParameterfCmd },
    { "::ntk::gl::GLext::glPointParameterfv",
            NULL, TclGLext_glPointParameterfvCmd },
    { "::ntk::gl::GLext::glPointParameteri",
            NULL, TclGLext_glPointParameteriCmd },
    { "::ntk::gl::GLext::glPointParameteriv",
            NULL, TclGLext_glPointParameterivCmd },
    { "::ntk::gl::GLext::glSecondaryColor3b",
            NULL, TclGLext_glSecondaryColor3bCmd },
    { "::ntk::gl::GLext::glSecondaryColor3bv",
            NULL, TclGLext_glSecondaryColor3bvCmd },
    { "::ntk::gl::GLext::glSecondaryColor3d",
            NULL, TclGLext_glSecondaryColor3dCmd },
    { "::ntk::gl::GLext::glSecondaryColor3dv",
            NULL, TclGLext_glSecondaryColor3dvCmd },
    { "::ntk::gl::GLext::glSecondaryColor3f",
            NULL, TclGLext_glSecondaryColor3fCmd },
    { "::ntk::gl::GLext::glSecondaryColor3fv",
            NULL, TclGLext_glSecondaryColor3fvCmd },
    { "::ntk::gl::GLext::glSecondaryColor3i",
            NULL, TclGLext_glSecondaryColor3iCmd },
    { "::ntk::gl::GLext::glSecondaryColor3iv",
            NULL, TclGLext_glSecondaryColor3ivCmd },
    { "::ntk::gl::GLext::glSecondaryColor3s",
            NULL, TclGLext_glSecondaryColor3sCmd },
    { "::ntk::gl::GLext::glSecondaryColor3sv",
            NULL, TclGLext_glSecondaryColor3svCmd },
    { "::ntk::gl::GLext::glSecondaryColor3ub",
            NULL, TclGLext_glSecondaryColor3ubCmd },
    { "::ntk::gl::GLext::glSecondaryColor3ubv",
            NULL, TclGLext_glSecondaryColor3ubvCmd },
    { "::ntk::gl::GLext::glSecondaryColor3ui",
            NULL, TclGLext_glSecondaryColor3uiCmd },
    { "::ntk::gl::GLext::glSecondaryColor3uiv",
            NULL, TclGLext_glSecondaryColor3uivCmd },
    { "::ntk::gl::GLext::glSecondaryColor3us",
            NULL, TclGLext_glSecondaryColor3usCmd },
    { "::ntk::gl::GLext::glSecondaryColor3usv",
            NULL, TclGLext_glSecondaryColor3usvCmd },
    { "::ntk::gl::GLext::glSecondaryColorPointer",
            NULL, TclGLext_glSecondaryColorPointerCmd },
    { "::ntk::gl::GLext::glWindowPos2d",
            NULL, TclGLext_glWindowPos2dCmd },
    { "::ntk::gl::GLext::glWindowPos2dv",
            NULL, TclGLext_glWindowPos2dvCmd },
    { "::ntk::gl::GLext::glWindowPos2f",
            NULL, TclGLext_glWindowPos2fCmd },
    { "::ntk::gl::GLext::glWindowPos2fv",
            NULL, TclGLext_glWindowPos2fvCmd },
    { "::ntk::gl::GLext::glWindowPos2i",
            NULL, TclGLext_glWindowPos2iCmd },
    { "::ntk::gl::GLext::glWindowPos2iv",
            NULL, TclGLext_glWindowPos2ivCmd },
    { "::ntk::gl::GLext::glWindowPos2s",
            NULL, TclGLext_glWindowPos2sCmd },
    { "::ntk::gl::GLext::glWindowPos2sv",
            NULL, TclGLext_glWindowPos2svCmd },
    { "::ntk::gl::GLext::glWindowPos3d",
            NULL, TclGLext_glWindowPos3dCmd },
    { "::ntk::gl::GLext::glWindowPos3dv",
            NULL, TclGLext_glWindowPos3dvCmd },
    { "::ntk::gl::GLext::glWindowPos3f",
            NULL, TclGLext_glWindowPos3fCmd },
    { "::ntk::gl::GLext::glWindowPos3fv",
            NULL, TclGLext_glWindowPos3fvCmd },
    { "::ntk::gl::GLext::glWindowPos3i",
            NULL, TclGLext_glWindowPos3iCmd },
    { "::ntk::gl::GLext::glWindowPos3iv",
            NULL, TclGLext_glWindowPos3ivCmd },
    { "::ntk::gl::GLext::glWindowPos3s",
            NULL, TclGLext_glWindowPos3sCmd },
    { "::ntk::gl::GLext::glWindowPos3sv",
            NULL, TclGLext_glWindowPos3svCmd },
    { "::ntk::gl::GLext::glGenQueries",
            NULL, TclGLext_glGenQueriesCmd },
    { "::ntk::gl::GLext::glDeleteQueries",
            NULL, TclGLext_glDeleteQueriesCmd },
    { "::ntk::gl::GLext::glIsQuery",
            NULL, TclGLext_glIsQueryCmd },
    { "::ntk::gl::GLext::glBeginQuery",
            NULL, TclGLext_glBeginQueryCmd },
    { "::ntk::gl::GLext::glEndQuery",
            NULL, TclGLext_glEndQueryCmd },
    { "::ntk::gl::GLext::glGetQueryiv",
            NULL, TclGLext_glGetQueryivCmd },
    { "::ntk::gl::GLext::glGetQueryObjectiv",
            NULL, TclGLext_glGetQueryObjectivCmd },
    { "::ntk::gl::GLext::glGetQueryObjectuiv",
            NULL, TclGLext_glGetQueryObjectuivCmd },
    { "::ntk::gl::GLext::glBindBuffer",
            NULL, TclGLext_glBindBufferCmd },
    { "::ntk::gl::GLext::glDeleteBuffers",
            NULL, TclGLext_glDeleteBuffersCmd },
    { "::ntk::gl::GLext::glGenBuffers",
            NULL, TclGLext_glGenBuffersCmd },
    { "::ntk::gl::GLext::glIsBuffer",
            NULL, TclGLext_glIsBufferCmd },
    { "::ntk::gl::GLext::glBufferData",
            NULL, TclGLext_glBufferDataCmd },
    { "::ntk::gl::GLext::glBufferSubData",
            NULL, TclGLext_glBufferSubDataCmd },
    { "::ntk::gl::GLext::glGetBufferSubData",
            NULL, TclGLext_glGetBufferSubDataCmd },
    { "::ntk::gl::GLext::glMapBuffer",
            NULL, TclGLext_glMapBufferCmd },
    { "::ntk::gl::GLext::glUnmapBuffer",
            NULL, TclGLext_glUnmapBufferCmd },
    { "::ntk::gl::GLext::glGetBufferParameteriv",
            NULL, TclGLext_glGetBufferParameterivCmd },
    { "::ntk::gl::GLext::glGetBufferPointerv",
            NULL, TclGLext_glGetBufferPointervCmd },
    { "::ntk::gl::GLext::glActiveTextureARB",
            NULL, TclGLext_glActiveTextureARBCmd },
    { "::ntk::gl::GLext::glClientActiveTextureARB",
            NULL, TclGLext_glClientActiveTextureARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1dARB",
            NULL, TclGLext_glMultiTexCoord1dARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1dvARB",
            NULL, TclGLext_glMultiTexCoord1dvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1fARB",
            NULL, TclGLext_glMultiTexCoord1fARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1fvARB",
            NULL, TclGLext_glMultiTexCoord1fvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1iARB",
            NULL, TclGLext_glMultiTexCoord1iARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1ivARB",
            NULL, TclGLext_glMultiTexCoord1ivARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1sARB",
            NULL, TclGLext_glMultiTexCoord1sARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord1svARB",
            NULL, TclGLext_glMultiTexCoord1svARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2dARB",
            NULL, TclGLext_glMultiTexCoord2dARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2dvARB",
            NULL, TclGLext_glMultiTexCoord2dvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2fARB",
            NULL, TclGLext_glMultiTexCoord2fARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2fvARB",
            NULL, TclGLext_glMultiTexCoord2fvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2iARB",
            NULL, TclGLext_glMultiTexCoord2iARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2ivARB",
            NULL, TclGLext_glMultiTexCoord2ivARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2sARB",
            NULL, TclGLext_glMultiTexCoord2sARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord2svARB",
            NULL, TclGLext_glMultiTexCoord2svARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3dARB",
            NULL, TclGLext_glMultiTexCoord3dARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3dvARB",
            NULL, TclGLext_glMultiTexCoord3dvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3fARB",
            NULL, TclGLext_glMultiTexCoord3fARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3fvARB",
            NULL, TclGLext_glMultiTexCoord3fvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3iARB",
            NULL, TclGLext_glMultiTexCoord3iARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3ivARB",
            NULL, TclGLext_glMultiTexCoord3ivARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3sARB",
            NULL, TclGLext_glMultiTexCoord3sARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord3svARB",
            NULL, TclGLext_glMultiTexCoord3svARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4dARB",
            NULL, TclGLext_glMultiTexCoord4dARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4dvARB",
            NULL, TclGLext_glMultiTexCoord4dvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4fARB",
            NULL, TclGLext_glMultiTexCoord4fARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4fvARB",
            NULL, TclGLext_glMultiTexCoord4fvARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4iARB",
            NULL, TclGLext_glMultiTexCoord4iARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4ivARB",
            NULL, TclGLext_glMultiTexCoord4ivARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4sARB",
            NULL, TclGLext_glMultiTexCoord4sARBCmd },
    { "::ntk::gl::GLext::glMultiTexCoord4svARB",
            NULL, TclGLext_glMultiTexCoord4svARBCmd },
    { "::ntk::gl::GLext::glLoadTransposeMatrixfARB",
            NULL, TclGLext_glLoadTransposeMatrixfARBCmd },
    { "::ntk::gl::GLext::glLoadTransposeMatrixdARB",
            NULL, TclGLext_glLoadTransposeMatrixdARBCmd },
    { "::ntk::gl::GLext::glMultTransposeMatrixfARB",
            NULL, TclGLext_glMultTransposeMatrixfARBCmd },
    { "::ntk::gl::GLext::glMultTransposeMatrixdARB",
            NULL, TclGLext_glMultTransposeMatrixdARBCmd },
    { "::ntk::gl::GLext::glSampleCoverageARB",
            NULL, TclGLext_glSampleCoverageARBCmd },
    { "::ntk::gl::GLext::glCompressedTexImage3DARB",
            NULL, TclGLext_glCompressedTexImage3DARBCmd },
    { "::ntk::gl::GLext::glCompressedTexImage2DARB",
            NULL, TclGLext_glCompressedTexImage2DARBCmd },
    { "::ntk::gl::GLext::glCompressedTexImage1DARB",
            NULL, TclGLext_glCompressedTexImage1DARBCmd },
    { "::ntk::gl::GLext::glCompressedTexSubImage3DARB",
            NULL, TclGLext_glCompressedTexSubImage3DARBCmd },
    { "::ntk::gl::GLext::glCompressedTexSubImage2DARB",
            NULL, TclGLext_glCompressedTexSubImage2DARBCmd },
    { "::ntk::gl::GLext::glCompressedTexSubImage1DARB",
            NULL, TclGLext_glCompressedTexSubImage1DARBCmd },
    { "::ntk::gl::GLext::glGetCompressedTexImageARB",
            NULL, TclGLext_glGetCompressedTexImageARBCmd },
    { "::ntk::gl::GLext::glPointParameterfARB",
            NULL, TclGLext_glPointParameterfARBCmd },
    { "::ntk::gl::GLext::glPointParameterfvARB",
            NULL, TclGLext_glPointParameterfvARBCmd },
    { "::ntk::gl::GLext::glWeightbvARB",
            NULL, TclGLext_glWeightbvARBCmd },
    { "::ntk::gl::GLext::glWeightsvARB",
            NULL, TclGLext_glWeightsvARBCmd },
    { "::ntk::gl::GLext::glWeightivARB",
            NULL, TclGLext_glWeightivARBCmd },
    { "::ntk::gl::GLext::glWeightfvARB",
            NULL, TclGLext_glWeightfvARBCmd },
    { "::ntk::gl::GLext::glWeightdvARB",
            NULL, TclGLext_glWeightdvARBCmd },
    { "::ntk::gl::GLext::glWeightubvARB",
            NULL, TclGLext_glWeightubvARBCmd },
    { "::ntk::gl::GLext::glWeightusvARB",
            NULL, TclGLext_glWeightusvARBCmd },
    { "::ntk::gl::GLext::glWeightuivARB",
            NULL, TclGLext_glWeightuivARBCmd },
    { "::ntk::gl::GLext::glWeightPointerARB",
            NULL, TclGLext_glWeightPointerARBCmd },
    { "::ntk::gl::GLext::glVertexBlendARB",
            NULL, TclGLext_glVertexBlendARBCmd },
    { "::ntk::gl::GLext::glCurrentPaletteMatrixARB",
            NULL, TclGLext_glCurrentPaletteMatrixARBCmd },
    { "::ntk::gl::GLext::glMatrixIndexubvARB",
            NULL, TclGLext_glMatrixIndexubvARBCmd },
    { "::ntk::gl::GLext::glMatrixIndexusvARB",
            NULL, TclGLext_glMatrixIndexusvARBCmd },
    { "::ntk::gl::GLext::glMatrixIndexuivARB",
            NULL, TclGLext_glMatrixIndexuivARBCmd },
    { "::ntk::gl::GLext::glMatrixIndexPointerARB",
            NULL, TclGLext_glMatrixIndexPointerARBCmd },
    { "::ntk::gl::GLext::glWindowPos2dARB",
            NULL, TclGLext_glWindowPos2dARBCmd },
    { "::ntk::gl::GLext::glWindowPos2dvARB",
            NULL, TclGLext_glWindowPos2dvARBCmd },
    { "::ntk::gl::GLext::glWindowPos2fARB",
            NULL, TclGLext_glWindowPos2fARBCmd },
    { "::ntk::gl::GLext::glWindowPos2fvARB",
            NULL, TclGLext_glWindowPos2fvARBCmd },
    { "::ntk::gl::GLext::glWindowPos2iARB",
            NULL, TclGLext_glWindowPos2iARBCmd },
    { "::ntk::gl::GLext::glWindowPos2ivARB",
            NULL, TclGLext_glWindowPos2ivARBCmd },
    { "::ntk::gl::GLext::glWindowPos2sARB",
            NULL, TclGLext_glWindowPos2sARBCmd },
    { "::ntk::gl::GLext::glWindowPos2svARB",
            NULL, TclGLext_glWindowPos2svARBCmd },
    { "::ntk::gl::GLext::glWindowPos3dARB",
            NULL, TclGLext_glWindowPos3dARBCmd },
    { "::ntk::gl::GLext::glWindowPos3dvARB",
            NULL, TclGLext_glWindowPos3dvARBCmd },
    { "::ntk::gl::GLext::glWindowPos3fARB",
            NULL, TclGLext_glWindowPos3fARBCmd },
    { "::ntk::gl::GLext::glWindowPos3fvARB",
            NULL, TclGLext_glWindowPos3fvARBCmd },
    { "::ntk::gl::GLext::glWindowPos3iARB",
            NULL, TclGLext_glWindowPos3iARBCmd },
    { "::ntk::gl::GLext::glWindowPos3ivARB",
            NULL, TclGLext_glWindowPos3ivARBCmd },
    { "::ntk::gl::GLext::glWindowPos3sARB",
            NULL, TclGLext_glWindowPos3sARBCmd },
    { "::ntk::gl::GLext::glWindowPos3svARB",
            NULL, TclGLext_glWindowPos3svARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib1dARB",
            NULL, TclGLext_glVertexAttrib1dARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib1dvARB",
            NULL, TclGLext_glVertexAttrib1dvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib1fARB",
            NULL, TclGLext_glVertexAttrib1fARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib1fvARB",
            NULL, TclGLext_glVertexAttrib1fvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib1sARB",
            NULL, TclGLext_glVertexAttrib1sARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib1svARB",
            NULL, TclGLext_glVertexAttrib1svARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib2dARB",
            NULL, TclGLext_glVertexAttrib2dARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib2dvARB",
            NULL, TclGLext_glVertexAttrib2dvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib2fARB",
            NULL, TclGLext_glVertexAttrib2fARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib2fvARB",
            NULL, TclGLext_glVertexAttrib2fvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib2sARB",
            NULL, TclGLext_glVertexAttrib2sARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib2svARB",
            NULL, TclGLext_glVertexAttrib2svARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib3dARB",
            NULL, TclGLext_glVertexAttrib3dARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib3dvARB",
            NULL, TclGLext_glVertexAttrib3dvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib3fARB",
            NULL, TclGLext_glVertexAttrib3fARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib3fvARB",
            NULL, TclGLext_glVertexAttrib3fvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib3sARB",
            NULL, TclGLext_glVertexAttrib3sARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib3svARB",
            NULL, TclGLext_glVertexAttrib3svARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4NbvARB",
            NULL, TclGLext_glVertexAttrib4NbvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4NivARB",
            NULL, TclGLext_glVertexAttrib4NivARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4NsvARB",
            NULL, TclGLext_glVertexAttrib4NsvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4NubARB",
            NULL, TclGLext_glVertexAttrib4NubARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4NubvARB",
            NULL, TclGLext_glVertexAttrib4NubvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4NuivARB",
            NULL, TclGLext_glVertexAttrib4NuivARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4NusvARB",
            NULL, TclGLext_glVertexAttrib4NusvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4bvARB",
            NULL, TclGLext_glVertexAttrib4bvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4dARB",
            NULL, TclGLext_glVertexAttrib4dARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4dvARB",
            NULL, TclGLext_glVertexAttrib4dvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4fARB",
            NULL, TclGLext_glVertexAttrib4fARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4fvARB",
            NULL, TclGLext_glVertexAttrib4fvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4ivARB",
            NULL, TclGLext_glVertexAttrib4ivARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4sARB",
            NULL, TclGLext_glVertexAttrib4sARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4svARB",
            NULL, TclGLext_glVertexAttrib4svARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4ubvARB",
            NULL, TclGLext_glVertexAttrib4ubvARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4uivARB",
            NULL, TclGLext_glVertexAttrib4uivARBCmd },
    { "::ntk::gl::GLext::glVertexAttrib4usvARB",
            NULL, TclGLext_glVertexAttrib4usvARBCmd },
    { "::ntk::gl::GLext::glVertexAttribPointerARB",
            NULL, TclGLext_glVertexAttribPointerARBCmd },
    { "::ntk::gl::GLext::glEnableVertexAttribArrayARB",
            NULL, TclGLext_glEnableVertexAttribArrayARBCmd },
    { "::ntk::gl::GLext::glDisableVertexAttribArrayARB",
            NULL, TclGLext_glDisableVertexAttribArrayARBCmd },
    { "::ntk::gl::GLext::glProgramStringARB",
            NULL, TclGLext_glProgramStringARBCmd },
    { "::ntk::gl::GLext::glBindProgramARB",
            NULL, TclGLext_glBindProgramARBCmd },
    { "::ntk::gl::GLext::glDeleteProgramsARB",
            NULL, TclGLext_glDeleteProgramsARBCmd },
    { "::ntk::gl::GLext::glGenProgramsARB",
            NULL, TclGLext_glGenProgramsARBCmd },
    { "::ntk::gl::GLext::glProgramEnvParameter4dARB",
            NULL, TclGLext_glProgramEnvParameter4dARBCmd },
    { "::ntk::gl::GLext::glProgramEnvParameter4dvARB",
            NULL, TclGLext_glProgramEnvParameter4dvARBCmd },
    { "::ntk::gl::GLext::glProgramEnvParameter4fARB",
            NULL, TclGLext_glProgramEnvParameter4fARBCmd },
    { "::ntk::gl::GLext::glProgramEnvParameter4fvARB",
            NULL, TclGLext_glProgramEnvParameter4fvARBCmd },
    { "::ntk::gl::GLext::glProgramLocalParameter4dARB",
            NULL, TclGLext_glProgramLocalParameter4dARBCmd },
    { "::ntk::gl::GLext::glProgramLocalParameter4dvARB",
            NULL, TclGLext_glProgramLocalParameter4dvARBCmd },
    { "::ntk::gl::GLext::glProgramLocalParameter4fARB",
            NULL, TclGLext_glProgramLocalParameter4fARBCmd },
    { "::ntk::gl::GLext::glProgramLocalParameter4fvARB",
            NULL, TclGLext_glProgramLocalParameter4fvARBCmd },
    { "::ntk::gl::GLext::glGetProgramEnvParameterdvARB",
            NULL, TclGLext_glGetProgramEnvParameterdvARBCmd },
    { "::ntk::gl::GLext::glGetProgramEnvParameterfvARB",
            NULL, TclGLext_glGetProgramEnvParameterfvARBCmd },
    { "::ntk::gl::GLext::glGetProgramLocalParameterdvARB",
            NULL, TclGLext_glGetProgramLocalParameterdvARBCmd },
    { "::ntk::gl::GLext::glGetProgramLocalParameterfvARB",
            NULL, TclGLext_glGetProgramLocalParameterfvARBCmd },
    { "::ntk::gl::GLext::glGetProgramivARB",
            NULL, TclGLext_glGetProgramivARBCmd },
    { "::ntk::gl::GLext::glGetProgramStringARB",
            NULL, TclGLext_glGetProgramStringARBCmd },
    { "::ntk::gl::GLext::glGetVertexAttribdvARB",
            NULL, TclGLext_glGetVertexAttribdvARBCmd },
    { "::ntk::gl::GLext::glGetVertexAttribfvARB",
            NULL, TclGLext_glGetVertexAttribfvARBCmd },
    { "::ntk::gl::GLext::glGetVertexAttribivARB",
            NULL, TclGLext_glGetVertexAttribivARBCmd },
    { "::ntk::gl::GLext::glGetVertexAttribPointervARB",
            NULL, TclGLext_glGetVertexAttribPointervARBCmd },
    { "::ntk::gl::GLext::glIsProgramARB",
            NULL, TclGLext_glIsProgramARBCmd },
    { "::ntk::gl::GLext::glBindBufferARB",
            NULL, TclGLext_glBindBufferARBCmd },
    { "::ntk::gl::GLext::glDeleteBuffersARB",
            NULL, TclGLext_glDeleteBuffersARBCmd },
    { "::ntk::gl::GLext::glGenBuffersARB",
            NULL, TclGLext_glGenBuffersARBCmd },
    { "::ntk::gl::GLext::glIsBufferARB",
            NULL, TclGLext_glIsBufferARBCmd },
    { "::ntk::gl::GLext::glBufferDataARB",
            NULL, TclGLext_glBufferDataARBCmd },
    { "::ntk::gl::GLext::glBufferSubDataARB",
            NULL, TclGLext_glBufferSubDataARBCmd },
    { "::ntk::gl::GLext::glGetBufferSubDataARB",
            NULL, TclGLext_glGetBufferSubDataARBCmd },
    { "::ntk::gl::GLext::glMapBufferARB",
            NULL, TclGLext_glMapBufferARBCmd },
    { "::ntk::gl::GLext::glUnmapBufferARB",
            NULL, TclGLext_glUnmapBufferARBCmd },
    { "::ntk::gl::GLext::glGetBufferParameterivARB",
            NULL, TclGLext_glGetBufferParameterivARBCmd },
    { "::ntk::gl::GLext::glGetBufferPointervARB",
            NULL, TclGLext_glGetBufferPointervARBCmd },
    { "::ntk::gl::GLext::glGenQueriesARB",
            NULL, TclGLext_glGenQueriesARBCmd },
    { "::ntk::gl::GLext::glDeleteQueriesARB",
            NULL, TclGLext_glDeleteQueriesARBCmd },
    { "::ntk::gl::GLext::glIsQueryARB",
            NULL, TclGLext_glIsQueryARBCmd },
    { "::ntk::gl::GLext::glBeginQueryARB",
            NULL, TclGLext_glBeginQueryARBCmd },
    { "::ntk::gl::GLext::glEndQueryARB",
            NULL, TclGLext_glEndQueryARBCmd },
    { "::ntk::gl::GLext::glGetQueryivARB",
            NULL, TclGLext_glGetQueryivARBCmd },
    { "::ntk::gl::GLext::glGetQueryObjectivARB",
            NULL, TclGLext_glGetQueryObjectivARBCmd },
    { "::ntk::gl::GLext::glGetQueryObjectuivARB",
            NULL, TclGLext_glGetQueryObjectuivARBCmd },
    { "::ntk::gl::GLext::glDeleteObjectARB",
            NULL, TclGLext_glDeleteObjectARBCmd },
    { "::ntk::gl::GLext::glGetHandleARB",
            NULL, TclGLext_glGetHandleARBCmd },
    { "::ntk::gl::GLext::glDetachObjectARB",
            NULL, TclGLext_glDetachObjectARBCmd },
    { "::ntk::gl::GLext::glCreateShaderObjectARB",
            NULL, TclGLext_glCreateShaderObjectARBCmd },
    { "::ntk::gl::GLext::glShaderSourceARB",
            NULL, TclGLext_glShaderSourceARBCmd },
    { "::ntk::gl::GLext::glCompileShaderARB",
            NULL, TclGLext_glCompileShaderARBCmd },
    { "::ntk::gl::GLext::glCreateProgramObjectARB",
            NULL, TclGLext_glCreateProgramObjectARBCmd },
    { "::ntk::gl::GLext::glAttachObjectARB",
            NULL, TclGLext_glAttachObjectARBCmd },
    { "::ntk::gl::GLext::glLinkProgramARB",
            NULL, TclGLext_glLinkProgramARBCmd },
    { "::ntk::gl::GLext::glUseProgramObjectARB",
            NULL, TclGLext_glUseProgramObjectARBCmd },
    { "::ntk::gl::GLext::glValidateProgramARB",
            NULL, TclGLext_glValidateProgramARBCmd },
    { "::ntk::gl::GLext::glUniform1fARB",
            NULL, TclGLext_glUniform1fARBCmd },
    { "::ntk::gl::GLext::glUniform2fARB",
            NULL, TclGLext_glUniform2fARBCmd },
    { "::ntk::gl::GLext::glUniform3fARB",
            NULL, TclGLext_glUniform3fARBCmd },
    { "::ntk::gl::GLext::glUniform4fARB",
            NULL, TclGLext_glUniform4fARBCmd },
    { "::ntk::gl::GLext::glUniform1iARB",
            NULL, TclGLext_glUniform1iARBCmd },
    { "::ntk::gl::GLext::glUniform2iARB",
            NULL, TclGLext_glUniform2iARBCmd },
    { "::ntk::gl::GLext::glUniform3iARB",
            NULL, TclGLext_glUniform3iARBCmd },
    { "::ntk::gl::GLext::glUniform4iARB",
            NULL, TclGLext_glUniform4iARBCmd },
    { "::ntk::gl::GLext::glUniform1fvARB",
            NULL, TclGLext_glUniform1fvARBCmd },
    { "::ntk::gl::GLext::glUniform2fvARB",
            NULL, TclGLext_glUniform2fvARBCmd },
    { "::ntk::gl::GLext::glUniform3fvARB",
            NULL, TclGLext_glUniform3fvARBCmd },
    { "::ntk::gl::GLext::glUniform4fvARB",
            NULL, TclGLext_glUniform4fvARBCmd },
    { "::ntk::gl::GLext::glUniform1ivARB",
            NULL, TclGLext_glUniform1ivARBCmd },
    { "::ntk::gl::GLext::glUniform2ivARB",
            NULL, TclGLext_glUniform2ivARBCmd },
    { "::ntk::gl::GLext::glUniform3ivARB",
            NULL, TclGLext_glUniform3ivARBCmd },
    { "::ntk::gl::GLext::glUniform4ivARB",
            NULL, TclGLext_glUniform4ivARBCmd },
    { "::ntk::gl::GLext::glUniformMatrix2fvARB",
            NULL, TclGLext_glUniformMatrix2fvARBCmd },
    { "::ntk::gl::GLext::glUniformMatrix3fvARB",
            NULL, TclGLext_glUniformMatrix3fvARBCmd },
    { "::ntk::gl::GLext::glUniformMatrix4fvARB",
            NULL, TclGLext_glUniformMatrix4fvARBCmd },
    { "::ntk::gl::GLext::glGetObjectParameterfvARB",
            NULL, TclGLext_glGetObjectParameterfvARBCmd },
    { "::ntk::gl::GLext::glGetObjectParameterivARB",
            NULL, TclGLext_glGetObjectParameterivARBCmd },
    { "::ntk::gl::GLext::glGetInfoLogARB",
            NULL, TclGLext_glGetInfoLogARBCmd },
    { "::ntk::gl::GLext::glGetAttachedObjectsARB",
            NULL, TclGLext_glGetAttachedObjectsARBCmd },
    { "::ntk::gl::GLext::glGetUniformLocationARB",
            NULL, TclGLext_glGetUniformLocationARBCmd },
    { "::ntk::gl::GLext::glGetActiveUniformARB",
            NULL, TclGLext_glGetActiveUniformARBCmd },
    { "::ntk::gl::GLext::glGetUniformfvARB",
            NULL, TclGLext_glGetUniformfvARBCmd },
    { "::ntk::gl::GLext::glGetUniformivARB",
            NULL, TclGLext_glGetUniformivARBCmd },
    { "::ntk::gl::GLext::glGetShaderSourceARB",
            NULL, TclGLext_glGetShaderSourceARBCmd },
    { "::ntk::gl::GLext::glBindAttribLocationARB",
            NULL, TclGLext_glBindAttribLocationARBCmd },
    { "::ntk::gl::GLext::glGetActiveAttribARB",
            NULL, TclGLext_glGetActiveAttribARBCmd },
    { "::ntk::gl::GLext::glGetAttribLocationARB",
            NULL, TclGLext_glGetAttribLocationARBCmd },
    { "::ntk::gl::GLext::glDrawBuffersARB",
            NULL, TclGLext_glDrawBuffersARBCmd },
    { "::ntk::gl::GLext::glBlendColorEXT",
            NULL, TclGLext_glBlendColorEXTCmd },
    { "::ntk::gl::GLext::glPolygonOffsetEXT",
            NULL, TclGLext_glPolygonOffsetEXTCmd },
    { "::ntk::gl::GLext::glTexImage3DEXT",
            NULL, TclGLext_glTexImage3DEXTCmd },
    { "::ntk::gl::GLext::glTexSubImage3DEXT",
            NULL, TclGLext_glTexSubImage3DEXTCmd },
    { "::ntk::gl::GLext::glTexSubImage1DEXT",
            NULL, TclGLext_glTexSubImage1DEXTCmd },
    { "::ntk::gl::GLext::glTexSubImage2DEXT",
            NULL, TclGLext_glTexSubImage2DEXTCmd },
    { "::ntk::gl::GLext::glCopyTexImage1DEXT",
            NULL, TclGLext_glCopyTexImage1DEXTCmd },
    { "::ntk::gl::GLext::glCopyTexImage2DEXT",
            NULL, TclGLext_glCopyTexImage2DEXTCmd },
    { "::ntk::gl::GLext::glCopyTexSubImage1DEXT",
            NULL, TclGLext_glCopyTexSubImage1DEXTCmd },
    { "::ntk::gl::GLext::glCopyTexSubImage2DEXT",
            NULL, TclGLext_glCopyTexSubImage2DEXTCmd },
    { "::ntk::gl::GLext::glCopyTexSubImage3DEXT",
            NULL, TclGLext_glCopyTexSubImage3DEXTCmd },
    { "::ntk::gl::GLext::glGetHistogramEXT",
            NULL, TclGLext_glGetHistogramEXTCmd },
    { "::ntk::gl::GLext::glGetHistogramParameterfvEXT",
            NULL, TclGLext_glGetHistogramParameterfvEXTCmd },
    { "::ntk::gl::GLext::glGetHistogramParameterivEXT",
            NULL, TclGLext_glGetHistogramParameterivEXTCmd },
    { "::ntk::gl::GLext::glGetMinmaxEXT",
            NULL, TclGLext_glGetMinmaxEXTCmd },
    { "::ntk::gl::GLext::glGetMinmaxParameterfvEXT",
            NULL, TclGLext_glGetMinmaxParameterfvEXTCmd },
    { "::ntk::gl::GLext::glGetMinmaxParameterivEXT",
            NULL, TclGLext_glGetMinmaxParameterivEXTCmd },
    { "::ntk::gl::GLext::glHistogramEXT",
            NULL, TclGLext_glHistogramEXTCmd },
    { "::ntk::gl::GLext::glMinmaxEXT",
            NULL, TclGLext_glMinmaxEXTCmd },
    { "::ntk::gl::GLext::glResetHistogramEXT",
            NULL, TclGLext_glResetHistogramEXTCmd },
    { "::ntk::gl::GLext::glResetMinmaxEXT",
            NULL, TclGLext_glResetMinmaxEXTCmd },
    { "::ntk::gl::GLext::glConvolutionFilter1DEXT",
            NULL, TclGLext_glConvolutionFilter1DEXTCmd },
    { "::ntk::gl::GLext::glConvolutionFilter2DEXT",
            NULL, TclGLext_glConvolutionFilter2DEXTCmd },
    { "::ntk::gl::GLext::glConvolutionParameterfEXT",
            NULL, TclGLext_glConvolutionParameterfEXTCmd },
    { "::ntk::gl::GLext::glConvolutionParameterfvEXT",
            NULL, TclGLext_glConvolutionParameterfvEXTCmd },
    { "::ntk::gl::GLext::glConvolutionParameteriEXT",
            NULL, TclGLext_glConvolutionParameteriEXTCmd },
    { "::ntk::gl::GLext::glConvolutionParameterivEXT",
            NULL, TclGLext_glConvolutionParameterivEXTCmd },
    { "::ntk::gl::GLext::glCopyConvolutionFilter1DEXT",
            NULL, TclGLext_glCopyConvolutionFilter1DEXTCmd },
    { "::ntk::gl::GLext::glCopyConvolutionFilter2DEXT",
            NULL, TclGLext_glCopyConvolutionFilter2DEXTCmd },
    { "::ntk::gl::GLext::glGetConvolutionFilterEXT",
            NULL, TclGLext_glGetConvolutionFilterEXTCmd },
    { "::ntk::gl::GLext::glGetConvolutionParameterfvEXT",
            NULL, TclGLext_glGetConvolutionParameterfvEXTCmd },
    { "::ntk::gl::GLext::glGetConvolutionParameterivEXT",
            NULL, TclGLext_glGetConvolutionParameterivEXTCmd },
    { "::ntk::gl::GLext::glGetSeparableFilterEXT",
            NULL, TclGLext_glGetSeparableFilterEXTCmd },
    { "::ntk::gl::GLext::glSeparableFilter2DEXT",
            NULL, TclGLext_glSeparableFilter2DEXTCmd },
    { "::ntk::gl::GLext::glAreTexturesResidentEXT",
            NULL, TclGLext_glAreTexturesResidentEXTCmd },
    { "::ntk::gl::GLext::glBindTextureEXT",
            NULL, TclGLext_glBindTextureEXTCmd },
    { "::ntk::gl::GLext::glDeleteTexturesEXT",
            NULL, TclGLext_glDeleteTexturesEXTCmd },
    { "::ntk::gl::GLext::glGenTexturesEXT",
            NULL, TclGLext_glGenTexturesEXTCmd },
    { "::ntk::gl::GLext::glIsTextureEXT",
            NULL, TclGLext_glIsTextureEXTCmd },
    { "::ntk::gl::GLext::glPrioritizeTexturesEXT",
            NULL, TclGLext_glPrioritizeTexturesEXTCmd },
    { "::ntk::gl::GLext::glArrayElementEXT",
            NULL, TclGLext_glArrayElementEXTCmd },
    { "::ntk::gl::GLext::glColorPointerEXT",
            NULL, TclGLext_glColorPointerEXTCmd },
    { "::ntk::gl::GLext::glDrawArraysEXT",
            NULL, TclGLext_glDrawArraysEXTCmd },
    { "::ntk::gl::GLext::glEdgeFlagPointerEXT",
            NULL, TclGLext_glEdgeFlagPointerEXTCmd },
    { "::ntk::gl::GLext::glGetPointervEXT",
            NULL, TclGLext_glGetPointervEXTCmd },
    { "::ntk::gl::GLext::glIndexPointerEXT",
            NULL, TclGLext_glIndexPointerEXTCmd },
    { "::ntk::gl::GLext::glNormalPointerEXT",
            NULL, TclGLext_glNormalPointerEXTCmd },
    { "::ntk::gl::GLext::glTexCoordPointerEXT",
            NULL, TclGLext_glTexCoordPointerEXTCmd },
    { "::ntk::gl::GLext::glVertexPointerEXT",
            NULL, TclGLext_glVertexPointerEXTCmd },
    { "::ntk::gl::GLext::glBlendEquationEXT",
            NULL, TclGLext_glBlendEquationEXTCmd },
    { "::ntk::gl::GLext::glPointParameterfEXT",
            NULL, TclGLext_glPointParameterfEXTCmd },
    { "::ntk::gl::GLext::glPointParameterfvEXT",
            NULL, TclGLext_glPointParameterfvEXTCmd },
    { "::ntk::gl::GLext::glColorSubTableEXT",
            NULL, TclGLext_glColorSubTableEXTCmd },
    { "::ntk::gl::GLext::glCopyColorSubTableEXT",
            NULL, TclGLext_glCopyColorSubTableEXTCmd },
    { "::ntk::gl::GLext::glColorTableEXT",
            NULL, TclGLext_glColorTableEXTCmd },
    { "::ntk::gl::GLext::glGetColorTableEXT",
            NULL, TclGLext_glGetColorTableEXTCmd },
    { "::ntk::gl::GLext::glGetColorTableParameterivEXT",
            NULL, TclGLext_glGetColorTableParameterivEXTCmd },
    { "::ntk::gl::GLext::glGetColorTableParameterfvEXT",
            NULL, TclGLext_glGetColorTableParameterfvEXTCmd },
    { "::ntk::gl::GLext::glIndexMaterialEXT",
            NULL, TclGLext_glIndexMaterialEXTCmd },
    { "::ntk::gl::GLext::glIndexFuncEXT",
            NULL, TclGLext_glIndexFuncEXTCmd },
    { "::ntk::gl::GLext::glLockArraysEXT",
            NULL, TclGLext_glLockArraysEXTCmd },
    { "::ntk::gl::GLext::glUnlockArraysEXT",
            NULL, TclGLext_glUnlockArraysEXTCmd },
    { "::ntk::gl::GLext::glCullParameterdvEXT",
            NULL, TclGLext_glCullParameterdvEXTCmd },
    { "::ntk::gl::GLext::glCullParameterfvEXT",
            NULL, TclGLext_glCullParameterfvEXTCmd },
    { "::ntk::gl::GLext::glDrawRangeElementsEXT",
            NULL, TclGLext_glDrawRangeElementsEXTCmd },
    { "::ntk::gl::GLext::glApplyTextureEXT",
            NULL, TclGLext_glApplyTextureEXTCmd },
    { "::ntk::gl::GLext::glTextureLightEXT",
            NULL, TclGLext_glTextureLightEXTCmd },
    { "::ntk::gl::GLext::glTextureMaterialEXT",
            NULL, TclGLext_glTextureMaterialEXTCmd },
    { "::ntk::gl::GLext::glPixelTransformParameteriEXT",
            NULL, TclGLext_glPixelTransformParameteriEXTCmd },
    { "::ntk::gl::GLext::glPixelTransformParameterfEXT",
            NULL, TclGLext_glPixelTransformParameterfEXTCmd },
    { "::ntk::gl::GLext::glPixelTransformParameterivEXT",
            NULL, TclGLext_glPixelTransformParameterivEXTCmd },
    { "::ntk::gl::GLext::glPixelTransformParameterfvEXT",
            NULL, TclGLext_glPixelTransformParameterfvEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3bEXT",
            NULL, TclGLext_glSecondaryColor3bEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3bvEXT",
            NULL, TclGLext_glSecondaryColor3bvEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3dEXT",
            NULL, TclGLext_glSecondaryColor3dEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3dvEXT",
            NULL, TclGLext_glSecondaryColor3dvEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3fEXT",
            NULL, TclGLext_glSecondaryColor3fEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3fvEXT",
            NULL, TclGLext_glSecondaryColor3fvEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3iEXT",
            NULL, TclGLext_glSecondaryColor3iEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3ivEXT",
            NULL, TclGLext_glSecondaryColor3ivEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3sEXT",
            NULL, TclGLext_glSecondaryColor3sEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3svEXT",
            NULL, TclGLext_glSecondaryColor3svEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3ubEXT",
            NULL, TclGLext_glSecondaryColor3ubEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3ubvEXT",
            NULL, TclGLext_glSecondaryColor3ubvEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3uiEXT",
            NULL, TclGLext_glSecondaryColor3uiEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3uivEXT",
            NULL, TclGLext_glSecondaryColor3uivEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3usEXT",
            NULL, TclGLext_glSecondaryColor3usEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColor3usvEXT",
            NULL, TclGLext_glSecondaryColor3usvEXTCmd },
    { "::ntk::gl::GLext::glSecondaryColorPointerEXT",
            NULL, TclGLext_glSecondaryColorPointerEXTCmd },
    { "::ntk::gl::GLext::glTextureNormalEXT",
            NULL, TclGLext_glTextureNormalEXTCmd },
    { "::ntk::gl::GLext::glMultiDrawArraysEXT",
            NULL, TclGLext_glMultiDrawArraysEXTCmd },
    { "::ntk::gl::GLext::glMultiDrawElementsEXT",
            NULL, TclGLext_glMultiDrawElementsEXTCmd },
    { "::ntk::gl::GLext::glFogCoordfEXT",
            NULL, TclGLext_glFogCoordfEXTCmd },
    { "::ntk::gl::GLext::glFogCoordfvEXT",
            NULL, TclGLext_glFogCoordfvEXTCmd },
    { "::ntk::gl::GLext::glFogCoorddEXT",
            NULL, TclGLext_glFogCoorddEXTCmd },
    { "::ntk::gl::GLext::glFogCoorddvEXT",
            NULL, TclGLext_glFogCoorddvEXTCmd },
    { "::ntk::gl::GLext::glFogCoordPointerEXT",
            NULL, TclGLext_glFogCoordPointerEXTCmd },
    { "::ntk::gl::GLext::glTangent3bEXT",
            NULL, TclGLext_glTangent3bEXTCmd },
    { "::ntk::gl::GLext::glTangent3bvEXT",
            NULL, TclGLext_glTangent3bvEXTCmd },
    { "::ntk::gl::GLext::glTangent3dEXT",
            NULL, TclGLext_glTangent3dEXTCmd },
    { "::ntk::gl::GLext::glTangent3dvEXT",
            NULL, TclGLext_glTangent3dvEXTCmd },
    { "::ntk::gl::GLext::glTangent3fEXT",
            NULL, TclGLext_glTangent3fEXTCmd },
    { "::ntk::gl::GLext::glTangent3fvEXT",
            NULL, TclGLext_glTangent3fvEXTCmd },
    { "::ntk::gl::GLext::glTangent3iEXT",
            NULL, TclGLext_glTangent3iEXTCmd },
    { "::ntk::gl::GLext::glTangent3ivEXT",
            NULL, TclGLext_glTangent3ivEXTCmd },
    { "::ntk::gl::GLext::glTangent3sEXT",
            NULL, TclGLext_glTangent3sEXTCmd },
    { "::ntk::gl::GLext::glTangent3svEXT",
            NULL, TclGLext_glTangent3svEXTCmd },
    { "::ntk::gl::GLext::glBinormal3bEXT",
            NULL, TclGLext_glBinormal3bEXTCmd },
    { "::ntk::gl::GLext::glBinormal3bvEXT",
            NULL, TclGLext_glBinormal3bvEXTCmd },
    { "::ntk::gl::GLext::glBinormal3dEXT",
            NULL, TclGLext_glBinormal3dEXTCmd },
    { "::ntk::gl::GLext::glBinormal3dvEXT",
            NULL, TclGLext_glBinormal3dvEXTCmd },
    { "::ntk::gl::GLext::glBinormal3fEXT",
            NULL, TclGLext_glBinormal3fEXTCmd },
    { "::ntk::gl::GLext::glBinormal3fvEXT",
            NULL, TclGLext_glBinormal3fvEXTCmd },
    { "::ntk::gl::GLext::glBinormal3iEXT",
            NULL, TclGLext_glBinormal3iEXTCmd },
    { "::ntk::gl::GLext::glBinormal3ivEXT",
            NULL, TclGLext_glBinormal3ivEXTCmd },
    { "::ntk::gl::GLext::glBinormal3sEXT",
            NULL, TclGLext_glBinormal3sEXTCmd },
    { "::ntk::gl::GLext::glBinormal3svEXT",
            NULL, TclGLext_glBinormal3svEXTCmd },
    { "::ntk::gl::GLext::glTangentPointerEXT",
            NULL, TclGLext_glTangentPointerEXTCmd },
    { "::ntk::gl::GLext::glBinormalPointerEXT",
            NULL, TclGLext_glBinormalPointerEXTCmd },
    { "::ntk::gl::GLext::glBlendFuncSeparateEXT",
            NULL, TclGLext_glBlendFuncSeparateEXTCmd },
    { "::ntk::gl::GLext::glVertexWeightfEXT",
            NULL, TclGLext_glVertexWeightfEXTCmd },
    { "::ntk::gl::GLext::glVertexWeightfvEXT",
            NULL, TclGLext_glVertexWeightfvEXTCmd },
    { "::ntk::gl::GLext::glVertexWeightPointerEXT",
            NULL, TclGLext_glVertexWeightPointerEXTCmd },
    { "::ntk::gl::GLext::glSampleMaskEXT",
            NULL, TclGLext_glSampleMaskEXTCmd },
    { "::ntk::gl::GLext::glSamplePatternEXT",
            NULL, TclGLext_glSamplePatternEXTCmd },
    { "::ntk::gl::GLext::glBeginVertexShaderEXT",
            NULL, TclGLext_glBeginVertexShaderEXTCmd },
    { "::ntk::gl::GLext::glEndVertexShaderEXT",
            NULL, TclGLext_glEndVertexShaderEXTCmd },
    { "::ntk::gl::GLext::glBindVertexShaderEXT",
            NULL, TclGLext_glBindVertexShaderEXTCmd },
    { "::ntk::gl::GLext::glGenVertexShadersEXT",
            NULL, TclGLext_glGenVertexShadersEXTCmd },
    { "::ntk::gl::GLext::glDeleteVertexShaderEXT",
            NULL, TclGLext_glDeleteVertexShaderEXTCmd },
    { "::ntk::gl::GLext::glShaderOp1EXT",
            NULL, TclGLext_glShaderOp1EXTCmd },
    { "::ntk::gl::GLext::glShaderOp2EXT",
            NULL, TclGLext_glShaderOp2EXTCmd },
    { "::ntk::gl::GLext::glShaderOp3EXT",
            NULL, TclGLext_glShaderOp3EXTCmd },
    { "::ntk::gl::GLext::glSwizzleEXT",
            NULL, TclGLext_glSwizzleEXTCmd },
    { "::ntk::gl::GLext::glWriteMaskEXT",
            NULL, TclGLext_glWriteMaskEXTCmd },
    { "::ntk::gl::GLext::glInsertComponentEXT",
            NULL, TclGLext_glInsertComponentEXTCmd },
    { "::ntk::gl::GLext::glExtractComponentEXT",
            NULL, TclGLext_glExtractComponentEXTCmd },
    { "::ntk::gl::GLext::glGenSymbolsEXT",
            NULL, TclGLext_glGenSymbolsEXTCmd },
    { "::ntk::gl::GLext::glSetInvariantEXT",
            NULL, TclGLext_glSetInvariantEXTCmd },
    { "::ntk::gl::GLext::glSetLocalConstantEXT",
            NULL, TclGLext_glSetLocalConstantEXTCmd },
    { "::ntk::gl::GLext::glVariantbvEXT",
            NULL, TclGLext_glVariantbvEXTCmd },
    { "::ntk::gl::GLext::glVariantsvEXT",
            NULL, TclGLext_glVariantsvEXTCmd },
    { "::ntk::gl::GLext::glVariantivEXT",
            NULL, TclGLext_glVariantivEXTCmd },
    { "::ntk::gl::GLext::glVariantfvEXT",
            NULL, TclGLext_glVariantfvEXTCmd },
    { "::ntk::gl::GLext::glVariantdvEXT",
            NULL, TclGLext_glVariantdvEXTCmd },
    { "::ntk::gl::GLext::glVariantubvEXT",
            NULL, TclGLext_glVariantubvEXTCmd },
    { "::ntk::gl::GLext::glVariantusvEXT",
            NULL, TclGLext_glVariantusvEXTCmd },
    { "::ntk::gl::GLext::glVariantuivEXT",
            NULL, TclGLext_glVariantuivEXTCmd },
    { "::ntk::gl::GLext::glVariantPointerEXT",
            NULL, TclGLext_glVariantPointerEXTCmd },
    { "::ntk::gl::GLext::glEnableVariantClientStateEXT",
            NULL, TclGLext_glEnableVariantClientStateEXTCmd },
    { "::ntk::gl::GLext::glDisableVariantClientStateEXT",
            NULL, TclGLext_glDisableVariantClientStateEXTCmd },
    { "::ntk::gl::GLext::glBindLightParameterEXT",
            NULL, TclGLext_glBindLightParameterEXTCmd },
    { "::ntk::gl::GLext::glBindMaterialParameterEXT",
            NULL, TclGLext_glBindMaterialParameterEXTCmd },
    { "::ntk::gl::GLext::glBindTexGenParameterEXT",
            NULL, TclGLext_glBindTexGenParameterEXTCmd },
    { "::ntk::gl::GLext::glBindTextureUnitParameterEXT",
            NULL, TclGLext_glBindTextureUnitParameterEXTCmd },
    { "::ntk::gl::GLext::glBindParameterEXT",
            NULL, TclGLext_glBindParameterEXTCmd },
    { "::ntk::gl::GLext::glIsVariantEnabledEXT",
            NULL, TclGLext_glIsVariantEnabledEXTCmd },
    { "::ntk::gl::GLext::glGetVariantBooleanvEXT",
            NULL, TclGLext_glGetVariantBooleanvEXTCmd },
    { "::ntk::gl::GLext::glGetVariantIntegervEXT",
            NULL, TclGLext_glGetVariantIntegervEXTCmd },
    { "::ntk::gl::GLext::glGetVariantFloatvEXT",
            NULL, TclGLext_glGetVariantFloatvEXTCmd },
    { "::ntk::gl::GLext::glGetVariantPointervEXT",
            NULL, TclGLext_glGetVariantPointervEXTCmd },
    { "::ntk::gl::GLext::glGetInvariantBooleanvEXT",
            NULL, TclGLext_glGetInvariantBooleanvEXTCmd },
    { "::ntk::gl::GLext::glGetInvariantIntegervEXT",
            NULL, TclGLext_glGetInvariantIntegervEXTCmd },
    { "::ntk::gl::GLext::glGetInvariantFloatvEXT",
            NULL, TclGLext_glGetInvariantFloatvEXTCmd },
    { "::ntk::gl::GLext::glGetLocalConstantBooleanvEXT",
            NULL, TclGLext_glGetLocalConstantBooleanvEXTCmd },
    { "::ntk::gl::GLext::glGetLocalConstantIntegervEXT",
            NULL, TclGLext_glGetLocalConstantIntegervEXTCmd },
    { "::ntk::gl::GLext::glGetLocalConstantFloatvEXT",
            NULL, TclGLext_glGetLocalConstantFloatvEXTCmd },
    { "::ntk::gl::GLext::glActiveStencilFaceEXT",
            NULL, TclGLext_glActiveStencilFaceEXTCmd },
    { "::ntk::gl::GLext::glProgramNamedParameter4fNV",
            NULL, TclGLext_glProgramNamedParameter4fNVCmd },
    { "::ntk::gl::GLext::glProgramNamedParameter4dNV",
            NULL, TclGLext_glProgramNamedParameter4dNVCmd },
    { "::ntk::gl::GLext::glProgramNamedParameter4fvNV",
            NULL, TclGLext_glProgramNamedParameter4fvNVCmd },
    { "::ntk::gl::GLext::glProgramNamedParameter4dvNV",
            NULL, TclGLext_glProgramNamedParameter4dvNVCmd },
    { "::ntk::gl::GLext::glGetProgramNamedParameterfvNV",
            NULL, TclGLext_glGetProgramNamedParameterfvNVCmd },
    { "::ntk::gl::GLext::glGetProgramNamedParameterdvNV",
            NULL, TclGLext_glGetProgramNamedParameterdvNVCmd },
    { "::ntk::gl::GLext::glDepthBoundsEXT",
            NULL, TclGLext_glDepthBoundsEXTCmd },
    { "::ntk::gl::GLext::glBlendEquationSeparateEXT",
            NULL, TclGLext_glBlendEquationSeparateEXTCmd },
